### ISSUE TITLE
Error when importing from flexflow.torch.model

### ISSUE THREAD

**Issue by Efrainq07** [flexflow/FlexFlow#100]
![image](https://user-images.githubusercontent.com/33973526/109084867-333e6600-76ce-11eb-93f2-a88b1c8fcd4f.png)
I was trying to run the `$FF_HOME/examples/python/pytorch/resnet.py` file but this error appeared. Upon further inspection I found that the same error happens if you just run `from flexflow.torch.model import PyTorchModel`.

I had found this error before when trying to run `import torch`. I also followed the message mentioned there (I assum runtime/runtime.mk mean $FF_HOME/legion/runtime/runtime.mk) and rebuilt again but that didn't seem to make a difference.
Is this a known error?

**Comment by eddy16112** [comment]
That is because the CUDA portion of the torch is conflicted with Legion runtime. You can try to install the cpu only torch, and it will solve your problem.

**Comment by Efrainq07** [comment]
I did `conda install pytorch-cpu torchvision-cpu -c pytorch-nightly` in order to install cpu only torch but this error appears:
`ModuleNotFoundError: No module named 'torch.fx'`
I understand `fx` is only available on the nightly build of pytorch and I guess it's not yet included on the cpu only version.
Is there a recommended pytorch build to run `$FF_HOME/examples/python/pytorch/resnet.py`?

**Comment by eddy16112** [comment]
I can not remember whether I use conda or pip. Can you please try to use pip?
pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
I am not sure if torch.fx has been moved into stable release, but it is already in the nightly release.

**Comment by Efrainq07** [comment]
That build solved the issue, thanks.
