### ISSUE TITLE
Assertion `batch_size == meta->num_samples' failed when trying to run flexflow with more than 2 GPU's

### ISSUE THREAD

**Issue by Efrainq07** [flexflow/FlexFlow#102]
I ran the next line on `$FF_HOME/python` with the script found on the examples folder `$FF_HOME/examples/python/pytorch/resnet.py`:
`./flexflow_python $FF_HOME/examples/python/pytorch/resnet.py -ll:py 1 -ll:gpu 2 -ll:fsize 14000 -ll:zsize 12192 --epochs 2 --batch-size 30 -lg:no_trace_optimization`
And this error appeared:
`flexflow_python: flexflow_dataloader.cu:132: static void SingleDataLoader::load_input_with_dim(const Legion::Task*, const std::vector<Legion::PhysicalRegion>&, Legion::Context, Legion::Runtime*) [with DT = float; int NDIM = 4; Legion::Context = Legion::Internal::TaskContext*]: Assertion `batch_size == meta->num_samples' failed.`

If I run the very same line but without changing the batchsize and using the default size of 64 the error doesn't appear and the script works as intended.

**Comment by eddy16112** [comment]
I am sorry I can not reproduce the bug. I run the resnet like this and it runs fine. 
./flexflow_python ../examples/python/pytorch/resnet.py -ll:py 1 -ll:gpu 2 -ll:fsize 2048 -ll:zsize 12192 -b 30
Can you please print the batch_size and num_samples before the assert?

**Comment by eddy16112** [comment]
One thing I would like to mention is when you creating a tensor 
input = [ffconfig.get_batch_size(), 3, 229, 229],
You will need to use `ffconfig.get_batch_size()`, instead of hard coding the batch size, because the batch size will always be read from the cmd line.
