### ISSUE TITLE
Error of 'pip install flexflow'

### ISSUE THREAD

**Issue by guanchuwang** [flexflow/FlexFlow#1025]
raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-S', '/tmp/pip-install-0sbdiigi/flexflow_22f8531c8dfd479b81f07a6ea4bbcf8c', '-B', '/tmp/pip-install-0sbdiigi/flexflow_22f8531c8dfd479b81f07a6ea4bbcf8c/build/temp.linux-x86_64-cpython-311_flexflow', '-GNinja', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-0sbdiigi/flexflow_22f8531c8dfd479b81f07a6ea4bbcf8c/build/lib.linux-x86_64-cpython-311/flexflow', '-DCMAKE_MAKE_PROGRAM=/tmp/pip-build-env-zasy0zxv/overlay/bin/ninja', '-DCUDA_USE_STATIC_CUDA_RUNTIME=OFF', '-DLegion_HIJACK_CUDART=OFF', '-DINFERENCE_TESTS=OFF', '-DLIBTORCH_PATH=/tmp/libtorch', '-DCMAKE_BUILD_TYPE=Release', '-DFF_CUDA_ARCH=autodetect', '-DCUDA_PATH=/usr/local/cuda', '-DCUDNN_PATH=/usr/local/cuda', '-DFF_USE_PYTHON=ON', '-DFF_USE_NCCL=ON', '-DNCCL_PATH=/usr/local/cuda', '-DFF_BUILD_ALL_EXAMPLES=OFF', '-DFF_BUILD_ALL_INFERENCE_EXAMPLES=ON', '-DFF_USE_PREBUILT_LEGION=OFF', '-DFF_USE_PREBUILT_NCCL=OFF', '-DFF_USE_ALL_PREBUILT_LIBRARIES=OFF', '-DFF_BUILD_UNIT_TESTS=OFF', '-DFF_USE_AVX2=OFF', '-DFF_MAX_DIM=5', '-DLEGION_MAX_RETURN_SIZE=262144', '-DROCM_PATH=/opt/rocm', '-DFF_GPU_BACKEND=cuda', '-DFF_BUILD_FROM_PYPI=ON']' returned non-zero exit status 1.

**Comment by jiazhihao** [comment]
This is a cmake error. Can you also share with us the specific cmake error message you got (e.g., send us the full output of `pip install flexflow --verbose`)? This will help us locate the issue.

Meanwhile, you can also try the docker images, which will avoid any build dependency issues.

**Comment by guanchuwang** [comment]
> This is a cmake error. Can you also share with us the specific cmake error message you got (e.g., send us the full output of `pip install flexflow --verbose`)? This will help us locate the issue.
> 
> Meanwhile, you can also try the docker images, which will avoid any build dependency issues.

Thank you for the quick reply! :) I use the docker container instead. However, I met a new problem. I used "docker run --gpus all -it --rm --shm-size=8g ghcr.io/flexflow/flexflow-cuda-11.6:latest" to run the pre-built Docker container. Then I run "CUDA_VISIBLE_DEVICES=4,5,6,7 python examples/python/pytorch/resnet.py" in the container. It returns an error that as follow:

Using cffi flexflow bindings.
Using flexflow backend.
resnet torch
b''
Python API batchSize(64) workersPerNodes(1) numNodes(1)
workSpaceSize (1024 MB)
[0 - 7f6a2662d740]    3.414131 {6}{inst}: instance allocation failed - out of memory in mem 1e00000000000002
Aborted (core dumped)

My GPUs 4,5,6,7 have 32GB memory (V100). Could you tell me the reason for this error?

**Comment by jiazhihao** [comment]
`pip install flexflow` is mainly for FlexFlow Serve. If you want to train DNNs with FlexFlow, you may want to use `$FF_HOME/build/flexflow_python` and add corresponding command line flags. Some examples are available at https://github.com/flexflow/FlexFlow/blob/inference/tests/multi_gpu_tests.sh
