### ISSUE TITLE
Methodology for training LLaMA 68M

### ISSUE THREAD

**Issue by cadedaniel** [flexflow/FlexFlow#1028]
Hi, nice project!

Seems from the paper there is no discussion on how the 68M LLaMA SSM was trained. How was it trained?

**Comment by JackFram** [comment]
Thx for your interest! The 68M LLaMA SSM is trained in a similar way as the 160M LLaMA, which is by training one epoch on Wikipedia, C4-RealNewsLike, and part of the C4-en dataset.

**Comment by cadedaniel** [comment]
Thanks!
