### ISSUE TITLE
Mismatch Error for LLaMA-2-70b

### ISSUE THREAD

**Issue by zhendong-nexusflow** [flexflow/FlexFlow#1033]
Hi Flexflow team,

Thank you so much for your great work!
It would be great if you can help me have a look at this mismatch error I got when I tried to run LLaMA-2-70b.
I'm using 8 gpus, memory_per_gpu: 78000, zero_copy_memory_per_node: 78000, tensor_parallelism_degree: 8, pipeline_parallelism_degree: 1.
Note that I can successfully run llama-2-7b and llama-2-13b. I deliberately chose pipeline parallel to be 1 for large llama-2 models.

Here is the error I got:
operator[487]: type(93)
        inputs[0] region(13735,1528,1528)
        outputs[0] region(13744,1529,1529)
operator[488]: type(87)
        inputs[0] region(13744,1529,1529)
        outputs[0] region(13746,1530,1530)
Loading hf weights...
Creating directory /home/.cache/flexflow/weights/meta-llama/llama-2-70b-hf/full-precision (if it doesn't exist)...
Loading 'meta-llama/Llama-2-70b-hf' model weights from the cache...
load weights: layers_79_feed_forward_w2_weight
load weights: layers_79_feed_forward_w3_weight
load weights: layers_79_feed_forward_w1_weight
load weights: layers_79_attention_norm_weight
load weights: layers_78_feed_forward_w2_weight
load weights: layers_78_attention_weight
load attention data error 33554432, 268435456, 1, /home/.cache/flexflow/weights/meta-llama/llama-2-70b-hf/full-precision/layers_78_attention_wk_weight
python: /var/tmp/pip-install-tdqee6zg/flexflow_1b7efa369d4b4739b0ef73b24b49a2c0/inference/file_loader.cc:245: void load_attention_weights_v2(DT*, int, int, size_t, size_t, std::string, std::string, size_t, int) [with DT = float; size_t = long unsigned int; std::string = std::__cxx11::basic_string<char>]: Assertion `false && "data size mismatch"' failed.
Aborted

Thank you in advance!

**Comment by zhendong-nexusflow** [comment]
By the way, If I run Llama-65b-hf with the same setting, I got:

load weights: layers_60_feed_forward_w3_weight
load weights: layers_33_attention_weight
load weights: layers_35_ffn_norm_weight
load weights: layers_36_ffn_norm_weight
load weights: layers_72_attention_weight
load weights: layers_68_attention_norm_weight
load weights: layers_58_attention_weight
load weights: layers_17_attention_weight
load weights: layers_14_feed_forward_w2_weight
load weights: layers_16_feed_forward_w2_weight
load weights: layers_16_feed_forward_w3_weight
load weights: layers_28_attention_norm_weight
load weights: layers_16_ffn_norm_weight
load weights: layers_70_ffn_norm_weight
load weights: layers_4_feed_forward_w2_weight
load weights: layers_16_feed_forward_w1_weight
load weights: layers_62_ffn_norm_weight
load weights: layers_15_ffn_norm_weight
load weights: layers_30_feed_forward_w3_weight
load weights: layers_14_feed_forward_w3_weight
load weights: layers_11_attention_weight
[0 - 7f9c905b7740]  129.892127 {5}{Mapper}: FlexFlow Mapper failed allocation of size 1073741824 bytes for region requirement of inline ammping in task legion_python_top_level_task (UID 1) in memory 1e00000000000012for processor 1d00000000000008.
python: /var/tmp/pip-install-tdqee6zg/flexflow_1b7efa369d4b4739b0ef73b24b49a2c0/src/mapper/mapper.cc:944: virtual void FlexFlow::FFMapper::map_inline(Legion::Mapping::MapperContext, const Legion::InlineMapping&, const Legion::Mapping::Mapper::MapInlineInput&, Legion::Mapping::Mapper::MapInlineOutput&): Assertion `false' failed.
Aborted

**Comment by jiazhihao** [comment]
@xinhaoc @goliaro Is this because LLAMA-2's group-attention has different number of KV heads and queries?

**Comment by goliaro** [comment]
@zhendong-nexusflow added this to the TODO list!

**Comment by damon-mosk-aoyama-nexusflow** [comment]
I encountered this assertion error when trying to load the `codellama/CodeLlama-34b-Instruct-hf` model, which has different values for the `num_attention_heads` and `num_key_value_heads` fields in the `config.json` file.  It appears that the argument value for the number of key/value heads passed to the `FileDataLoader` constructor is set to the number of attention heads here:

https://github.com/flexflow/FlexFlow/blob/inference/python/flexflow/serve/serve.py#L265

Should the `n_kv_heads` variable be set to `self.hf_config.num_key_value_heads` if the `num_key_value_heads` value is present in the configuration, at least for specific model types?

**Comment by xinhaoc** [comment]
Hi @zhendong-nexusflow thanks for the catch! we'll give a quick fix recently.

**Comment by xinhaoc** [comment]
@zhendong-nexusflow fixed now
