### ISSUE TITLE
Does specInfer add prompt templates during funetuning/inference?

### ISSUE THREAD

**Issue by LiuXiaoxuanPKU** [flexflow/FlexFlow#1036]
Thanks for the great project! I'm wondering if specInfer adds prompt template during finetuning/inference?

For example in inference, if you use the vicuna model and the dataset question (Q1) is 
`Give me a five-day Hawaii travel plan`.

After adding the prompt template, Q1' will be
`A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: Give me a five-day Hawaii travel plan ASSISTANT: "`

The model will generate an answer with Q1' as the input.

Does specInfer do something similar for LLaMa-7B model? Or does SpecInfer take Q1 as the input?

**Comment by goliaro** [comment]
Hi Lily, I'm glad that you asked! We're working on adding support for prompt templates, and Vicuna is one of the first model we're definitely going to support. So stay tuned! I'm adding this issue to the development roadmap, and you should see a PR coming up very soon!

**Comment by LiuXiaoxuanPKU** [comment]
Thanks for adding the support! I'm also curious about the setting for the paper (https://arxiv.org/abs/2305.09781). Does it take the original Q1 as the input for both fine-tuning and inference?

**Comment by goliaro** [comment]
yes, for the experiments in the paper, the original Q1 from the prompt dataset is used

**Comment by LiuXiaoxuanPKU** [comment]
> yes, for the experiments in the paper, the original Q1 from the prompt dataset is used

Thanks! It makes sense, for llama-7b, it does not make too much sense to add prompt templates. I am looking forward to the prompt template and multi-round conversation support!

**Comment by LiuXiaoxuanPKU** [comment]
Also, has the fine-tuning script been released? We are interested in learning more about SpecInfer's learning-based Speculator. Thanks a lot!

**Comment by goliaro** [comment]
we haven't added support for fine-tuning yet, but are planning to do so over the course of next month or so

**Comment by goliaro** [comment]
@LiuXiaoxuanPKU You can try the code below to chat with models (such as Vicuna) that require a prompt template to generate good results:

```python
import flexflow.serve as ff

ff.init(
        num_gpus=4,
        memory_per_gpu=14000,
        zero_copy_memory_per_node=30000,
        tensor_parallelism_degree=4,
        pipeline_parallelism_degree=1
    )
# Specify the LLM
llm = ff.LLM("lmsys/vicuna-7b-v1.3")
# Create the sampling configs
generation_config = ff.GenerationConfig(
    do_sample=False, temperature=0.9, topp=0.8, topk=1
)
llm.compile(generation_config)

def get_vicuna_chat_prompt(user_prompt):
    vicuna_prompt_template = f"A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: {} ASSISTANT:"
    return vicuna_prompt_template.format(user_prompt)

vicuna_prompt = get_vicuna_chat_prompt("What's there to do in Tokyo?")

result = llm.generate(vicuna_prompt)
```

You can just write your own version of the `get_vicuna_chat_prompt` function for the model that you're interested in by replacing the `vicuna_prompt_template` with the relevant template for your model

Hope this helps!
