### ISSUE TITLE
Disable any tests that don't make sense for repo-refactor

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#1065]
Currently CI uses the set of tests from master plus some additional ones that @aquan9 added specifically for repo-refactor. Because of this, there are a bunch of tests that are enabled on master but fail on repo-refactor, and it is possible that some of these are due to them not making sense on repo-refactor or not having been updated to the new repo structure. You should go through the list of tests that are currently running on repo-refactor and write up in this issue a list of which tests don't make sense and should be removed as well as which make sense but need to be fixed

**Comment by lockshaw** [comment]
This will allow us to temporarily disable those tests that we know will fail (saving CI time), as well as to create issues for all of the tests that we want to fix and re-enable

**Comment by lambda7xx** [comment]
how to know which test is out of date? build it and find the failure one?
