### ISSUE TITLE
Mailing List

### ISSUE THREAD

**Issue by aowen14** [flexflow/FlexFlow#110]
In the README, it notes for Contributing:

"Please subscribe to the FlexFlow users mailing list for", but it doesn't include a way to join said mailing list. Is there a mailing list or other form of community to join?

**Comment by jiazhihao** [comment]
Thanks for your interests! Please join FlexFlow's mailing list: flexflow@googlegroups.com if you are interested in receiving FlexFlow updates. You can also join our [slack channel](https://join.slack.com/t/flexflowgroup/shared_invite/zt-njx37ylh-qBPvaRDs7c1yrysK9KMEqg) for posting FlexFlow-related questions.

**Comment by aowen14** [comment]
Thanks!
