### ISSUE TITLE
Increasing the limit on the number of tokens in a prompt

### ISSUE THREAD

**Issue by damon-mosk-aoyama-nexusflow** [flexflow/FlexFlow#1123]
Hi FlexFlow team,

We've been working on testing the performance of FlexFlow when serving the Llama 2 models in a web server that invokes the `generate` Python API for requests, and returns the responses.  We wanted to test the performance of the server on input prompts with over 1000 tokens.  However, these prompts exceeded the [maximum prompt length](https://github.com/flexflow/FlexFlow/blob/inference/src/runtime/request_manager.cc#L146) configuration parameter value, so meaningful responses were not returned.  We understand that it should be possible to change some configuration parameter values to increase this limit and build FlexFlow from source, but we don’t know whether other changes are required beyond those to the parameter values.  In particular, we would like to know whether changing the values [MAX_PROMPT_LENGTH](https://github.com/flexflow/FlexFlow/blob/inference/include/flexflow/batch_config.h#L51) and [MAX_SEQ_LENGTH](https://github.com/flexflow/FlexFlow/blob/inference/include/flexflow/batch_config.h#L52), and making no other changes, should work.

Thanks!

**Comment by lockshaw** [comment]
@xinhaoc @goliaro Any thoughts on this?
