### ISSUE TITLE
Improvements for graph

### ISSUE THREAD

**Issue by wmdi** [flexflow/FlexFlow#1198]
This issue is to track changes for improving the graph library that do not block compiler refactor.

- [ ] Improve the inheritance tree. Refer to https://github.com/flexflow/FlexFlow/pull/1189
- [ ] Improve `get_subgraph` for open graphs.
- [ ] Pointer cast for `cow_ptr_t`

**Comment by lockshaw** [comment]
@wmdi Reminder to divide this up into separate issues with brief descriptions 🙂

**Comment by wmdi** [comment]
This issue is split into #1283, #1284, and #1285.
