### ISSUE TITLE
model weights are always downloaded repeatedly.

### ISSUE THREAD

**Issue by 1193749292** [flexflow/FlexFlow#1236]
Take facebook/opt-6.7b as an example. The following information is displayed each time you run the facebook/opt-6.7b directory.
`/path/model/facebook/opt-6.7b' model weights not found in cache or outdated. Downloading from huggingface.co`
![image](https://github.com/flexflow/FlexFlow/assets/128877897/fa3e295f-8dfe-4710-8c73-ce8b9735e651)

```
llm = ff.LLM( "/path/model/model/facebook/opt-6.7b",cache_path="/path/model/model/facebook/opt-6.7b/half-precision")
```
When specifying the LLM, the weights_path and clean_cache parameters do not exist. Is there any parameter that can avoid this situation or other methods?

**Comment by jiazhihao** [comment]
@goliaro Can you take a look at this issue?

**Comment by goliaro** [comment]
Let me take a look!

**Comment by 1193749292** [comment]
@goliaro Thank you very much for your answer. I executed the script in the same directory as flexflow and it worked.

And then I want to ask, is there a way to omit unnecessary output when executing a lot of things?

**Comment by goliaro** [comment]
@1193749292 We'll add a non-verbose inference mode soon. In the meantime, feel free to comment out the print statements that you don't need

**Comment by xinlong-yang** [comment]
> @1193749292 We'll add a non-verbose inference mode soon. In the meantime, feel free to comment out the print statements that you don't need

hi, I wonder how to modify the cache path, I don't want cache model's weights in ~/.cache/flexflow, thanks!

**Comment by lockshaw** [comment]
> hi, I wonder how to modify the cache path, I don't want cache model's weights in ~/.cache/flexflow, thanks!

Moved to #1320.
