### ISSUE TITLE
Some problems in flewflow used in TopoOpt

### ISSUE THREAD

**Issue by Resurgence27** [flexflow/FlexFlow#1237]
I have some problems with flexflow which  is used in project [TopoOpt](https://github.com/hipersys-team/FlexFlow/tree/b1526834dd873604a680406fe153eaec08ceaf07) , all the following problems  I encounter in that flexflow's version
1.   after the instructions stated in Topoopt when run pytorch examples, it occurs error 
  > ERROR: The binary was compiled for the wrong GPU architecture. Update the 'GPU_ARCH' flag at the top of runtime/runtime.mk to match/include your current GPU architecture (80).

with the similar issue[154](https://github.com/flexflow/FlexFlow/issues/154), and I try to export the GPU_ARCH in runtime.mk and config.linux, it  doesn't work.

  2.   flewflow convert pytorch model to flexflow model which use `torch.fx.symblo_trace`. I try to load model use module tranfomer e.g. `from tranfomer import GPT2model` , to generate computational graph, it occurs error 
  > torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow

 maybe due to dynamic control flow and many optional parameters. How can I fix it?

3. Can flewflow directly use tensorflow model rather than convert it to keras model?

4.when the command args  include --measure, use flexflow_python to execute python file, it doesn't generate measure_<>_<>.json, which is mentioned in [README](https://github.com/hipersys-team/FlexFlow/tree/b1526834dd873604a680406fe153eaec08ceaf07#readme), I find in it doesn't use attribute measurement_only in [src/runtime/model.cc](https://github.com/hipersys-team/FlexFlow/blob/b1526834dd873604a680406fe153eaec08ceaf07/src/runtime/model.cc) to run measurement, maybe it should be completed in [fflexflow_c.cc](https://github.com/hipersys-team/FlexFlow/blob/b1526834dd873604a680406fe153eaec08ceaf07/python/flexflow_c.cc) and added in [flexflow_cffi_header.py](https://github.com/hipersys-team/FlexFlow/blob/b1526834dd873604a680406fe153eaec08ceaf07/python/flexflow/core/flexflow_cffi_header.py)

5.when run pytorch example [cifar10_cnn_py](https://github.com/hipersys-team/FlexFlow/blob/b1526834dd873604a680406fe153eaec08ceaf07/examples/python/pytorch/cifar10_cnn.py) at `torch_model.apply(ffmodel, [input_tensor, input_tensor])`it occurs error
> TypeError: conv2d(): incompatible function arguments. The following argument types are supported:
 (self: flexflow.core.flexflow_pybind11_internal.FFModel, 
input: flexflow.core.flexflow_pybind11_internal.Tensor, 
out_channels: int, kernel_h: int, kernel_w: int, stride_h: int, stride_w: int, padding_h: int, padding_w: int, 
activation: flexflow.core.flexflow_pybind11_internal.ActiMode = <ActiMode.AC_MODE_NONE: 10>, groups: int = 1, 
use_bias: bool = True, shared_op: flexflow.core.flexflow_pybind11_internal.Op = None,
kernel_initializer: flexflow.core.flexflow_pybind11_internal.Initializer = None, 
bias_initializer: flexflow.core.flexflow_pybind11_internal.Initializer = None, name: str = None)
->flexflow.core.flexflow_pybind11_internal.Tensor
>
>Innvoked with: <flexflow.core.flexflow_pybind11.FFModel object at 0x7f1dd05c9680>; 
kwargs: input=<flexflow.core.flexflow_pybind11_internal.Tensor object at 0x7f17e7dc5cb0>, 
out_channels=32, kernel_h=3, kernel_w=3, stride_h=1, stride_w=1, padding_h=0, padding_w=0, 
activation=<ActiMode.AC_MODE_NONE: 10>, groups=1, use_bias=True, name='conv1'

maybe due to the type `ActiMode` and `PoolTyle` conflicts in `flexflow.core.flexflow_type` and `flexflow.core.flexflow_pybind11_internal` , how can I fix it?

**Comment by Resurgence27** [comment]
@jiazhihao 
Sorry to disturbing you. Now I have some other problems with flexflow, could you solve them and reply to me? Thank you.
1. what is the meaning of `MachineView` and the relationship between `MachineView` and `ParallelConfig` and I find the num_dim of `MachineView` always less than `ParallelConfig` 
2. the meaning of `ParallelDims.degree`  is the max number can be shared along this dim? 
3. Why in the function below the `MachineView.dim[i]` must equal to `ParallelTensor.dim[i].degree` maybe it relates to the question 1 the meaning of `MachineView` 
```
bool ParallelTensorBase::get_sub_tensor(MachineView const &mv,
                                        ParallelTensorBase &sub_tensor) const {
  sub_tensor.num_dims = this->num_dims;
  for (int i = 0; i < sub_tensor.num_dims; i++) {
    sub_tensor.dims[i] = this->dims[i];
    if (this->dims[i].parallel_idx != -1) {
      int idx = this->dims[i].parallel_idx;
      assert(idx >= 0);
      assert(this->dims[i].degree == mv.dim[idx]);
      sub_tensor.dims[i].size /= mv.dim[idx];
      sub_tensor.dims[i].degree /= mv.dim[idx];
    }
  }
  return true;
}
```
4. the `ParallelTensor.dim[i].parallel_idx` can be thought the runtime index where that dim is allocate? and the `ParallelTensor.dim[i].parallel_idx` how associate with `ParallelTensor.dim[i].degree`
5. in [linear.cc](https://github.com/flexflow/FlexFlow/blob/inference/src/ops/linear.cc) there is two parallel strategy, so could I implement tensor parallel in `embedding` and `multiattention` operators only rewrite `Op::get_random_parallel_config`?
6. are there a conversion from `ParallelConfig` to `MachineView` for a specific operator?

**Comment by lockshaw** [comment]
> @jiazhihao Sorry for disturbing you. Now I have some other problems with flexflow, could you solve them and reply to me? Thank you.
> 
>     1. what is the meaning of `MachineView` and the relationship between `MachineView` and `ParallelConfig` and I find the num_dim of `MachineView` always less than `ParallelConfig`

Machine views are explained in the unity paper: https://www.usenix.org/conference/osdi22/presentation/unger

>     2. the meaning of `ParallelDims.degree`  is the max number can be shared along this dim?

It is the number of shards in that dimension.

>     3. Why in the function below the `MachineView.dim[i]` must equal to `ParallelTensor.dim[i].degree` maybe it relates to the question 1 the meaning of `MachineView`
> 
> 
> ```
> bool ParallelTensorBase::get_sub_tensor(MachineView const &mv,
>                                         ParallelTensorBase &sub_tensor) const {
>   sub_tensor.num_dims = this->num_dims;
>   for (int i = 0; i < sub_tensor.num_dims; i++) {
>     sub_tensor.dims[i] = this->dims[i];
>     if (this->dims[i].parallel_idx != -1) {
>       int idx = this->dims[i].parallel_idx;
>       assert(idx >= 0);
>       assert(this->dims[i].degree == mv.dim[idx]);
>       sub_tensor.dims[i].size /= mv.dim[idx];
>       sub_tensor.dims[i].degree /= mv.dim[idx];
>     }
>   }
>   return true;
> }
> ```

See part 1.

>     4. the `ParallelTensor.dim[i].parallel_idx` can be thought the runtime index where that dim is allocate? and the `ParallelTensor.dim[i].parallel_idx` how associate with `ParallelTensor.dim[i].degree`

`parallel_idx` is used to determine which shards are passed to which instance of the task.

>     5. in [linear.cc](https://github.com/flexflow/FlexFlow/blob/inference/src/ops/linear.cc) there is two parallel strategy, so could I implement tensor parallel in `embedding` and `multiattention` operators only rewrite `Op::get_random_parallel_config`?

I think `get_random_parallel_config` is actually no longer used, it was used in the original MCMC+simulator but has since been deprecated in favor of the algorithm from Unity. We hope to eventually bring back the MCMC algorithm as it provides a useful baseline, but currently this is not a high priority.

>     6. are there a conversion from `ParallelConfig` to `MachineView` for a specific operator?

See part 1.

**Comment by yjsunn** [comment]
hi, have you solve the first issue?  I also refer to https://github.com/flexflow/FlexFlow/issues/154 and change the FF_CUDA_ARCH in config.linux too. But it is not working.
