### ISSUE TITLE
Improve `get_subgraph` for open graphs

### ISSUE THREAD

**Issue by wmdi** [flexflow/FlexFlow#1284]
Currently `get_subgraph` for open graphs involves a template parameter to specify the open type of the subgraph (closed, upward open, downward open, or open). Change the design so that `get_subgraph` for open graphs always gives a fully open subgraph (for other types, we should call an additional conversion between different types of open graphs).

**Comment by lockshaw** [comment]
@wmdi According to https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXFiYg5H4L6MjeIFUV it seems that this issue tracks more than just `get_subgraph`--can you add additional detail to this issue or create an additional issue for the improvement mentioned there?

**Comment by lockshaw** [comment]
Closed as these graphs no longer exist.
