### ISSUE TITLE
Spec infer C++ examples blocked

### ISSUE THREAD

**Issue by reyna-abhyankar** [flexflow/FlexFlow#1319]
Specifically, https://github.com/flexflow/FlexFlow/blob/0d75c1042bf87e45684bcb3679cfc9f39a87e589/src/runtime/request_manager.cc#L314

This may be a background server issue, since the `serve_xxxx()` functions aren't called.

This is for running `spec_infer.cc` and `incr_decoding.cc` examples.

**Comment by jiazhihao** [comment]
What's the command line you used?

**Comment by goliaro** [comment]
@reyna-abhyankar, you need to add the flag `-ll:cpu 4`. We should update the docs. Let me know if you are still encountering the issue with the CPU flag.

**Comment by goliaro** [comment]
Feel free to reopen if the issue is not fixed, closing for now after our discussion on Slack
