### ISSUE TITLE
Request for FlexLLM Artifact

### ISSUE THREAD

**Issue by warpmatrix** [flexflow/FlexFlow#1331]
I recently came across your inspiring paper titled "FlexLLM: A System for Co-Serving Large Language Model Inference and Parameter-Efficient Finetuning". As it mentioned in the paper:

> All the code was integrated into FlexFlow, available at https://github.com/flexflow/FlexFlow/.

I was particularly intrigued by the innovative approach and results presented in your work. However, it seems there is no related description in default branch. Is there any way to access the related artifact? Thanks again for your marvelous work.

**Comment by jiazhihao** [comment]
Thanks for your interests! The code is currently under the `peft` branch. We are actively fixing a python related issue and will make the code available in the main branch soon.

**Comment by warpmatrix** [comment]
Oh, I get it. Thank you very much for your guidance! I will keep following for your terrific work👍
