### ISSUE TITLE
Reenable `utils` tests

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#1336]
Currently (as of #1229) many of the tests `utils` are disabled in the corresponding `CMakeLists.txt` `SRC_PATTERNS` because they fail. These should eventually get re-enabled.

**Comment by lockshaw** [comment]
@Marsella8 where are we on this? I assume this is fixed by #1464?

**Comment by Marsella8** [comment]
> @Marsella8 where are we on this? I assume this is fixed by #1464?

Yes utils tests have been re-enabled
