### ISSUE TITLE
Difference of peft branch

### ISSUE THREAD

**Issue by czq693497091** [flexflow/FlexFlow#1385]
Hi, I am really interested in the work of FlexLLM and I guess the artifact evaluation is realeted to the peft_* branch. I wonder the difference between the peft, peft-qkv and peft_optimizer. Especially  I am impressed by the design of token-level finetune. Which branch is recommended to study the FlexLLM? Thanks!

**Comment by goliaro** [comment]
@czq693497091 Thanks for your interest! The main branch for FlexLLM and peft-related functionalities is `peft`. The other branches will be merged into the `peft` branch in the next few weeks. An old version of token-level fine-tuning is available in [this branch](https://github.com/xinhaoc/FlexFlow/tree/peft_xinhao); we will upstream the newest version into the `peft` branch at a later time (likely a month or two).
