### ISSUE TITLE
Segfault with PyBind11 native python

### ISSUE THREAD

**Issue by eddy16112** [flexflow/FlexFlow#139]
Run python ../examples/python/native/mnist_cnn.py -ll:py 1 -ll:gpu 1 -ll:fsize 2048 -ll:zsize 12192
Then there is a segfault. 
Here is the stack trace:
#0  0x00002b51b360985d in nanosleep () from /lib64/libc.so.6
#1  0x00002b51b36096f4 in sleep () from /lib64/libc.so.6
#2  0x00002b51e0f45d26 in Realm::realm_freeze (signal=11) at /home/wwu/flexflow-cmake/deps/legion/runtime/realm/runtime_impl.cc:167
#3  <signal handler called>
#4  0x0000564a5124bf83 in cfunction_call_varargs (kwargs=<optimized out>, args=<optimized out>, func=0x2b51ba7894f0) at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:744
#5  PyCFunction_Call () at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:772
#6  0x0000564a5120985f in _PyObject_MakeTpCall () at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:159
#7  0x0000564a5128ce35 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x2b51b3265780, callable=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:125
#8  call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x564a532ce900) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4963
#9  _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3500
#10 0x0000564a51256a92 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4298
#11 0x0000564a51257754 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4327
#12 0x0000564a512e5edc in PyEval_EvalCode (co=co@entry=0x2b51b32c89d0, globals=globals@entry=0x2b51b3249080, locals=locals@entry=0x2b51b3249080) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:718
#13 0x0000564a5131b083 in builtin_exec_impl.isra.14 (locals=0x2b51b3249080, globals=0x2b51b3249080, source=0x2b51b32c89d0) at /tmp/build/80754af9/python_1599203911753/work/Python/bltinmodule.c:1033
#14 builtin_exec () at /tmp/build/80754af9/python_1599203911753/work/Python/clinic/bltinmodule.c.h:396
#15 0x0000564a5120c699 in cfunction_vectorcall_FASTCALL () at /tmp/build/80754af9/python_1599203911753/work/Objects/methodobject.c:422
#16 0x0000564a51209041 in PyVectorcall_Call () at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:199
#17 0x0000564a5124c056 in PyCFunction_Call () at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:774
#18 0x0000564a51291da0 in do_call_core (kwdict=0x2b51ba7bb440, callargs=0x2b51ba7bb600, func=0x2b51b319f590, tstate=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4983
#19 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3559
#20 0x0000564a51256a92 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4298
#21 0x0000564a51257943 in _PyFunction_Vectorcall.localalias.355 () at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:435
#22 0x0000564a511cc77f in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x2b51b327a550, callable=0x2b51b31b94c0) at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#23 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x564a532ce900) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4963
#24 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3469
#25 0x0000564a5125786b in function_code_fastcall (globals=<optimized out>, nargs=2, args=<optimized out>, co=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:283
#26 _PyFunction_Vectorcall.localalias.355 () at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:410
#27 0x0000564a511cc75e in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x2b51b32b21c0, callable=0x2b51b31e05e0) at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#28 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x564a532ce900) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4963
#29 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3486
#30 0x0000564a5125786b in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:283
#31 _PyFunction_Vectorcall.localalias.355 () at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:410
#32 0x0000564a511cab84 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x2b51b32b23f0, callable=0x2b51b31bb0d0) at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#33 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x564a532ce900) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4963
#34 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3500
#35 0x0000564a5125786b in function_code_fastcall (globals=<optimized out>, nargs=2, args=<optimized out>, co=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:283
#36 _PyFunction_Vectorcall.localalias.355 () at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:410
#37 0x0000564a511cab84 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x2b51b32b27d8, callable=0x2b51b31be310) at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#38 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x564a532ce900) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4963
#39 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:3500
#40 0x0000564a5125786b in function_code_fastcall (globals=<optimized out>, nargs=2, args=<optimized out>, co=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:283
#41 _PyFunction_Vectorcall.localalias.355 () at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:410
#42 0x0000564a5114a2d6 in _PyObject_Vectorcall (kwnames=0x0, nargsf=2, args=0x7fff7733ced0, callable=0x2b51b31be3a0) at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:127
#43 _PyObject_FastCall () at /tmp/build/80754af9/python_1599203911753/work/Include/cpython/abstract.h:147
#44 object_vacall (base=0x0, callable=0x2b51b31be3a0, vargs=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:1186
#45 0x0000564a51249c07 in _PyObject_CallMethodIdObjArgs () at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:1244
#46 0x0000564a511fbda6 in import_find_and_load (abs_name=0x2b51b3253ab0) at /tmp/build/80754af9/python_1599203911753/work/Python/import.c:1698
#47 PyImport_ImportModuleLevelObject () at /tmp/build/80754af9/python_1599203911753/work/Python/import.c:1798
#48 0x0000564a5128ff45 in import_name (level=0x564a5145cd20 <small_ints+160>, fromlist=0x2b51b323cf70, name=0x2b51b3253ab0, f=0x2b51b3218640, tstate=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:5139
#49 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:2993
#50 0x0000564a51256a92 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4298
#51 0x0000564a51257754 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:4327
#52 0x0000564a512e5edc in PyEval_EvalCode (co=co@entry=0x2b51b32c8450, globals=globals@entry=0x2b51b3201840, locals=locals@entry=0x2b51b3201840) at /tmp/build/80754af9/python_1599203911753/work/Python/ceval.c:718
#53 0x0000564a512e5f84 in run_eval_code_obj () at /tmp/build/80754af9/python_1599203911753/work/Python/pythonrun.c:1125
#54 0x0000564a513181f4 in run_mod () at /tmp/build/80754af9/python_1599203911753/work/Python/pythonrun.c:1147
#55 0x0000564a511e06e1 in PyRun_FileExFlags (fp=fp@entry=0x564a533df100, filename_str=filename_str@entry=0x2b51b32485f0 "../examples/python/native/mnist_cnn.py", start=start@entry=257, globals=globals@entry=0x2b51b3201840, locals=locals@entry=0x2b51b3201840, closeit=closeit@entry=1, flags=0x7fff7733d468)
    at /tmp/build/80754af9/python_1599203911753/work/Python/pythonrun.c:1063
#56 0x0000564a511e0ac6 in PyRun_SimpleFileExFlags (fp=fp@entry=0x564a533df100, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7fff7733d468) at /tmp/build/80754af9/python_1599203911753/work/Python/pythonrun.c:428
#57 0x0000564a511e112e in PyRun_AnyFileExFlags (fp=fp@entry=0x564a533df100, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7fff7733d468) at /tmp/build/80754af9/python_1599203911753/work/Python/pythonrun.c:86
#58 0x0000564a511e198b in pymain_run_file (cf=0x7fff7733d468, config=0x564a532cd820) at /tmp/build/80754af9/python_1599203911753/work/Modules/main.c:387
#59 pymain_run_python (exitcode=0x7fff7733d460) at /tmp/build/80754af9/python_1599203911753/work/Modules/main.c:612
#60 Py_RunMain () at /tmp/build/80754af9/python_1599203911753/work/Modules/main.c:691
#61 0x0000564a5131acd3 in pymain_main () at /tmp/build/80754af9/python_1599203911753/work/Modules/main.c:1113

**Comment by eddy16112** [comment]
my mistake, I should not add -ll:py 1

**Comment by msbaines** [comment]
I knew about this. I will add code to print an error when the user passes -ll:py
