### ISSUE TITLE
Optional CodeCoverage Building Instrumentation

### ISSUE THREAD

**Issue by Bob-Chen222** [flexflow/FlexFlow#1390]
Need to figure out a way to build the FlexFlow with code coverage instrumentation optionally.

**Comment by lockshaw** [comment]
I would recommend only building the with-instrumentation version when the user runs tests with coverage, as most of the time the user will not be examining the coverage information and we don't want to unnecessarily slow down most builds. Note that `proj test` already builds things that `proj build` does not (`proj build` does not build the test suites), so this isn't anything particularly new

**Comment by lockshaw** [comment]
Closed by #1396
