### ISSUE TITLE
Tanh and embedding_avx2 ops are outdated

### ISSUE THREAD

**Issue by eddy16112** [flexflow/FlexFlow#149]
Looks like the ops/tanh.cu and ops/embedding_avx2.cc are never added to the CMake/Makefile, and the declaration of Tanh is not in the model.h.

**Comment by jiazhihao** [comment]
These two are outdated. tanh.cu should be removed, and I will update embedding_avx2.cc to make it compatible with the new operator interface.

**Comment by eddy16112** [comment]
> These two are outdated. tanh.cu should be removed, and I will update embedding_avx2.cc to make it compatible with the new operator interface.

Thanks for letting me know. Do not worry, I can try to work on updating the embedding_avx2.

**Comment by eddy16112** [comment]
Fixed.
