### ISSUE TITLE
Tokenizer not optional

### ISSUE THREAD

**Issue by stelleg** [flexflow/FlexFlow#1515]
The CMake option `FF_BUILD_TOKENIZER` enables or disables the tokenizers-cpp subproject, but if disabled flexflow can't build, due to tokenizers being used in core flexflow. This also appears to imply that rust is no longer optional to build flexflow.  Not sure if there's a reasonable way to `#ifdef` out the tokenizer code for projects that don't need it, or if the conditional code in cmake should be made unconditional, but I think it's worth addressing.

**Comment by goliaro** [comment]
@stelleg I can push a fix. Which branch are you working on?

**Comment by stelleg** [comment]
@goliaro Great! Working on the inference branch
