### ISSUE TITLE
Strategy searching import error: Invalid color space color for child 1 of logical partition (508,304,606)

### ISSUE THREAD

**Issue by MiZhangWhuer** [flexflow/FlexFlow#157]
Great work! I tried to use the auto-tuning by searching the strategy as follows:

    python/flexflow_python examples/python/native/inception.py -ll:py 1 -ll:gpu 4 -ll:fsize 26000 -ll:zsize 55000 --epochs 10 -ll:streams 1 --search-budget 20000   --export-strategy ./strategy_folder/inception_strategy.pb --enable-parameter-parallel --enable-attribute-parallel

When the trained strategy is loaded:
    
     python/flexflow_python examples/python/native/inception.py -ll:py 1 -ll:gpu 4 -ll:fsize 26000 -ll:zsize 55000 --epochs 40 -ll:streams 1  --import-strategy ./strategy_folder/inception_strategy.pb

The error occurs:
        [error 39] LEGION ERROR: Invalid color space color for child 1 of logical partition (508,304,606) (from file /home/user/mycode/FlexFlow//deps/legion/runtime/legion/region_tree.cc:1589)

How can I fix the strategy error for flexible tuning? Could you please provide some guidance on it?

**Comment by jiazhihao** [comment]
Can you share with us the tuned strategy file `./strategy_folder/inception_strategy.pb`

**Comment by MiZhangWhuer** [comment]
> Can you share with us the tuned strategy file `./strategy_folder/inception_strategy.pb`

Thanks for the replay. Here is the strategy file :
[inception_strategy.zip](https://github.com/flexflow/FlexFlow/files/6228336/inception_strategy.zip)
