### ISSUE TITLE
Operator Unit tests documentation

### ISSUE THREAD

**Issue by Efrainq07** [flexflow/FlexFlow#161]
Hello, I noticed the documentation for running the operator unit tests [here](https://github.com/flexflow/FlexFlow/blob/master/tests/ops/test_readme.md) seems to be outdated and made for the DLRM repo. One of the issues is that the Makefile mentioned there is no longer on the main folder. 
Where has this file been moved to? Or what is the recommended way to run those tests? 
I can update that readme.md once this is clarified. Thanks

**Comment by lockshaw** [comment]
Discussion moved to #362
