### ISSUE TITLE
torch.split not recognized when running PyTorch CIFAR-10 examples

### ISSUE THREAD

**Issue by knagrecha** [flexflow/FlexFlow#187]
I'm trying to run the [cifar10_cnn_torch.py ](https://github.com/flexflow/FlexFlow/blob/master/examples/python/pytorch/cifar10_cnn_torch.py) code, but am running into an issue where the converter does not recognize the torch.split function used in the example. Here is the precise error:

    Traceback (most recent call last): File "FlexFlowTest.py", line 42, in <module>

    fx.torch_to_flexflow(model, "cnn.ff")

     File "/opt/conda/lib/python3.8/site-packages/flexflow/torch/fx.py", line 117, in torch_to_flexflow

    assert False, "Unrecogonized built-in function: {}".format(function_name)

    AssertionError: Unrecogonized built-in function: <function split at 0x7fdd63c1b820>

The corresponding forward function pulled straight from the example:
```
def forward(self, input1, input2):
        y1 = self.conv1(input1)
        y1 = self.relu(y1)
        y2 = self.conv1(input2)
        y2 = self.relu(y2)
        y = torch.cat((y1, y2), 1)
        (y1, y2) = torch.split(y, 1) 
        y = torch.cat((y1, y2), 1)
        y = self.conv2(y)
        y = self.relu(y)
        y = self.pool1(y)
        y = self.conv3(y)
        y = self.relu(y)
        y = self.conv4(y)
        y = self.relu(y)
        y = self.pool2(y)
        y = self.flat1(y)
        y = self.linear1(y)
        y = self.relu(y)
        yo = self.linear2(y)
        return (yo, y)

```

Not sure what could be causing this - I've used pip install from PyPI so all dependencies should be there. Is it perhaps because torch.split returns multiple values, or maybe because it works in a functional manner (rather than say, self.conv(x)).

Would appreciate any help with this.

**Comment by knagrecha** [comment]
@eddy16112 , could this be related to [your commit](https://github.com/flexflow/FlexFlow/commit/d33a775c86300de9efe17111091f5137c65ab019) for torch.split? Did you run into any similar errors when adding torch.split back in January?

**Comment by eddy16112** [comment]
I tried it, but did not have any issue. Are you in the master branch? Make sure you export FF_USE_CFFI=1, because the split is only implemented on cffi backend. 

By the way, here is the command I used 
./flexflow_python ../examples/python/pytorch/cifar10_cnn_torch.py  -ll:py 1 -ll:gpu 1 -ll:fsize 2048 -ll:zsize 12192

**Comment by knagrecha** [comment]
Oh, is ./flexflow_python used for both conversion AND running? Looking at ./test.sh in the python folder, I thought it was python <filename> for model generation and ./flexflow_python for application. That would explain the code structure with top_level function being used even for model generation. Thanks for the pointer.

**Comment by eddy16112** [comment]
Actually, you can do 
python3.6 ../examples/python/pytorch/cifar10_cnn_torch.py

But you will need to export FF_USE_CFFI=1.
