### ISSUE TITLE
Exporting GPU_ARCH=xx prior to installation does not seem to solve GPU ARCH errors for PyTorch frontend

### ISSUE THREAD

**Issue by knagrecha** [flexflow/FlexFlow#188]
Related issue: https://github.com/flexflow/FlexFlow/issues/154 advises export of GPU_ARCH environment variable when encountering Legion error on mismatched compilation. I attempted to use this fix to no avail. My system has 2 1080TI GPUs. When I run the config.linux file (having setup all of the config variables before hand), it confirms that my export (export GPU_ARCH=61) for the Pascal architecture worked. . See output:

```
 Defaults for Linux machine
cmake -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF -DCMAKE_BUILD_TYPE=Debug -DCUDA_PATH=/usr/local/cuda -DCUDNN_PATH=/usr/local/cuda -DFF_USE_PYTHON=ON -DFF_USE_NCCL=OFF -DFF_USE_GASNET=OFF -FF_BUILD_EXAMPLES=OFF -DFF_USE_AVX2=OFF -DFF_MAX_DIM=4 ../config/../
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- ZLIB libraries : /usr/lib/x86_64-linux-gnu/libz.so
-- Found CUDA: /usr/local/cuda (found version "11.0") 
-- No result from nvcc so building for 2.0
6.1
61
-- Automatic GPU ARCH detection: 61
-- CUDA Detected CUDA_ARCH : 61
-- CUDA root path : /usr/local/cuda
-- CUDA include path : /usr/local/cuda/include
-- CUDA runtime libraries : 
-- CUDA driver libraries : /usr/local/cuda/lib64/stubs/libcuda.so
-- CUBLAS libraries : /usr/local/cuda/lib64/libcublas.so
-- CURAND libraries : /usr/local/cuda/lib64/libcurand.so
-- CUDA Arch : 61
CUDA_GENCODE: -gencode arch=compute_61,code=sm_61
-- CUDNN inlcude : /usr/include
-- CUDNN libraries : /usr/lib/x86_64-linux-gnu/libcudnn.so
GASNET ROOT: 
-- Performing Test COMPILER_SUPPORTS_MARCH
-- Performing Test COMPILER_SUPPORTS_MARCH - Success
-- Performing Test COMPILER_SUPPORTS_MALTIVEC
-- Performing Test COMPILER_SUPPORTS_MALTIVEC - Failed
-- Performing Test COMPILER_SUPPORTS_MABI_ALTIVEC
-- Performing Test COMPILER_SUPPORTS_MABI_ALTIVEC - Failed
-- Performing Test COMPILER_SUPPORTS_MVSX
-- Performing Test COMPILER_SUPPORTS_MVSX - Failed
-- Performing Test COMPILER_SUPPORTS_DEFCHECK
-- Performing Test COMPILER_SUPPORTS_DEFCHECK - Failed
-- Found PythonInterp: /opt/conda/bin/python (found version "3.8.8") 
-- Found PythonLibs: /opt/conda/lib/libpython3.8.so (found version "3.8.8") 
CMake Warning (dev) at deps/legion/CMakeLists.txt:246 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
```

GPU_ARCH is set to 61, which is correct for a 1080TI with the Pascal architecture. However, when I use the ./flexflow_python executable after building, I get this error. 

```
ERROR: The binary was compiled for the wrong GPU architecture. Update the 'GPU_ARCH' flag at the top of runtime/runtime.mk to match/include your current GPU architecture (61).
```

Per the issue raised by @eddy16112 here: https://github.com/StanfordLegion/legion/issues/824#issue-603421046, I switched export from a number to "pascal" (export GPU_ARCH="pascal"), but still got the same error.

Do I need to change something in the Legion runtime.mk files? Not sure how to proceed, this error is blocking any use of the PyTorch frontend.

**Comment by lockshaw** [comment]
@knagrecha If you're using the cmake build system (which it appears you are) you can ignore the `runtime.mk` files (there is both a `make`-based build system and `cmake`-based system, and they are part of the former). Have you tried cleaning the project and re-building from scratch? CMake likes to cache values (`CMakeCache.txt`)

**Comment by eddy16112** [comment]
export GPU_ARCH=pascal is used for makefile system. Could you please try the makefile to see if works for you? It is 
https://github.com/flexflow/FlexFlow/blob/master/python/Makefile

**Comment by knagrecha** [comment]
@lockshaw I've tried cleaning and retrying it both with make clean and complete machine teardowns (using a Kubernetes cluster so it's not too much overhead to do this), but ran into the same issue regardless. I'll try using the make-based build system instead of the cmake one.
