### ISSUE TITLE
support for multi node clusters

### ISSUE THREAD

**Issue by DavidPeleg6** [flexflow/FlexFlow#190]
I am looking into a way to distribute my DNN over multiple nodes connected by highspeed ethernet (rather than nvlink) when I came across this framework.
Is the simulator of the distributed DNN able to take multi node clusters into account when calculating runtime for the MCMC optimization?

**Comment by lockshaw** [comment]
@DavidPeleg6 Yes, the simulator takes into account multi-node clusters (as long as the nodes are all uniform). You'll have to know the bandwidth of the various interconnects as FlexFlow does not automatically discover them

**Comment by DavidPeleg6** [comment]
I understand. Thanks!
