### ISSUE TITLE
The Unity Merge

### ISSUE THREAD

**Issue by jiazhihao** [flexflow/FlexFlow#192]
This issue tracks the list of todos for merging the `unify` branch to `master`
- [ ] Update the Python interface
- [ ] Add a `ParallelComputationGraph` layer for capturing the parallelization of operators
- [ ] Sequential graph splits

**Comment by lockshaw** [comment]
- [ ] Add machine views for dimension >1
- [ ] Load TASO-generated jint optimizations
- [ ] Investigate search bug on inception
- [ ] Update the rest of the operators
- [ ] Fix replica counting for weight synchronization estimates

**Comment by abhivijay96** [comment]
I am trying to execute inception with the script in osdi folder. Here is the command I am using:

"$FF_HOME"/build/examples/cpp/InceptionV3/inception -ll:gpu 2 -ll:fsize 11000 -ll:zsize 14000 -b 64 --budget 10

However, the execution results in a segmentation fault, I attached GDB to look at where this is happening and here is what it says:
0x00007ffff7c8954b in FlexFlow::ParallelTensorBase::get_shape() const () from /path/FlexFlow/build/libflexflow.so 

Can you please take a look at this?

**Comment by lockshaw** [comment]
> I am trying to execute inception with the script in the osdi folder. Here is the command I am using:
> 
> `"$FF_HOME"/build/examples/cpp/InceptionV3/inception -ll:gpu 2 -ll:fsize 11000 -ll:zsize 14000 -b 64 --budget 10`
> 
> However, the execution results in a segmentation fault, I attached GDB to look at where this is happening and here is what it says: `0x00007ffff7c8954b in FlexFlow::ParallelTensorBase::get_shape() const () from /path/FlexFlow/build/libflexflow.so `
> 
> Can you please take a look at this?

Moving to #1131.
