### ISSUE TITLE
How to save the trained weights?

### ISSUE THREAD

**Issue by MiZhangWhuer** [flexflow/FlexFlow#193]
I tried the provided demo and everything worked smoothly. However, there isn't any interface for saving the trained models. 
Could you please provide some examples on how to save the trained weights?

**Comment by jiazhihao** [comment]
The `get_weight_tensor` and `get_bias_tensor` method will help you get a tensor for the kernel or bias of a layer with trainable parameters: https://github.com/flexflow/FlexFlow/blob/master/examples/python/native/print_layers.py#L72-L74
