### ISSUE TITLE
does FlexFlow work for non-identical systems

### ISSUE THREAD

**Issue by DavidPeleg6** [flexflow/FlexFlow#195]
I just noticed that I have to define the GPU-ARCHITECTURE prior to building the framework.
Is there also support for multi node systems with non-identical hardware?

**Comment by jiazhihao** [comment]
If you want to run FlexFlow on non-identical hardware, you can simply build FlexFlow by including all needed GPU architecture versions (e.g., `FF_CUDA_ARCH=xx,yy`)

**Comment by DavidPeleg6** [comment]
I understand, thank you. 
Furthermore, is there an option for me to run flexflow on generic hardware? (like a TPU for example).

**Comment by Q-SudhirDeshmukh** [comment]
Hi, Just came across this great work. 

Would like to know if it would work on TPU as well ?

**Comment by lockshaw** [comment]
> Would like to know if it would work on TPU as well ?

No, the FlexFlow implementation currently only supports NVIDIA and AMD GPUs.
