### ISSUE TITLE
Export strategy flag not working

### ISSUE THREAD

**Issue by DavidPeleg6** [flexflow/FlexFlow#197]
I am currently running the following test script:
./flexflow_python $FF_HOME/examples/python/keras/func_mnist_cnn.py -ll:py 1 -ll:gpu 4 -ll:fsize 2048 -ll:zsize 12192 --export /usr/FlexFlow/strategy.txt

and while the script runs well, the export flag is not generated. Is performing a MCMC search step mandatory for the creation of a strategy?

**Comment by jiazhihao** [comment]
Yes, you need to set a non-zero budget for the MCMC search `--budget xxx`. Otherwise, the search procedure will be skipped and won't produce a strategy file.

**Comment by DavidPeleg6** [comment]
and is there no way to avoid this feature? 
I am looking to make some manual changes to the strategy, so I would like to have some runs with only the simulator running an imported strategy rather than optimizing.

**Comment by jiazhihao** [comment]
To do what you want, you can change the following line https://github.com/flexflow/FlexFlow/blob/master/src/runtime/model.cc#L1578 from `budget > 0` to `budget >= 0`. This will allow FlexFlow to search the MCMC search even when the budget is zero. In this case, the simulator will report the simulated run time of the imported strategy.

**Comment by DavidPeleg6** [comment]
thank you!
