### ISSUE TITLE
strategy file explanation

### ISSUE THREAD

**Issue by DavidPeleg6** [flexflow/FlexFlow#202]
I would like to use the strategy generated by flexflow and recreate the network according to the exported strategy.
Is there a source that explains the structure of the strategy file?

**Comment by eddy16112** [comment]
The code of exporting strategy is https://github.com/eddy16112/FlexFlow/blob/master/src/runtime/strategy.cc#L150

Here is an example:
`./flexflow_python ../examples/python/native/mnist_cnn.py -ll:py 1 -ll:gpu 2 -ll:fsize 4096 -ll:zsize 12192 --epochs 1 --search-budget 10000 --export-strategy strategy.txt`
You will see the best strategy found
```
=========== Best Discovered Strategy ==========
[Conv2D_100] num_dims(4) dims[1,1,1,2] device_ids[0,1]
[Conv2D_101] num_dims(4) dims[1,1,1,2] device_ids[0,1]
[Pool2D_102] num_dims(4) dims[1,1,1,2] device_ids[0,1]
[Flat_103] num_dims(2) dims[1,2] device_ids[0,1]
[Dense_104] num_dims(2) dims[1,1] device_ids[1]
[Dense_105] num_dims(2) dims[1,2] device_ids[0,1]
[Softmax_106] num_dims(2) dims[1,2] device_ids[0,1]
```
The strategy.txt is the output of strategy found. The format is:
```
number of operators
Operator 1
Operator 2
...
```
For each operator, the format is:
```
Conv2D_100                    -> name of the operator
0                             -> the device that the operator can be executed on, 0 means GPU, 1 means CPU 
4                             -> number of parallelizable dimensions
1       1       1       2     -> how each parallelizable dimension is parallelized, 1 means no parallelization, n means this dimension is divided into n pieces for parallelization
2                             -> number of devices the operator is executed on
0       1                     -> device id the operator is executed on
```

**Comment by roman955b** [comment]
Line 4 ("how each parallelizable dimension is parallelized")
What does each of the 4 dimensions represent?

**Comment by eddy16112** [comment]
> Line 4 ("how each parallelizable dimension is parallelized")
> What does each of the 4 dimensions represent?

It represents the dimensions of the input tensor of the operator, for example, the 4 dims of Conv2D is width, height, depth, batch size.

**Comment by DavidPeleg6** [comment]
thanks!

**Comment by DavidPeleg6** [comment]
> > Line 4 ("how each parallelizable dimension is parallelized")
> > What does each of the 4 dimensions represent?
> 
> It represents the dimensions of the input tensor of the operator, for example, the 4 dims of Conv2D is width, height, depth, batch size.

is there a documentation list regarding what the parallelizable dimensions of each operator are?
also, for the case of convolution I understand batch stands for the Sample dimension while depth stands for Attribute, but do both width and height stand for Parameter dimension?
