### ISSUE TITLE
'FFModel' object has no attribute 'concat' 

### ISSUE THREAD

**Issue by roman955b** [flexflow/FlexFlow#204]
All the below tests (from python/test.sh) failed due to the error: `AttributeError: 'FFModel' object has no attribute 'concat'`
FlexFlow commit (master, sha: commit f0913c24cd056a09797a3261d9f4c750cd062208 )
Legion submodule (sha: commit 2561e7ab768c818f5f09513b4aa36b13d0507a70) (default of FlexFlow master)
nccl submodule (sha: commit 399656269027c1818fc999ccf8ec4dd838cec50d) (default of FlexFlow master)

  `./flexflow_python $FF_HOME/examples/python/keras/func_mnist_mlp_concat.py`
  `./flexflow_python $FF_HOME/examples/python/keras/func_mnist_mlp_concat2.py`
  `./flexflow_python $FF_HOME/examples/python/native/print_layers.py`
  `./flexflow_python $FF_HOME/examples/python/native/split.py`
  `./flexflow_python $FF_HOME/examples/python/keras/func_cifar10_cnn_concat.py`
  `./flexflow_python $FF_HOME/examples/python/keras/func_cifar10_cnn_concat_model.py`
  `./flexflow_python $FF_HOME/examples/python/keras/func_cifar10_cnn_concat_seq_model.py`
  `./flexflow_python $FF_HOME/examples/python/native/cifar10_cnn_concat.py`

Full log trace of one of the tests:
```
Failed:
./flexflow_python $FF_HOME/examples/python/keras/func_mnist_mlp_concat.py -ll:py 1 -ll:gpu $GPUS -ll:fsize 2048 -ll:zsize 12192

++ ./flexflow_python /usr/FlexFlow/examples/python/keras/func_mnist_mlp_concat.py -ll:py 1 -ll:gpu 1 -ll:fsize 4096 -ll:zsize 12192
[0 - 7fea41c91700]    0.239597 {3}{Mapper}: No strategy file provided. Use default data parallelism.
[0 - 7fea41c91700]    0.239717 {3}{Mapper}: No strategy file provided. Use default data parallelism.
[0 - 7fea41c91700]    0.239769 {3}{Mapper}: No strategy file provided. Use default data parallelism.
Using pybind11 flexflow bindings.
top-level task
Using flexflow backend.
Functional API, mnist mlp concat
shape:  (60000, 784)
Python API batchSize(64) workersPerNodes(1) numNodes(1)
Python API batchSize(64) workersPerNodes(1) numNodes(1)
Python API batchSize(64) workersPerNodes(1) numNodes(1)
Python API batchSize(64) workersPerNodes(1) numNodes(1)
Python API batchSize(64) workersPerNodes(1) numNodes(1)
workSpaceSize (1024 MB)
ndim(2) dims[1 1 -43437328 32745]
[0 - 7fea190d5700]    2.347655 {6}{python}: python exception occurred within task:
Traceback (most recent call last):
  File "/usr/FlexFlow/python/flexflow/core/flexflow_top.py", line 196, in flexflow_top_level_task
    run_path(args[start], run_name='__main__')
  File "/usr/FlexFlow/python/flexflow/core/flexflow_top.py", line 146, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "/usr/FlexFlow/examples/python/keras/func_mnist_mlp_concat.py", line 81, in <module>
    top_level_task()
  File "/usr/FlexFlow/examples/python/keras/func_mnist_mlp_concat.py", line 73, in top_level_task
    model.compile(optimizer=opt, loss='sparse_categorical_crossentropy', metrics=['accuracy', 'sparse_categorical_crossentropy'])
  File "/usr/FlexFlow/python/flexflow/keras/models/base_model.py", line 179, in compile
    self._create_flexflow_layers()
  File "/usr/FlexFlow/python/flexflow/keras/models/base_model.py", line 451, in _create_flexflow_layers
    out_t = self._ffmodel.concat(t_ffhandle_list, layer.axis)
AttributeError: 'FFModel' object has no attribute 'concat'
flexflow_python: /usr/FlexFlow/deps/legion/runtime/realm/python/python_module.cc:978: virtual void Realm::LocalPythonProcessor::execute_task(Realm::Processor::TaskFuncID, const Realm::ByteArrayRef&): Assertion `0' failed.


```

**Comment by eddy16112** [comment]
right now, the concat is not implemented on pybind backend, please export FF_USE_CFFI=1,

**Comment by MiZhangWhuer** [comment]
> All the below tests (from python/test.sh) failed due to the error: `AttributeError: 'FFModel' object has no attribute 'concat'`
> FlexFlow commit (master, sha: commit [f0913c2](https://github.com/flexflow/FlexFlow/commit/f0913c24cd056a09797a3261d9f4c750cd062208) )
> Legion submodule (sha: commit 2561e7ab768c818f5f09513b4aa36b13d0507a70) (default of FlexFlow master)
> nccl submodule (sha: commit 399656269027c1818fc999ccf8ec4dd838cec50d) (default of FlexFlow master)
> 
> `./flexflow_python $FF_HOME/examples/python/keras/func_mnist_mlp_concat.py`
> `./flexflow_python $FF_HOME/examples/python/keras/func_mnist_mlp_concat2.py`
> `./flexflow_python $FF_HOME/examples/python/native/print_layers.py`
> `./flexflow_python $FF_HOME/examples/python/native/split.py`
> `./flexflow_python $FF_HOME/examples/python/keras/func_cifar10_cnn_concat.py`
> `./flexflow_python $FF_HOME/examples/python/keras/func_cifar10_cnn_concat_model.py`
> `./flexflow_python $FF_HOME/examples/python/keras/func_cifar10_cnn_concat_seq_model.py`
> `./flexflow_python $FF_HOME/examples/python/native/cifar10_cnn_concat.py`
> 
> Full log trace of one of the tests:
> 
> ```
> Failed:
> ./flexflow_python $FF_HOME/examples/python/keras/func_mnist_mlp_concat.py -ll:py 1 -ll:gpu $GPUS -ll:fsize 2048 -ll:zsize 12192
> 
> ++ ./flexflow_python /usr/FlexFlow/examples/python/keras/func_mnist_mlp_concat.py -ll:py 1 -ll:gpu 1 -ll:fsize 4096 -ll:zsize 12192
> [0 - 7fea41c91700]    0.239597 {3}{Mapper}: No strategy file provided. Use default data parallelism.
> [0 - 7fea41c91700]    0.239717 {3}{Mapper}: No strategy file provided. Use default data parallelism.
> [0 - 7fea41c91700]    0.239769 {3}{Mapper}: No strategy file provided. Use default data parallelism.
> Using pybind11 flexflow bindings.
> top-level task
> Using flexflow backend.
> Functional API, mnist mlp concat
> shape:  (60000, 784)
> Python API batchSize(64) workersPerNodes(1) numNodes(1)
> Python API batchSize(64) workersPerNodes(1) numNodes(1)
> Python API batchSize(64) workersPerNodes(1) numNodes(1)
> Python API batchSize(64) workersPerNodes(1) numNodes(1)
> Python API batchSize(64) workersPerNodes(1) numNodes(1)
> workSpaceSize (1024 MB)
> ndim(2) dims[1 1 -43437328 32745]
> [0 - 7fea190d5700]    2.347655 {6}{python}: python exception occurred within task:
> Traceback (most recent call last):
>   File "/usr/FlexFlow/python/flexflow/core/flexflow_top.py", line 196, in flexflow_top_level_task
>     run_path(args[start], run_name='__main__')
>   File "/usr/FlexFlow/python/flexflow/core/flexflow_top.py", line 146, in run_path
>     exec(code, module.__dict__, module.__dict__)
>   File "/usr/FlexFlow/examples/python/keras/func_mnist_mlp_concat.py", line 81, in <module>
>     top_level_task()
>   File "/usr/FlexFlow/examples/python/keras/func_mnist_mlp_concat.py", line 73, in top_level_task
>     model.compile(optimizer=opt, loss='sparse_categorical_crossentropy', metrics=['accuracy', 'sparse_categorical_crossentropy'])
>   File "/usr/FlexFlow/python/flexflow/keras/models/base_model.py", line 179, in compile
>     self._create_flexflow_layers()
>   File "/usr/FlexFlow/python/flexflow/keras/models/base_model.py", line 451, in _create_flexflow_layers
>     out_t = self._ffmodel.concat(t_ffhandle_list, layer.axis)
> AttributeError: 'FFModel' object has no attribute 'concat'
> flexflow_python: /usr/FlexFlow/deps/legion/runtime/realm/python/python_module.cc:978: virtual void Realm::LocalPythonProcessor::execute_task(Realm::Processor::TaskFuncID, const Realm::ByteArrayRef&): Assertion `0' failed.
> ```

Hi, implementing the concat is straightforward. You should modify the  concat.cu interface as follows:

Concat::Concat(FFModel& model,
               // int _n, 
			   const std::vector<Tensor> &_tensors,
               int _axis,
               const char* name) 

and then adding the interface to python binding:
   .def("concat", &FFModel::concat, "tensors"_a, "axis"_a, "name"_a=nullptr)

**Comment by eddy16112** [comment]
please export FF_USE_CFFI=1

**Comment by MiZhangWhuer** [comment]
> please export FF_USE_CFFI=1

It is not necessary to export this symbol because it relays on Legion symbol and the user must set extra command line parameters. I've modified the entire source code and will release it the next few month. Hope it can benefit the whole community.
