### ISSUE TITLE
split operator not implemented (pytorch)

### ISSUE THREAD

**Issue by DavidPeleg6** [flexflow/FlexFlow#207]
I am running the following test script:
./flexflow_python $FF_HOME/examples/python/pytorch/cifar10_cnn.py -ll:py 1 -ll:gpu 4  -ll:fsize 8192 -ll:zsize 12192 -ll:cpu 28 --export strategy.txt --budget 1000

and I get the following error:
measure_operator_cost not implemented for op split_105 (type 22). Please report this issue to the FlexFlow developers.
Aborted (core dumped)

If the split operator is not yet supported in the simulator, is there a workaround I can use?

**Comment by eddy16112** [comment]
Please switch to python cffi backend by export FF_USE_CFFI=1

**Comment by DavidPeleg6** [comment]
I have tried it and I am getting the same error

**Comment by eddy16112** [comment]
I am sorry it is because the split operator is not supported in the simulator, right now, the only way is not to use split if you want to use the simulator.

**Comment by DavidPeleg6** [comment]
I understand.
Is the split operator supported in the actual flexflow runtime? For example, in case I would like to run a script with my own strategy.

**Comment by jiazhihao** [comment]
It is supported in the runtime. I will push a fix to support split in the simulator.

**Comment by DavidPeleg6** [comment]
thank you!

**Comment by jiazhihao** [comment]
The support for split in the simulator is available in commit d5461fa11daf0bb240b9874f658f9172b9fec61d
