### ISSUE TITLE
Location of FlexFlow graph container in code

### ISSUE THREAD

**Issue by DavidPeleg6** [flexflow/FlexFlow#209]
I am trying to print the distribution of the NN over my hardware (the actual split of each individual layer across the SOAP space according to the strategy file).
I tried using FFModel's print_layers method but I seem to get the entire saved layer rather than its representation.
Is there an inner FlexFlow structure that includes the entire split model? 
Or is there a specific stage during the execution of each layer in which the layer is split across the hardware? If so, what is it?

**Comment by jiazhihao** [comment]
You are right that `print_layers` will print an entire layer regardless of its partitioning. If you want to see the partitioned weights on individual devices, `print_tensor` might be what you need. It directly prints the partitioned weights assigned to each device. E.g., https://github.com/flexflow/FlexFlow/blob/master/src/ops/embedding.cu#L269.

**Comment by DavidPeleg6** [comment]
thanks.
Is there a way to print it straight from the examples/python/native/print_layers.py script?
