### ISSUE TITLE
Legion runtime does not accept manual splits

### ISSUE THREAD

**Issue by DavidPeleg6** [flexflow/FlexFlow#212]
I would like to check different splits by manually changing the strategy. In order to do so, I tried as a first step to change the split in the sample dimension from 4 gpus to 2 gpus. flexflow simulator runs this split with no issues, but the test fails at runtime with the following error:
{5}{runtime}: [error 39] LEGION ERROR: Invalid color space color for child 2 of logical partition (13,10,18) (from file /usr/FlexFlow/deps/legion/runtime/legion/region_tree.cc:1595)
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_39

The step to generate this issue are:
1) ./flexflow_python $FF_HOME/examples/python/keras/func_cifar10_cnn.py -ll:py 1 -ll:gpu 4 -ll:fsize 8192 -ll:zsize 12192 -ll:cpu 28 --export strategy.txt --budget 10000
which yields the following strategy file [strategy before.txt](https://github.com/flexflow/FlexFlow/files/6682184/strategy.before.txt)

2) change the third convolution layer (Conv_2D_103) in the strategy file to split the batch to 2 gpus instead, which yields the following strategy file [strategy after.txt](https://github.com/flexflow/FlexFlow/files/6682185/strategy.after.txt)

3) ./flexflow_python $FF_HOME/examples/python/keras/func_cifar10_cnn.py -ll:py 1 -ll:gpu 4 -ll:fsize 8192 -ll:zsize 12192 -ll:cpu 28 --import strategy.txt --budget 1 --export strategy.txt
and note that the strategy has not changed

4) ./flexflow_python $FF_HOME/examples/python/keras/func_cifar10_cnn.py -ll:py 1 -ll:gpu 4 -ll:fsize 8192 -ll:zsize 12192 -ll:cpu 28 --import strategy.txt

**Comment by merrymercy** [comment]
I got a similar error in #215

**Comment by DavidPeleg6** [comment]
Furthermore, when running ResNet with MCMC budget of 10,000 
` ./transformer  -ll:gpu 4 -ll:fsize 11000 -ll:zsize 10000 --enable-parameter-parallel  --enable-attribute-parallel --export strategy.txt --budget 10000
`
 I get the following strategy file:
[strategy.txt](https://github.com/flexflow/FlexFlow/files/6721817/strategy.txt)

when I rerun the test with the imported strategy file I get the same error:

[0 - 7f096baf9700]    6.850577 {5}{runtime}: [error 39] LEGION ERROR: Invalid color space color for child 1 of logical partition (281,176,350) (from file /usr/FlexFlow/deps/legion/runtime/legion/region_tree.cc:1595)
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_39

init linear (input): in_dim(8192) out_dim(5) batch_size(32)

**Comment by MiZhangWhuer** [comment]
@DavidPeleg6 I got similar error too and do not find the solution yet.

**Comment by jiazhihao** [comment]
@DavidPeleg6 The issue should have been fixed by commit 217f3199f

**Comment by MiZhangWhuer** [comment]
> @DavidPeleg6 The issue should have been fixed by commit [217f319](https://github.com/flexflow/FlexFlow/commit/217f3199f6839bfd255f2ba1d51ca424e1945337)

Zhihao, how do you debug this error? Is there any convenient way to locate the error associate with launcher.add_region_requirement(
      RegionRequirement)?

**Comment by jiazhihao** [comment]
The error message is not very informative unfortunately. The issue was that switching between parallelization strategies requires partitioning some tensors in multiple ways, each of which is called a `LogicalPartition`, and FlexFlow used an incorrect partitioning for conv2d. This resulted in an assertion error in Legion.

The easiest way to debug Legion issues is generating a backtrace using `gdb` and `LEGION_FREEZE_OR_ERROR=1`: https://legion.stanford.edu/debugging/.

**Comment by MiZhangWhuer** [comment]
> The error message is not very informative unfortunately. The issue was that switching between parallelization strategies requires partitioning some tensors in multiple ways, each of which is called a `LogicalPartition`, and FlexFlow used an incorrect partitioning for conv2d. This resulted in an assertion error in Legion.
> 
> The easiest way to debug Legion issues is generating a backtrace using `gdb` and `LEGION_FREEZE_OR_ERROR=1`: https://legion.stanford.edu/debugging/.

Thanks for providing the guidance. It is quite surprise that importing the same strategy file in C++ interface works fine but the error occurs in Python interface. What's the probable reason?

**Comment by DavidPeleg6** [comment]
Thanks!
