### ISSUE TITLE
How to run FlexFlow on multiple nodes?

### ISSUE THREAD

**Issue by merrymercy** [flexflow/FlexFlow#213]
I cannot find any examples of running FlexFlow on multiple nodes.

Could you provide any guidance or instructions on how to do this?

@jiazhihao @eddy16112

**Comment by merrymercy** [comment]
Find a related post here.
https://github.com/flexflow/FlexFlow/issues/35

**Comment by jiazhihao** [comment]
@merrymercy You can run FlexFlow on multiple nodes by building the source code with GASNET enabled (by setting `FF_USE_GASNET=ON` at https://github.com/flexflow/FlexFlow/blob/master/config/config.linux#L37). You can then use `srun` or `mpirun` for launching distributed runs of FlexFlow.
