### ISSUE TITLE
Failed to auto-tune a MLP model: [error 39] LEGION ERROR: Invalid color space color

### ISSUE THREAD

**Issue by merrymercy** [flexflow/FlexFlow#215]
I tried to auto-tune a 3-layer MLP model but got "LEGION ERROR: Invalid color space color" when loading the tuned strategy.

### Testing Environment
AWS p3.8xlarge, Deep Learning AMI (Ubuntu 18.04) Version 43.0, 4 x V100 GPUs.
FlexFlow : 798ce79e9837f (master branch, Jun 16, 2021)

###  Model definition
The file is put in `$FF_HOME/examples/python/native/mlp.py`
```python
import argparse
import time

import numpy as np

from flexflow.core import *

def top_level_task():
    ffconfig = FFConfig()
    print("Python API batchSize(%d) workersPerNodes(%d) numNodes(%d)" % (
        ffconfig.batch_size, ffconfig.workers_per_node, ffconfig.num_nodes))
    ffmodel = FFModel(ffconfig)

    batch_size = ffconfig.batch_size
    hidden_dim = 2304

    input_tensor = ffmodel.create_tensor([batch_size, hidden_dim], DataType.DT_FLOAT)
    t = input_tensor

    t = ffmodel.dense(t, hidden_dim)
    t = ffmodel.dense(t, hidden_dim)
    t = ffmodel.dense(t, 10)

    optimizer = SGDOptimizer(ffmodel, 0.001)
    ffmodel.optimizer = optimizer
    ffmodel.compile(loss_type=LossType.LOSS_SPARSE_CATEGORICAL_CROSSENTROPY,
                    metrics=[MetricsType.METRICS_ACCURACY,
                             MetricsType.METRICS_SPARSE_CATEGORICAL_CROSSENTROPY])

    label_tensor = ffmodel.label_tensor
    num_samples = batch_size * 12
    x_train = np.random.randn(num_samples, hidden_dim).astype("float32")
    y_train = np.random.randn(num_samples, 10).astype("int32")
    dataloader_input = ffmodel.create_data_loader(input_tensor, x_train)
    dataloader_label = ffmodel.create_data_loader(label_tensor, y_train)

    ffmodel.init_layers()
    ffmodel.fit(x=dataloader_input, y=dataloader_label, epochs=1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    args, unknown = parser.parse_known_args()
    top_level_task()
```
I can run the model successfully with the default data parallel strategy.

###  Auto-tuning
Run search.
```
ubuntu@ip-172-31-5-165:~/efs/FlexFlow/python$ ./flexflow_python $FF_HOME/examples/python/native/mlp.py -ll:py 1 -ll:gpu 4 -ll:fsize 14000 -ll:zsize 8192 --batch-size 1024 --export mlp_stra.txt --search-budget 100000  --enable-parameter-parallel -enable-attribute-parallel --search-alpha 0.05
...
=========== Best Discovered Strategy ==========
[Dense_100] num_dims(2) dims[4,1] device_ids[0,1,2,3]
[Dense_101] num_dims(2) dims[4,1] device_ids[0,1,2,3]
[Dense_102] num_dims(2) dims[1,4] device_ids[0,1,2,3]
============= MCMC Search Finished ============
...
```

Load the strategy
```
ubuntu@ip-172-31-5-165:~/efs/FlexFlow/python$ ./flexflow_python $FF_HOME/examples/python/native/mlp.py -ll:py 1 -ll:gpu 4 -ll:fsize 14000 -ll:zsize 8192 --batch-size 1024 --enable-parameter-parallel -enable-attribute-parallel --import mlp_stra.txt
...
seed = 1681692777 scale = 0.0509
ndim(3) dims[1 1 4 32655]
ndim(4) dims[1 1 1 4]
Check ptr input_head_ 0x7f7d243fb010, input_ 0x7f7d243fb010 140175455793168 28311552, input 0x7f7f371eb860 140184362334304 28311552
-0.91684 -1.2121 -0.771326 -0.0530045 -0.477053 1.44452 0.409929 0.0835165 1.38563 0.617744 0.356743 -0.634055 -0.184139 0.363768 -0.19827 -2.49121 0.711975 0.586437 -0.958185 -0.0129322 0.144634 0.184534 0.698922 1.33135 -0.0452553 0.0760331 -0.311934 1.19092 0.528086 0.532449 -0.436187 -0.528343
Check ptr input_head_ 0x7f7f10977820, input_ 0x7f7f10977820 140183715936288 12288, input 0x7f7f3ddeb860 140184475580512 12288
0 0 -1 0 0 0 1 0 0 0 -1 -1 1 2 0 0 0 1 0 0 0 -1 -1 0 0 0 0 0 -1 -1 0 -1
init linear (input): in_dim(2304) out_dim(576) batch_size(1024)
[0 - 7f8fe621f700]    6.640753 {5}{runtime}: [error 39] LEGION ERROR: Invalid color space color for child 1 of logical partition (1,2,2) (from file /home/ubuntu/efs/FlexFlow/deps/legion/runtime/legion/region_tree.cc:1595)
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_39
```

If I modifiy the strategy file `mlp_stra.txt` to use data parallel for all dense layers, the command can run successfully.
But it crashes for any strategy that partitions the parameter dimension.

@jiazhihao

**Comment by jiazhihao** [comment]
The issue should have been fixed by commit 345ba896.

**Comment by merrymercy** [comment]
Thanks, it now works correctly.

But I can see warnings like
```
[0 - 7ff844e50700]    7.038498 {4}{runtime}: [warning 1097] LEGION WARNING: WARNING: The runtime has failed to memoize the trace more than 5 times, due to the absence of a replayable template. It is
highly likely that trace 201 will not be memoized for the rest of execution. The most recent template was not replayable for the following reason: precondition not subsumed by postcondition. Please change the mapper to stop making memoization requests. (from file /home/ubuntu/efs/FlexFlow/deps/legion/runtime/legion/legion_trace.cc:2025)
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1097
```

Do these warnings impact the performance?

**Comment by DavidPeleg6** [comment]
@jiazhihao I am running into the same problem with a manually generated strategy.
I am running the `examples/python/native/alexnet.py` test in the master branch (commit af8f6c6) with two strategies:
1. Generated by running the MCMC algorithm which yields the [MCMCstrategy.txt](https://github.com/flexflow/FlexFlow/files/6878715/MCMCstrategy.txt)
2. Generated manually [ManualStrategy.txt](https://github.com/flexflow/FlexFlow/files/6878729/ManualStrategy.txt)

Both strategies are simulated correctly in FlexFlow. However, only the MCMC generated strategy runs on the physical hardware while the manually generated strategy yields the following error (full output [full_output.txt](https://github.com/flexflow/FlexFlow/files/6878775/full_output.txt) ):
```
[0 - 7efe403e6700]   17.101481 {5}{runtime}: [error 39] LEGION ERROR: Invalid color space color for child 1 of logical partition (9,7,11) (from file /usr/FlexFlow/deps/legion/runtime/legion/region_tree.cc:1595)
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_39
```
I am unable to find any reason for the different performance as my manual strategy does not have any splits in the parameter dimension.

**Comment by DavidPeleg6** [comment]
@jiazhihao @eddy16112 any ideas on what I could check?

**Comment by JimWang1991** [comment]
> Thanks for the quick fix. It now works correctly.
> 
> But I can see warnings like
> 
> ```
> [0 - 7ff844e50700]    7.038498 {4}{runtime}: [warning 1097] LEGION WARNING: WARNING: The runtime has failed to memoize the trace more than 5 times, due to the absence of a replayable template. It is
> highly likely that trace 201 will not be memoized for the rest of execution. The most recent template was not replayable for the following reason: precondition not subsumed by postcondition. Please change the mapper to stop making memoization requests. (from file /home/ubuntu/efs/FlexFlow/deps/legion/runtime/legion/legion_trace.cc:2025)
> For more information see:
> http://legion.stanford.edu/messages/warning_code.html#warning_code_1097
> ```
> 
> Do these warnings affect the performance?

@merrymercy hello, have you sovle this warning? Do these warnings affect the performance? I encounter the same appearance and the train speed seems slower than the default data parallel.

**Comment by roman955b** [comment]
@JimWang1991  Any new insights on this warning and performance penalty?
