### ISSUE TITLE
file deppart_tmpl.cc.in does not exist

### ISSUE THREAD

**Issue by FourWinds021** [flexflow/FlexFlow#216]
**when i want to build flexflow use cmake config command: ../config/config.linux, and comes a error as flow, is there some one have the idea to solve this problem?**

Defaults for Linux machine
cmake -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF -DCMAKE_BUILD_TYPE=Release -DCUDNN_PATH=/usr/local/cuda -DFF_USE_PYTHON=ON -DFF_USE_NCCL=ON -DFF_USE_GASNET=ON -DFF_BUILD_EXAMPLES=OFF -DFF_USE_AVX2=OFF -DFF_MAX_DIM=4 ../config/../
-- ZLIB libraries : /usr/lib/x86_64-linux-gnu/libz.so
7.5
75
-- Automatic GPU ARCH detection: 75
-- CUDA Detected CUDA_ARCH : 75
-- CUDA root path : /usr/local/cuda
-- CUDA include path : /usr/local/cuda/include
-- CUDA runtime libraries : 
-- CUDA driver libraries : /usr/local/cuda/lib64/stubs/libcuda.so
-- CUBLAS libraries : /usr/local/cuda/lib64/libcublas.so
-- CURAND libraries : /usr/local/cuda/lib64/libcurand.so
-- CUDA Arch : 75
CUDA_GENCODE: -gencode arch=compute_75,code=sm_75
-- CUDNN inlcude : /usr/include
-- CUDNN libraries : /usr/lib/x86_64-linux-gnu/libcudnn.so
NCCL install dir: /userhome/wangjin/AutoParallel/FlexFlow-master/build/deps/nccl
GASNET ROOT: 
CMake Warning (dev) at /opt/conda/share/cmake-3.18/Modules/FindCUDA.cmake:875 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'CUDA_USE_STATIC_CUDA_RUNTIME'.
Call Stack (most recent call first):
  deps/legion/cmake/FindCUDA.cmake:22 (include)
  deps/legion/CMakeLists.txt:307 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error: File /userhome/wangjin/AutoParallel/FlexFlow-master/cmake/deppart_tmpl.cc.in does not exist.
CMake Error at deps/legion/runtime/CMakeLists.txt:223 (configure_file):
  configure_file Problem configuring file
CMake Error: File /userhome/wangjin/AutoParallel/FlexFlow-master/cmake/deppart_tmpl.cc.in does not exist.
CMake Error at deps/legion/runtime/CMakeLists.txt:707 (configure_file):
  configure_file Problem configuring file
CMake Error: File /userhome/wangjin/AutoParallel/FlexFlow-master/cmake/deppart_tmpl.cc.in does not exist.
CMake Error at deps/legion/runtime/CMakeLists.txt:707 (configure_file):
  configure_file Problem configuring file
CMake Error: File /userhome/wangjin/AutoParallel/FlexFlow-master/cmake/deppart_tmpl.cc.in does not exist.
CMake Error at deps/legion/runtime/CMakeLists.txt:707 (configure_file):
  configure_file Problem configuring file
-- pybind11 v2.6.2 
-- Configuring incomplete, errors occurred!
See also "/userhome/wangjin/AutoParallel/FlexFlow-master/build/CMakeFiles/CMakeOutput.log".
See also "/userhome/wangjin/AutoParallel/FlexFlow-master/build/CMakeFiles/CMakeError.log".

**Comment by JimWang1991** [comment]
when I change the file path of deppart_tmpl.cc.in in deps/legion/runtime/CMakeLists.txt to 

> configure_file(${CMAKE_SOURCE_DIR}/deps/legion/cmake/deppart_tmpl.cc.in ${SRCFILE}_${INST_N1}_${INST_N2}.cc)

it seems worked now.

**Comment by jiazhihao** [comment]
The issue is related to using Legion as a submodule and should have been fixed. Are you using the most up-to-date version of FlexFlow and its submodules?

**Comment by JimWang1991** [comment]
> The issue is related to using Legion as a submodule and should have been fixed. Are you using the most up-to-date version of FlexFlow and its submodules?

the link of Legion in the FlexFlow-master (FlexFlow/deps/legion) is invalid, so I download this version of Legion from https://gitlab.com/StanfordLegion/legion/-/tree/master 
and change the line 223 in legion/runtime/CMakeLists.txt to :
> configure_file(${CMAKE_SOURCE_DIR}/deps/legion/cmake/deppart_tmpl.cc.in ${SRCFILE}${INST_N1}${INST_N2}.cc)

**Comment by jiazhihao** [comment]
The master branch of FlexFlow depends on legion@1c30cf19681988e2fbd9fedb3bbe7a97a272d911, which should be the most recent commit of the `flexflow` branch of Legion: https://gitlab.com/StanfordLegion/legion/-/tree/flexflow
