### ISSUE TITLE
The strategy returned by auto-tuning is slower than the default data parallel strategy

### ISSUE THREAD

**Issue by merrymercy** [flexflow/FlexFlow#217]
### Testing Environment
AWS p3.8xlarge, Deep Learning AMI (Ubuntu 18.04) Version 43.0, 4 x V100 GPUs.
FlexFlow : 6b06996 (master branch, Jun 28, 2021)

### Model definition
The model is a MLP with 8 dense layers.
The file is put in `$FF_HOME/examples/python/native/mlp_2304.py`
https://github.com/merrymercy/FlexFlow/blob/d55288e983418b2c7eaf3987d987782970640ca5/examples/python/native/mlp_2304.py

### Auto-tuning
```
./flexflow_python $FF_HOME/examples/python/native/mlp_2304.py -ll:py 1 -ll:gpu 4 -ll:fsize 14000 -ll:zsize 8192 --batch-size 16384 --export mlp_stra.txt --search-budget 500000 --enable-parameter-parallel -enable-attribute-parallel --search-alpha 0.05
...
iteration(0) current_strategy(318.7493) best_strategy(318.7493)
...
iteration(8000) current_strategy(316.6185) best_strategy(316.6185)
...
iteration(500000) current_strategy(316.6185) best_strategy(316.6185)
=========== Best Discovered Strategy ==========
[Dense_100] num_dims(2) dims[4,1] device_ids[0,1,2,3]
[Dense_101] num_dims(2) dims[4,1] device_ids[0,1,2,3]
[Dense_102] num_dims(2) dims[4,1] device_ids[0,1,2,3]
[Dense_103] num_dims(2) dims[4,1] device_ids[0,1,2,3]
[Dense_104] num_dims(2) dims[4,1] device_ids[0,1,2,3]
[Dense_105] num_dims(2) dims[4,1] device_ids[0,1,2,3]
[Dense_106] num_dims(2) dims[1,4] device_ids[0,1,2,3]
[Dense_107] num_dims(2) dims[1,4] device_ids[0,1,2,3]
============= MCMC Search Finished ============
...
```
### Benchmark
1. Use the tuned strategy
```
./flexflow_python $FF_HOME/examples/python/native/mlp_2304.py -ll:py 1 -ll:gpu 4 -ll:fsize 14000 -ll:zsize 8192 --batch-size 16384 --import mlp_stra.txt
...
Time: 0.484 second
```

2.  Use the default data-parallel
```
./flexflow_python $FF_HOME/examples/python/native/mlp_2304.py -ll:py 1 -ll:gpu 4 -ll:fsize 14000 -ll:zsize 8192 --batch-size 16384
...
Time: 0.333 second
```

### Questions
I have the following observations.
- **O1** The tuned strategy is slower than default data parallel strategy.
- **O2** The execution time estimated by the simulator is not very accurate, at least for the returned strategy.
- **O3** The MCMC search does not improve the execution time a lot even in the simulator. It only reduces the estimated execution time from 318.7493 to 316.7213. In addition, the estimated execution time stops to decrease after 8000 iterations. Adding more search iterations does not improve the result.

Are **O1** and **O2** due to the wrong configuration of the simulator or inefficient implementation of the runtime?
For example, the NVlink-based GPU-to-GPU connection on p3.8xlarge is not symmetric. How to configure the simulator to fit the real topology better?
Is **O3** the expected behavior of the MCMC search?

**Comment by MiZhangWhuer** [comment]
@merrymercy The same issue to me. The gap mainly comes from the code in compile function?
if (config.import_strategy_file.length() > 0) {
    load_strategies_from_file(config.import_strategy_file, config.strategies);
  }
  if (config.search_budget > 0) {
    // Launch the search task
    FFModel* model = this;
    TaskLauncher launcher(STRATEGY_SEARCH_TASK_ID,
        TaskArgument(&model, sizeof(FFModel*)));
    Future future = runtime->execute_task(ctx, launcher);
    future.get_void_result();
  } else {
    // Do nothing
  }

When testing with the C++ interface, it achieves a better performance. Maybe the gap is the communication time of C++ and python binding?

**Comment by merrymercy** [comment]
In the python script, I only call four APIs without any large arguments (https://github.com/merrymercy/FlexFlow/blob/d55288e983418b2c7eaf3987d987782970640ca5/examples/python/native/mlp_2304.py#L46-L49).
The FFI overhead should be minimal.

**Comment by eddy16112** [comment]
The only difference between c++ and python is c++ enables control replication optimization by default, and python does not. However, when running on single node, the control replication optimization should not make any difference.

**Comment by eddy16112** [comment]
@merrymercy looks like your python script does not enable legion tracing. Please take a look at https://github.com/flexflow/FlexFlow/blob/master/python/flexflow/core/flexflow_cffi.py#L1732

**Comment by merrymercy** [comment]
@eddy16112  What's the functionality of legion tracing? How does it impact the performance?

**Comment by MiZhangWhuer** [comment]
> @merrymercy looks like your python script does not enable legion tracing. Please take a look at https://github.com/flexflow/FlexFlow/blob/master/python/flexflow/core/flexflow_cffi.py#L1732

Even the tracing is set, the performance drop dramatically. Is is relate to GASNet library?

**Comment by MiZhangWhuer** [comment]
@merrymercy I‘ve sent an message to your gmail. Please check it and hope online communication for the prompt reply.

**Comment by eddy16112** [comment]
> @eddy16112 What's the functionality of legion tracing? How does it impact the performance? I tried to add tracing but it only makes the execution slower.
> 
> I also tried to run Flexflow on multiple nodes but found it is very slow. I am using the python interface, how to enable the "control replication optimization"?

tracing is important optimization which can memorize the dependencies of a DAG without analyze it every iteration. 

My mistake, the control replication is not enabled by default for C++ API. I think you do not need to enable it for the comparison between C++ and python. 
To enable control replication, you will need to use the [create_data_loader2](https://github.com/flexflow/FlexFlow/blob/master/python/flexflow/core/flexflow_cffi.py#L1817) instead of `create_data_loader` (I know the name is confusing), then when running the program, you will need to add [--control-replication](https://github.com/flexflow/FlexFlow/blob/master/src/mapper/mapper.cc#L1508).

**Comment by merrymercy** [comment]
It seems that the `create_data_loader2` API is broken during the recent ffi refactor.
I got this error
```
  File "/home/ubuntu/efs/FlexFlow/examples/python/native/mlp.py", line 88, in <module>
    top_level_task()
  File "/home/ubuntu/efs/FlexFlow/examples/python/native/mlp.py", line 42, in top_level_task
    dataloader_input = ffmodel.create_data_loader2(input_tensor, x_train)
AttributeError: 'FFModel' object has no attribute 'create_data_loader2'
flexflow_python: /home/ubuntu/efs/FlexFlow/deps/legion/runtime/realm/python/python_module.cc:978: virtual void Realm::LocalPythonProcessor::execute_task(Realm::Processor::TaskFuncID, const Realm::ByteArrayRef&)
: Assertion `0' failed.
```
The function `create_data_loader2` is defined in python but not in this binding definition (https://github.com/flexflow/FlexFlow/blob/798ce79e9837fc779d3c910684155d7d7dec81a4/python/bindings.cc#L326)

**Comment by eddy16112** [comment]
> It seems the `create_data_loader2` API is broken during the recent ffi refactor.
> I got this error
> 
> ```
>   File "/home/ubuntu/efs/FlexFlow/examples/python/native/mlp.py", line 88, in <module>
>     top_level_task()
>   File "/home/ubuntu/efs/FlexFlow/examples/python/native/mlp.py", line 42, in top_level_task
>     dataloader_input = ffmodel.create_data_loader2(input_tensor, x_train)
> AttributeError: 'FFModel' object has no attribute 'create_data_loader2'
> flexflow_python: /home/ubuntu/efs/FlexFlow/deps/legion/runtime/realm/python/python_module.cc:978: virtual void Realm::LocalPythonProcessor::execute_task(Realm::Processor::TaskFuncID, const Realm::ByteArrayRef&)
> : Assertion `0' failed.
> ```
> 
> The function `create_data_loader2` is defined in python but not in this binding definition (
> 
> https://github.com/flexflow/FlexFlow/blob/798ce79e9837fc779d3c910684155d7d7dec81a4/python/bindings.cc#L325-L327
> 
> )

Sorry, my mistake, I did not notice the pybind11 backend did not have `create_data_loader2`. If using the pybind11 backend, which is the default python binding of the FlexFlow, the `create_data_loader` should work with control replication.
