### ISSUE TITLE
Sample parallel and attribute parallel are not implement for convolution layers 

### ISSUE THREAD

**Issue by merrymercy** [flexflow/FlexFlow#218]
In the master branch, sample parallel and attribute parallel are not implemented for convolution layers.
Do you have any plan to support them?

In addition, I cannot find a public version of code that fully implements all functionalities mentioned in the FlexFlow paper (full search space + simulator + search algorithm). Is there such a public version?

**Comment by JF-D** [comment]
As far as I know,
simulator in `src/runtime/simulator.cc`,
search algorithm in `src/runtime/model.cc` (`FFModel::optimize`),
full search space in `src/runtime/model.cc` (`Op::get_random_parallel_config`).

**Comment by DavidPeleg6** [comment]
@JF-D @jiazhihao 
from what I understand, in `Op::get_random_parallel_config` (line 534-535 in src/runtime/model.cc) the only dimension that gets randomly split is the batch.
Aside from that, in linear.cu there is an override of the get_random_parallel_config function that also implements random splits in the parameter dimension. 
As @merrymercy mentioned, I also cannot find an implementation of random splits for any other operator.

**Comment by jiazhihao** [comment]
@DavidPeleg6 You are right that FlexFlow currently uses the `get_random_parallel_config` method of the `Op` class to generate parallel configuration for an operator. `get_random_parallel_config` returns data parallelism with different degrees of parallelism by default, and users can overwrite this method to enable more hybrid parallelization strategies.

In the `unify` branch, which will be merged in September, we will be using a simpler interface for defining parallelization strategies of an operator by defining the mappings between input and output tensors of an operator. For example, these lines (https://github.com/flexflow/FlexFlow/blob/unify/src/ops/linear.cc#L278-L287) will enable data, parameter, and reduction parallelism for a linear operator.
