### ISSUE TITLE
Compile error when compiling flexflow deps legion

### ISSUE THREAD

**Issue by JF-D** [flexflow/FlexFlow#219]
Hi,
I use gcc5.4 + cuda10.1. When compiling, I met the following error, it seems the c++11 option is not ON. How can I solve this?
![image](https://user-images.githubusercontent.com/30710061/124848632-d6ce4a00-dfcf-11eb-9a6a-1ff90d5c855c.png)

Best,
Jiangfei

**Comment by eddy16112** [comment]
Could you please give a try with the following patch?

diff --git a/CMakeLists.txt b/CMakeLists.txt
index f588d4fb..bddfa6de 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -59,6 +59,12 @@ set(CC_FLAGS $ENV{CC_FLAGS})
 set(NVCC_FLAGS $ENV{NVCC_FLAGS})
 set(LD_FLAGS $ENV{LD_FLAGS})
 
+list(APPEND CC_FLAGS
+  -std=c++11)
+
+list(APPEND NVCC_FLAGS
+  -std=c++11)
+
 # ZLIB
 include(zlib)
 
@@ -98,7 +104,6 @@ endif()
 message(STATUS "FlexFlow MAX_DIM: ${FF_MAX_DIM}")
 
 list(APPEND CC_FLAGS
-  -std=c++11
   -DMAX_TENSOR_DIM=${FF_MAX_DIM})
 
 if(FF_USE_AVX2)
@@ -109,7 +114,6 @@ endif()
   
 list(APPEND NVCC_FLAGS
   -Wno-deprecated-gpu-targets
-  -std=c++11
   -DMAX_TENSOR_DIM=${FF_MAX_DIM})
   
 list(APPEND LD_FLAGS

**Comment by JF-D** [comment]
It doesn't work.
I think it's the error of Legion. When I compile Legion saparately, and meet similar error. The Legion doesn't set c++11 flag.

**Comment by eddy16112** [comment]
I thought the patch could set the CXX flags for Legion. Could you please add -std=c++11 to CMAKE_CXX_FLAGS using the ccmake?

**Comment by JF-D** [comment]
I think so. But it didn't.
I tried to compile an older version Legion saparately, it works well.
You mean, add c++11 using cmake to CMakeLists of FlexFlow or Legion?  I checked, FlexFlow did have c++11 flag when compiling, but legion didn't have. And I also tried to compile legion with flexflow, and add `add_definitions(-std=c++11)` to legion CMakeLists.txt, it didn't work.

I will check it again. If you have more suggestions, please let me know.

**Comment by eddy16112** [comment]
I will give a try with the gcc5. In the meantime, you can use the Makefile or upgrade the gnu to 6 or later.

**Comment by JF-D** [comment]
Hi,
When I tried to compile flexflow example directly, e.g. in `examples/cpp/AlexNet` folder run `make`, it works well. It seems for each cpp example, I need to compile flexflow once. I wonder what the result is after compiling flexflow, a library for python binding or something else, and how do flexflow compile with legion together, since the variables(`FLEXFLOW_EXT_LIBRARIES`) extended in `legion.cmake` are only used in the MakeFile of cpp examples.

**Comment by JF-D** [comment]
Well, I find what's wrong:)

Follow https://github.com/flexflow/FlexFlow/issues/219#issuecomment-876098384 and https://github.com/flexflow/FlexFlow/issues/219#issuecomment-876420485, `CC_FLAGS` makes sense in MakeFile, and `CMAKE_CXX_FLAGS` makes sense in CMakeLists.txt. In your patch, you should add `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`. 

Thanks a lot!
Jiangfei

**Comment by JF-D** [comment]
I am sorry, but what about this...
![image](https://user-images.githubusercontent.com/30710061/124940665-c0aaa300-e03c-11eb-9772-1acf839754ca.png)

**Comment by eddy16112** [comment]
Have you installed the cuBLAS? Here is my cmake cmd, and I can not reproduce your error.  By the way, thank you for letting me know the Legion c++11 bug, I already fixed it in the master branch. 
-DCUDA_USE_STATIC_CUDA_RUNTIME=OFF -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/home/wwu/flexflow-cmake/install -DCMAKE_BUILD_TYPE=Debug -DCUDA_PATH=/projects/opt/centos7/cuda/10.1 -DFF_USE_PYTHON=ON -DFF_USE_NCCL=OFF -DFF_USE_GASNET=OFF -DFF_BUILD_ALL_EXAMPLES=ON -DFF_USE_AVX2=OFF -DFF_MAX_DIM=4

**Comment by JF-D** [comment]
In `cmake/cuda.cmake`, the cublas path is specified in `$CUDA_ROOT/lib64`, but according to https://forums.developer.nvidia.com/t/cublas-for-10-1-is-missing/71015 ,  cublas is moved out of cuda dir in (maybe after) cuda10.1, I think maybe the cublas lib path can be setted as a macro.

**Comment by eddy16112** [comment]
Thanks for letting me know. I will fix the cublas.
