### ISSUE TITLE
Question about dataloader

### ISSUE THREAD

**Issue by JF-D** [flexflow/FlexFlow#220]
Hi,

When I run examples, I notice the model usually uses cifar/minist dataset. I wonder how the dataloader is implemented in FlexFlow. Are all data stored in GPU memory or loaded from cpu memory like pytorch dataloader? I want to know the data load time and if there are synthetic dataset example. I want to compare the speed of synthetic data training.

Thanks a lot!
Jiangfei

**Comment by eddy16112** [comment]
The entire dataset will be loaded into pinned CPU memory, and in each iteration, one batch will be moved into GPU memory asynchronously. Currently the dataloader should support any 4D and 2D datasets, here is the [API](https://github.com/flexflow/FlexFlow/blob/master/python/flexflow/core/flexflow_cffi.py#L1783). The full array is a numpy array containing the entire data.

**Comment by JF-D** [comment]
Thanks a lot!

The cpp example can use random input like this https://github.com/flexflow/FlexFlow/blob/master/examples/cpp/AlexNet/alexnet.cc#L100, I want to know how can I use random input like this in python, is there an example?

**Comment by eddy16112** [comment]
https://github.com/flexflow/FlexFlow/blob/master/examples/python/native/cifar10_cnn.py#L56
you can pass a random numpy array instead of the one containing the data
