### ISSUE TITLE
【import error】libflwxflow.so not find

### ISSUE THREAD

**Issue by imyzx2017** [flexflow/FlexFlow#222]
I had build flexflow by compiling source code. But got a import error as below:
How can I solve this? Thanks

```
import flexflow.torch.fx as fx
Using pybind11 flexflow bindings.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/flexflow/torch/fx.py", line 18, in <module>
    from flexflow.core.flexflow_type import ActiMode, AggrMode, PoolType, DataType, LossType, MetricsType, OpType, enum_to_int, enum_to_str
  File "/opt/conda/lib/python3.8/site-packages/flexflow/core/__init__.py", line 29, in <module>
    from .flexflow_pybind11 import *
  File "/opt/conda/lib/python3.8/site-packages/flexflow/core/flexflow_pybind11.py", line 20, in <module>
    from .flexflow_pybind11_internal import ActiMode, CompMode, DataType, LossType, MetricsType, PoolType, ParameterSyncType
ImportError: libflexflow.so: cannot open shared object file: No such file or directory
```

**Comment by eddy16112** [comment]
You will need to export PYTHONPATH=your flexflow dir/python/flexflow/core:$PYTHONPATH

**Comment by imyzx2017** [comment]
> You will need to export PYTHONPATH=your flexflow dir/python/flexflow/core:$PYTHONPATH

Here is my flexflow/core dir, still not find libflexflow.so file.. 
After setting my PYTHONPATH,  import still got same error  0.0
![image](https://user-images.githubusercontent.com/32630786/126929603-1a3eac48-70c3-4778-9ed8-7d5acbaf4b51.png)

**Comment by eddy16112** [comment]
You should not use python native interpreter, you will need to use flexflow_python ../example/

**Comment by imyzx2017** [comment]
> You should not use python native interpreter, you will need to use flexflow_python ../example/

Thans for your help! After setting libPATH, running test using native python or flexflow_python passed!
