### ISSUE TITLE
How to define or generate the Enhanced-Machine-Model-File?

### ISSUE THREAD

**Issue by imyzx2017** [flexflow/FlexFlow#226]
When I using your auto parallel search function on MLP model, Flexflow can generate parallel-config-file with sampleParallel setting and  channelParallel setting.
`flexflow_python mlp.py -ll:py 1 -ll:gpu 4 -ll:fsize 24000 -ll:zsize 8192 --batch-size 6400 --export mlp_stra_4gpus_pc2.txt --search-budget 50000 --enable-parameter-parallel --enable-attribute-parallel --search-alpha 0.05`
But when i train the MLP model using `--import strategy.txt`, the trainingConsumeTime is bigger than using AllDataParallelConfig. (4 Tesla V100 with NVLINK). One possible reason is that I used default simpleMachineModel to do parallel-search-task. So here is my question:
How can I define or generate the Enhanced-Machine-Model-File? Any tools? Thanks !

**Comment by eddy16112** [comment]
@dycz0fx Can you take a look at this issue?

**Comment by dycz0fx** [comment]
The enhanced machine model needs a config file to know the configuration of a machine. Please refer to this config file (https://github.com/flexflow/FlexFlow/blob/master/machine_config_example) as an example. To get better estimations, you may want to use some benchmarks to get the actual latency and bandwidth of the communication devices you plan to use. The benchmark I used is the Memspeed benchmark in legion/test/realm. Once you have the config file, you can launch the enhanced machine model with `--machine-model-version 1 --machine-model-file /path/to/machine_config --simulator-segment-size 4194304 --simulator-max-num-segments 10`.

**Comment by imyzx2017** [comment]
> The enhanced machine model needs a config file to know the configuration of a machine. Please refer to this config file (https://github.com/flexflow/FlexFlow/blob/master/machine_config_example) as an example. To get better estimations, you may want to use some benchmarks to get the actual latency and bandwidth of the communication devices you plan to use. The benchmark I used is the Memspeed benchmark in legion/test/realm. Once you have the config file, you can launch the enhanced machine model with `--machine-model-version 1 --machine-model-file /path/to/machine_config --simulator-segment-size 4194304 --simulator-max-num-segments 10`.

thanks for your reply!
