### ISSUE TITLE
How to obtain the HDF5 dataset for DLRM training 

### ISSUE THREAD

**Issue by shengchengwang** [flexflow/FlexFlow#230]
Dear all,

I am playing with the DLRM and facing an issue regarding the format of the training dataset. I downloaded the dataset from Criteo, and decompress it. Afterward, I got two text files ("train.txt" and "test.txt"). What is the most smooth way to preprocess the two files? I noticed that there is a "preprocess_hdf.py" file in the folder, but how to use it? Thx.

**Comment by jiazhihao** [comment]
The 7-day criteo Kaggle dataset is available at http://sapling.stanford.edu/~zhihao/kaggle_all.h5.

**Comment by shengchengwang** [comment]
> The 7-day criteo Kaggle dataset is available at http://sapling.stanford.edu/~zhihao/kaggle_all.h5.

Thank you for the sharing
