### ISSUE TITLE
How to compile in Release

### ISSUE THREAD

**Issue by roman955b** [flexflow/FlexFlow#231]
In how many places, and where (including the submodules), does one has to configure the FlexFlow solution in order to compile in Release? (Does one have to set any env. variables too?)
I compile using by calling 
1) creating a build directory `git/FlexFlow/build`
2) From inside `git/FlexFlow/build` I call:  `../config/config.linucx`
3) I build using `make build`

**Comment by roman955b** [comment]
The background of my question is that I get low throughput on GPU, far below what the simulator generates.
I also get lower and lower throughput as I increase the number of epochs.

For example, when testing on AlexNet the MCMC generated strategy gives me these numbers:
```
epochs 1, ELAPSED TIME = 2.0643s, THROUGHPUT = 4844.21 samples/s
epochs 1, ELAPSED TIME = 2.0421s, THROUGHPUT = 4896.81 samples/s
epochs 1, ELAPSED TIME = 2.0796s, THROUGHPUT = 4808.69 samples/s
epochs 5, ELAPSED TIME = 11.4411s, THROUGHPUT = 4370.22 samples/s
epochs 5, ELAPSED TIME = 11.4344s, THROUGHPUT = 4372.77 samples/s
epochs 5, ELAPSED TIME = 11.6385s, THROUGHPUT = 4296.09 samples/s
epochs 10, ELAPSED TIME = 33.1380s, THROUGHPUT = 3017.68 samples/s
epochs 10, ELAPSED TIME = 33.4647s, THROUGHPUT = 2988.22 samples/s
epochs 10, ELAPSED TIME = 33.7055s, THROUGHPUT = 2966.88 samples/s
```

**Comment by eddy16112** [comment]
It is compiled in release mode by default. Please check if BUILD_TYPE is Release or not. 
https://github.com/flexflow/FlexFlow/blob/master/config/config.linux#L19

**Comment by roman955b** [comment]
Thanks. 

I followed those instructions (plus I add the flag `--python-data-loader-type 2 ` as a FlexFlow warning hinted me to do).

It runs on GPU but I get this warning about every ~1000 data points (images) when training AlexNet.

```
[0 - 7fb008fea700]   28.898951 {4}{runtime}: [warning 1097] LEGION WARNING: WARNING: The runtime has failed to memoize the trace more than 5 times, due to the absence of a replayable template. It is highly likely that trace 201 will not be memoized for the rest of execution. The most recent template was not replayable for the following reason: precondition not subsumed by postcondition. Please change the mapper to stop making memoization requests. (from file /FlexFlow/deps/legion/runtime/legion/legion_trace.cc: 2025)                                                                                                                                                      
For more information see:                                                                 
http://legion.stanford.edu/messages/warning_code.html#warning_code_1097    
```

**Comment by roman955b** [comment]
Question continued in issue #232 .
Thanks
