### ISSUE TITLE
RTX 3090 not supported?

### ISSUE THREAD

**Issue by ConnollyLeon** [flexflow/FlexFlow#239]
I am trying to build FlexFlow with RTX 3090. 
But I got 
```text
nvcc fatal: Unsupported gpu architecture 'compute_86' 
```
when trying to build deps/nccl.

Any Suggestions to solve this?

**Comment by eddy16112** [comment]
If the error comes from the NCCL, can you try to disable the NCCL?
https://github.com/flexflow/FlexFlow/blob/master/config/config.linux#L34

**Comment by ConnollyLeon** [comment]
I tried, but got this error:
```text
[ 41%] Built target RealmRuntime
[ 41%] Performing build step for 'nccl'
nvcc fatal   : Unsupported gpu architecture 'compute_86'
make[5]: *** [Makefile:53：/home/connolly/Documents/GitHub/FlexFlow/build/deps/nccl/obj/collectives/device/sendrecv.dep] Error 1
make[4]: *** [Makefile:50：/home/connolly/Documents/GitHub/FlexFlow/build/deps/nccl/obj/collectives/device/colldevice.a] Error 2
make[3]: *** [Makefile:25：src.build] Error 2
make[2]: *** [CMakeFiles/nccl.dir/build.make:112：deps/nccl/src/nccl-stamp/nccl-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:379：CMakeFiles/nccl.dir/all] Error 2
make: *** [Makefile:130：all] Error 2

```

**Comment by eddy16112** [comment]
When FF_USE_NCCL is set to OFF, you should not see deps/nccl are compiled. 
Also, please check the output of CMake, you should see something like this:
-- CUDA Detected CUDA_ARCH : 61
check if the number is correct for your GPU.

**Comment by ConnollyLeon** [comment]
Well... I found out that I should delete all generated files created by `config/config.linux` before building with other configurations. 

I have set FF_USE_NCCL to OFF now, but I got this error:
```text
[ 47%] Built target RealmRuntime
[ 47%] Building NVCC (Device) object deps/legion/runtime/CMakeFiles/cuda_compile_1.dir/legion/cuda_compile_1_generated_legion_redop.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_86'
CMake Error at cuda_compile_1_generated_legion_redop.cu.o.Release.cmake:220 (message):
  Error generating
  /home/connolly/Documents/GitHub/FlexFlow/build/deps/legion/runtime/CMakeFiles/cuda_compile_1.dir/legion/./cuda_compile_1_generated_legion_redop.cu.o


make[2]: *** [deps/legion/runtime/CMakeFiles/LegionRuntime.dir/build.make:65：deps/legion/runtime/CMakeFiles/cuda_compile_1.dir/legion/cuda_compile_1_generated_legion_redop.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:270：deps/legion/runtime/CMakeFiles/LegionRuntime.dir/all] Error 2
make: *** [Makefile:130：all] Error 2
```
I am sure 86 is correct arch number for RTX 3090.

**Comment by eddy16112** [comment]
How do you set the FF_CUDA_ARCH? You will need to set it to 86 not compute_86.

**Comment by ConnollyLeon** [comment]
I didn't set FF_CUDA_ARCH. It is set automatically.

**Comment by eddy16112** [comment]
Please check this link, https://github.com/NVIDIAGameWorks/kaolin/issues/351, it could be a driver issue. 

I am sorry I do not have a RTX 3090, so I can not test it for you. Can you type "make VERBOSE=1" and paste the output for cuda_compile_1_generated_legion_redop.cu.o, I just want to make sure the generated makefile is correct.

**Comment by JialongZhou666** [comment]
> I didn't set FF_CUDA_ARCH. It is set automatically.

Hi, have you solved this question?
