### ISSUE TITLE
Remove the virtual function Parameter* get_parameter(int index) = 0 from Op base class

### ISSUE THREAD

**Issue by eddy16112** [flexflow/FlexFlow#24]
@jiazhihao I plan to remove the virtual function `virtual Parameter* get_parameter(int index) = 0;` from the Op base class and move it down to child classes like Conv2d, Linear and etc., since not all Ops have parameters. 

When calling it from python, I can cast the Op* to Conv2d* (or others) because when calling this function, users should already know what kind of Ops it is. 

Please let me know your suggestions.

**Comment by jiazhihao** [comment]
@eddy16112 One benefit to keep it as a base class function is supporting traversing the model and collecting all trainable weights. This also seems to be the design used in TensorFlow Keras: https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/keras/engine/base_layer.py#L1546-L1588

I think for not it is better to keep our interface consistent with Keras to minimize mismatches.

**Comment by eddy16112** [comment]
I see. It makes senses to me. Thanks.
