### ISSUE TITLE
Alexnet crashes after the interface changes commit 

### ISSUE THREAD

**Issue by eddy16112** [flexflow/FlexFlow#25]
@jiazhihao I noticed the Flexflow crashes after your latest commit 
[https://github.com/flexflow/FlexFlow/commit/2bc9997a269cd420515549770aea6c750b25d511](url)

Here is the error I get from Alexnet:
[wwu12@saturn AlexNet_old]$ mpirun -np 1 ./alexnet -ll:gpu 1 -ll:fsize 2048 -ll:zsize 12192
[0 - 7ffff7fcd800] {4}{threads}: reservation ('DMA request queue') cannot be satisfied
[0 - 7ffff7fa0800] {3}{Mapper}: No strategy file provided. Use default data parallelism.
[0 - 7ffff7fa0800] {3}{AlexNet}: batchSize(64) workersPerNodes(1) numNodes(1)
in update_metrics_task
workSpaceSize (1024 MB)
seed = 1804289383 scale = 0.1185
[0 - 7ffff7fa0800] {3}{AlexNet}: Use random dataset...
[0 - 7ffff7fa0800] {3}{AlexNet}: Number of random samples = 2560

alexnet: /home/wwu12/legion-cr/runtime/legion/region_tree.cc:5819: void Legion::Internal::RegionTreeForest::initialize_path(Legion::Internal::IndexTreeNode*, Legion::Internal::IndexTreeNode*, Legion::Internal::RegionTreePath&): Assertion `child->depth > 0' failed.

**Comment by eddy16112** [comment]
Here is the stack, but I did not get too much information for me to debug since it is not in FF.

#7  0x00007fffd54430d2 in __assert_fail () from /lib64/libc.so.6
#8  0x00000000029329e2 in Legion::Internal::RegionTreeForest::initialize_path (this=0x69c1010, child=0x7ffbe44334a0, parent=0x7ffbe4436e30, path=...) at /home/wwu12/legion-cr/runtime/legion/region_tree.cc:5819
#9  0x0000000002932831 in Legion::Internal::RegionTreeForest::initialize_path (this=0x69c1010, child=..., parent=..., path=...) at /home/wwu12/legion-cr/runtime/legion/region_tree.cc:5785
#10 0x0000000002539f27 in Legion::Internal::Operation::initialize_privilege_path (this=0x7ffbe44cdb50, path=..., req=...) at /home/wwu12/legion-cr/runtime/legion/legion_ops.cc:178
#11 0x0000000002607acd in Legion::Internal::IndexTask::trigger_prepipeline_stage (this=0x7ffbe44cd9a0) at /home/wwu12/legion-cr/runtime/legion/legion_tasks.cc:7993
#12 0x000000000253aabe in Legion::Internal::Operation::execute_prepipeline_stage (this=0x7ffbe44cdb50, generation=0, from_logical_analysis=true) at /home/wwu12/legion-cr/runtime/legion/legion_ops.cc:416
#13 0x000000000253ac14 in Legion::Internal::Operation::execute_dependence_analysis (this=0x7ffbe44cdb50) at /home/wwu12/legion-cr/runtime/legion/legion_ops.cc:437
#14 0x0000000002540e34 in Legion::Internal::SpeculativeOp::execute_dependence_analysis (this=0x7ffbe44cdb50) at /home/wwu12/legion-cr/runtime/legion/legion_ops.cc:2375
#15 0x000000000259b5ec in Legion::Internal::MemoizableOp<Legion::Internal::SpeculativeOp>::execute_dependence_analysis (this=0x7ffbe44cdb50) at /home/wwu12/legion-cr/runtime/legion/legion_ops.inl:124
#16 0x000000000266d7fa in Legion::Internal::InnerContext::process_dependence_stage (this=0x7ffbec2017c0) at /home/wwu12/legion-cr/runtime/legion/legion_context.cc:7070
#17 0x000000000267668e in Legion::Internal::InnerContext::handle_dependence_stage (args=0x7ffbe44d36e0) at /home/wwu12/legion-cr/runtime/legion/legion_context.cc:9236
#18 0x0000000002a21a93 in Legion::Internal::Runtime::legion_runtime_task (args=0x7ffbe44d36e0, arglen=12, userdata=0x69e1b00, userlen=8, p=...) at /home/wwu12/legion-cr/runtime/legion/runtime.cc:26256
#19 0x0000000003e2b61d in Realm::LocalTaskProcessor::execute_task (this=0x69843c0, func_id=133, task_args=...) at /home/wwu12/legion-cr/runtime/realm/proc_impl.cc:979
#20 0x00000000047aa0db in Realm::Task::execute_on_processor (this=0x7ffbe44d3540, p=...) at /home/wwu12/legion-cr/runtime/realm/tasks.cc:198
#21 0x00000000047ae38a in Realm::UserThreadTaskScheduler::execute_task (this=0x69846e0, task=0x7ffbe44d3540) at /home/wwu12/legion-cr/runtime/realm/tasks.cc:1431
#22 0x00000000047ac6ad in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x69846e0) at /home/wwu12/legion-cr/runtime/realm/tasks.cc:935

**Comment by jiazhihao** [comment]
The bug should have been fixed by commit 0eeb7dac71.

**Comment by eddy16112** [comment]
Thanks, it works now.
