### ISSUE TITLE
[Issues when running examples] watchdog: BUG: soft lockup - CPU#0 stuck for 23s!

### ISSUE THREAD

**Issue by MadFunMaker** [flexflow/FlexFlow#261]
I am trying to run cpp examples in FlexFlow (e.g., InceptionV3). I built FlexFlow successfully with the following configuration:

> BUILD_TYPE=Release
> 
> #set CUDA Arch, replace xx with your GPU architecture
> #FF_CUDA_ARCH=xx
> 
> #set CUDNN dir in case cmake cannot autodetect a path
> CUDNN_DIR=/usr/local/cuda
> 
> #set CUDA dir in case cmake cannot autodetect a path
> #CUDA_DIR=/usr/local/cuda
> 
> #enable Python
> FF_USE_PYTHON=ON
> 
> #enable NCCL
> FF_USE_NCCL=OFF
> 
> #enable GASNet
> FF_USE_GASNET=OFF
> 
> #select GASNET conduit
> FF_GASNET_CONDUIT=mpi
> 
> #build C++ examples
> FF_BUILD_ALL_EXAMPLES=ON
> 
> #enable avx2
> FF_USE_AVX2=OFF
> 
> #set MAX_DIM
> FF_MAX_DIM=4

However, when I run FlexFlow examples such as Inception V3, it always incurs the following kernel error after finishing training or violating assertion: 
`kernel:[256610.941256] watchdog: BUG: soft lockup - CPU#29 stuck for 22s! [inception:274704]`

Does anybody have any clue to fix this issue?

FYI, to run the examples, I ran the following scripts:
`CUDA_VISIBLE_DEVICES=0,1 ./examples/cpp/InceptionV3/inception -ll:gpu 2 -ll:fsize 2048 -ll:zsize 12192 -e 10 -b 64`

**Comment by eddy16112** [comment]
Have you tried other examples?

**Comment by lockshaw** [comment]
Closing for now, feel free to reopen if this issue still exists.
