### ISSUE TITLE
make failed when building nvcc objects - installing FlexFlow according to tutorial

### ISSUE THREAD

**Issue by MackZackA** [flexflow/FlexFlow#263]
I am setting up FlexFlow on an EC2 instance, following tutorials in 

The make process errored when building NVCC objects at 47%.
The error message showed: "/usr/local/cuda/include/crt/host_config.h:129:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!"

**Comment by eddy16112** [comment]
Which CUDA version are you using? I think you are using a old version of CUDA. I think you can either using a newer CUDA or a gcc lower than 7.0

**Comment by eddy16112** [comment]
@MackZackA I think the issue is fixed, right? If so, I will close the it.
