### ISSUE TITLE
ERROR: The binary was compiled for the wrong GPU architecture. Update the 'GPU_ARCH' flag at the top of runtime/runtime.mk to match/include your current GPU architecture (80).

### ISSUE THREAD

**Issue by TonyTangYu** [flexflow/FlexFlow#267]
I installed FlexFlow from the source code. 
When testing FlexFlow with pytorch interface, errors occurred.  Our environment is PyTorch 1.5, cuda 11.0, and cudnn 8.0. After installing FlexFlow, we came into the following error when running `./flexflow_python $FF_HOME/examples/python/pytorch/mnist_mlp_torch.py -ll:py 1 -ll:gpu 4 -ll:fsize 2048 -ll:zsize 12192`. 

> [0 - 7f7911e7bfc0] 4098.849694 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4098.849696 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4098.849698 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4098.849699 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4098.849701 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4098.849703 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4098.849704 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4098.849706 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4100.077353 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4100.077362 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4100.077366 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4100.077369 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4100.077372 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4100.077374 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4100.077377 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4100.077379 {4}{gpu}: duplicate registration of function _ZN6thrust8cuda_cub3cub11EmptyKernelIvEEvv
> [0 - 7f7911e7bfc0] 4103.231768 {5}{gpu}: ERROR: The binary was compiled for the wrong GPU architecture. Update the 'GPU_ARCH' flag at the top of runtime/runtime.mk to match/include your current GPU architecture (80).

I tried to specify the `FF_CUDA_ARCH=80` in the `config/config.linux` file. I also modified the runtime.mk in the `deps/legion/runtime` folder and set `GPU_ARCH = ampere`. However, none of these methods worked. I still run into the above error. 

Is there any method to solve the above errors? Thanks ahead.

**Comment by TonyTangYu** [comment]
@jiazhihao  Thanks for your reply. The following is the output of running config/config.linux:

>  Defaults for Linux machine
> cmake -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF -DCMAKE_C_COMPILER=/mnt/cache/share/gcc/gcc-5.4/bin/gcc -DCMAKE_CXX_COMPILER=/mnt/cache/share/gcc/gcc-5.4/bin/g++ -DCMAKE_BUILD_TYPE=Release -DFF_CUDA_ARCH=80 -DCUDA_PATH=/mnt/cache/share/platform/dep/cuda11.0-cudnn8.0/targets/x86_64-linux/lib/stubs -DCUDNN_PATH=/mnt/cache/share/platform/dep/cuda11.0-cudnn8.0 -DFF_USE_PYTHON=ON -DFF_USE_NCCL=OFF -DFF_USE_GASNET=OFF -DFF_BUILD_ALL_EXAMPLES=OFF -DFF_USE_AVX2=OFF -DFF_MAX_DIM=8 ../config/../
> -- ZLIB libraries : /usr/lib64/libz.so
> -- CUDA root path : /mnt/cache/share/platform/dep/cuda11.0-cudnn8.0
> -- CUDA include path : /mnt/cache/share/platform/dep/cuda11.0-cudnn8.0/include
> -- CUDA runtime libraries : 
> -- CUDA driver libraries : /mnt/cache/share/platform/dep/cuda11.0-cudnn8.0/lib64/stubs/libcuda.so
> -- CUBLAS libraries : /mnt/cache/share/platform/dep/cuda11.0-cudnn8.0/lib64/libcublas.so
> -- CURAND libraries : /mnt/cache/share/platform/dep/cuda11.0-cudnn8.0/lib64/libcurand.so
> -- CUDA Arch : 80
> -- CUDA_GENCODE: -gencode arch=compute_80,code=sm_80
> -- CUDNN inlcude : /mnt/cache/share/platform/dep/cuda11.0-cudnn8.0/include
> -- CUDNN libraries : /mnt/cache/share/platform/dep/cuda11.0-cudnn8.0/lib64/libcudnn.so
> -- GASNET ROOT: 
> CMake Warning (dev) at deps/legion/CMakeLists.txt:307 (find_package):
>   Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
>   Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> 
>   CMake variable CUDA_ROOT is set to:
> 
>     /mnt/cache/share/platform/dep/cuda11.0-cudnn8.0/targets/x86_64-linux/lib/stubs
> 
>   For compatibility, CMake is ignoring the variable.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at /mnt/lustre/tangyu/anaconda3/envs/pytorch/lib/python3.6/site-packages/cmake/data/share/cmake-3.22/Modules/FindCUDA.cmake:1020 (option):
>   Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
>   --help-policy CMP0077" for policy details.  Use the cmake_policy command to
>   set the policy and suppress this warning.
> 
>   For compatibility with older versions of CMake, option is clearing the
>   normal variable 'CUDA_USE_STATIC_CUDA_RUNTIME'.
> Call Stack (most recent call first):
>   deps/legion/cmake/FindCUDA.cmake:22 (include)
>   deps/legion/CMakeLists.txt:307 (find_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- FlexFlow MAX_DIM: 8
> -- pybind11 v2.6.2 
> CMake Warning (dev) at /mnt/lustre/tangyu/anaconda3/envs/pytorch/lib/python3.6/site-packages/cmake/data/share/cmake-3.22/Modules/CMakeDependentOption.cmake:84 (message):
>   Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
>   Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> Call Stack (most recent call first):
>   deps/pybind11/CMakeLists.txt:98 (cmake_dependent_option)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /mnt/cache/tangyu/FlexFlow/build

Is there any help?

**Comment by jiazhihao** [comment]
The cmake output indicates that only CUDA_ARCH 80 is involved in building FlexFlow. Can you confirm that this is a clean build? @eddy16112 any idea?

**Comment by TonyTangYu** [comment]
@jiazhihao Yeah, I always make a new build folder as long as I change the config/config.linux file. FYI, our GPU is A100.

**Comment by eddy16112** [comment]
@TonyTangYu What kid of machine are you using? AWS? @jiazhihao Actually I have seen people had the same issue, but I just can not reproduce it on my machine. Check this issue https://github.com/flexflow/FlexFlow/issues/154

**Comment by knagrecha** [comment]
@eddy16112 I was one of the users in issue #154, I was using Kubernetes pods on an academic private computing cluster. Had a single 1080 GPU, errors would occur even after pod teardowns and relaunches.

**Comment by eddy16112** [comment]
@knagrecha Can you please check the output of nvidia-smi?

**Comment by TonyTangYu** [comment]
@eddy16112  I have read and tried the solutions mentioned in issue #154 and #188 . Unfortunately, they didn't work for me. I am using on an academic private computing cluster, each node equipped 8 GPUs.

**Comment by eddy16112** [comment]
> @eddy16112 I have read and tried the solutions mentioned in issue #154 and #188 . Unfortunately, they didn't work for me. I am using on an academic private computing cluster, each node equipped 8 GPUs.

Can you try the makefile instead of the cmake? Sometimes, the cmake will add some flags and hard to debug.

**Comment by TonyTangYu** [comment]
@eddy16112 Thanks for your quick reply. Could you please offer me instructions of trying the makefile instead of the cmake?

**Comment by eddy16112** [comment]
@TonyTangYu You can check my last comment on how to use makefile. But before trying it, you can also try VERBOSE=1 make -j with cmake, and paste the verbose info for cu files.

**Comment by TonyTangYu** [comment]
@eddy16112  I tried your comment on how to use makefile. However, it didn't work for me. The error still exists.

**Comment by fdouglis** [comment]
@TonyTangYu did you happen to sort this out?  I am hitting the same issue, perhaps even on the same system (8 A-100s -- is it a Lambda Labs server by any chance?)

**Comment by lockshaw** [comment]
Closing as out-of-date for now, feel free to reopen if this issue still exists.
