### ISSUE TITLE
Always "Aborted (core dumped)"

### ISSUE THREAD

**Issue by JialongZhou666** [flexflow/FlexFlow#277]
I have tried many python examples in the keras folder, all of them showed "Aborted (core dumped)".
<img width="891" alt="截屏2022-05-19 17 47 43" src="https://user-images.githubusercontent.com/65952233/169265107-b8462d87-a019-4ecd-bfb2-c213495220dc.png">
The result is in the picture.
What is the problem?

**Comment by JialongZhou666** [comment]
My machine is RTX 8*3090. flex flow 1.0, tensorflow and tensorflow-gpu 2.9.0.

**Comment by eddy16112** [comment]
You should not run the example using the native python interpreter. Please check this link on how to run FlexFlow examples. 
https://github.com/flexflow/FlexFlow/blob/master/INSTALL.md#2-run-flexflow-python-examples

**Comment by JialongZhou666** [comment]
> You should not run the example using the native python interpreter. Please check this link on how to run FlexFlow examples. https://github.com/flexflow/FlexFlow/blob/master/INSTALL.md#2-run-flexflow-python-examples

oh, thank you.
But there is another question: 
ModuleNotFoundError: No module named 'keras_preprocessing'
I met this error when running "./flexflow_python ~/FlexFlow/examples/python/keras/func_cifar10_alexnet.py -ll:py 1 -ll:gpu 8 -ll:fsize 800 -ll:zsize 400", but in the pip list I have this module. So how to solve this question?
<img width="1127" alt="截屏2022-05-20 17 48 55" src="https://user-images.githubusercontent.com/65952233/169502608-bc1ee99f-9733-4ddb-a9af-f79d1288d6b2.png">
<img width="724" alt="截屏2022-05-20 17 49 30" src="https://user-images.githubusercontent.com/65952233/169502721-33b33fb0-b93d-44df-a5fa-323ca467ec6b.png">

**Comment by JialongZhou666** [comment]
It seems like that some libraries, such as tf and keras. They cannot be imported when running "./flexflow_python ~/FlexFlow/examples/python/keras/func_cifar10_alexnet.py -ll:py 1 -ll:gpu 8 -ll:fsize 800 -ll:zsize 400".
<img width="1142" alt="截屏2022-05-20 18 00 17" src="https://user-images.githubusercontent.com/65952233/169504729-cdf1dbee-97af-40e0-8de2-13b5d0da5ccc.png">
The pic shows that I can import them directly in python.

**Comment by eddy16112** [comment]
Yes, it is because of two reasons.
1. there are resource contention between the underline runtime of TF/PyTorch and FlexFlow.
2. FlexFlow and TF/PyTorch may use some common third party libraries, but it is difficulty to know which version is used in TF/PyTorch. If you end up compiling FlexFlow using the version that is different from the one used in TF/PyTorch, you could run to unexpected errors.
