### ISSUE TITLE
Incorrect type checking of ScalarFloorDivNode operands

### ISSUE THREAD

**Issue by sydneyhauke** [flexflow/FlexFlow#282]
If I correctly understand the following line :
https://github.com/flexflow/FlexFlow/blob/ad627c9dd7cac82f7894320a8d896b3b55e6b2dc/python/flexflow/torch/model.py#L1706
scalar floor division supports only int or float operands. 

Then the check is erroneous. We should crash when `scalar` is not an int *and* is not a float.

**Comment by lockshaw** [comment]
@soumyac1999 Can you take a look into this issue? Should be a nice relatively introductory issue (either the current behavior is correct or it will only require a quick fix)

**Comment by soumyac1999** [comment]
@sydneyhauke, the current check is indeed erroneous and will always return True. Thanks for pointing it out.

@lockshaw, I'll send in a PR. Meanwhile, some observations/questions on code style:

1. `assert 0` can usually be replaced by some more meaningful error check or raising more informative exceptions. Google style guide: https://google.github.io/styleguide/pyguide.html#244-decision and an example:
```
$ python error.py
  File "/home/soumya/error.py", line 4, in <module>
    f()
  File "/home/soumya/error.py", line 2, in f
    assert 0, "Error message"
AssertionError: Error message

$ python error.py
Traceback (most recent call last):
  File "/home/soumya/error.py", line 4, in <module>
    f()
  File "/home/soumya/error.py", line 2, in f
    assert 5==3, "Error message"
AssertionError: Error message
```
2. Do we have a perferred way to checking types? `isinstance(x, y)` vs `type(x) == y`

**Comment by lockshaw** [comment]
> `assert 0` can usually be replaced by some more meaningful error check or raising more informative exceptions. Google style guide: https://google.github.io/styleguide/pyguide.html#244-decision and an example:

Absolutely agree, happy to merge any changes with improvements to error reporting. Unfortunately in the rush to build stuff error reporting often gets left to last. If you're interested feel free to either create an issue to discuss refactoring there or start a discussion in flexflow-core. :slightly_smiling_face: 

> Do we have a perferred way for checking types? isinstance(x, y) vs type(x) == y

Situation-dependent: `isinstance` is more robust but can be slower, while `type` equality checks are much faster. I'd say lean toward the former unless it's performance critical (which in general the python layer in FF shouldn't be)
