### ISSUE TITLE
Tensor FFModel::create_tensor Assertion `false' failed.

### ISSUE THREAD

**Issue by liayan** [flexflow/FlexFlow#285]
root@f38d051cad41:/usr/FlexFlow/python# ./flexflow_python ../examples/python/keras/func_mnist_mlp_net2net.py -ll:py 1 -ll:gpu 1 -ll:fsize 14048 -ll:zsize 12192 -b 64
[0 - 7ff60406e700]    0.086492 {3}{Mapper}: No strategy file provided. Use default data parallelism.
[0 - 7ff60406e700]    0.086542 {3}{Mapper}: No strategy file provided. Use default data parallelism.
[0 - 7ff60406e700]    0.086561 {3}{Mapper}: No strategy file provided. Use default data parallelism.
top-level task
Using flexflow backend.
Functional API, mnist mlp teach student
shape:  (60000, 784)
Python API batchSize(64) workersPerNodes(1) numNodes(1)
workSpaceSize (1024 MB)
ndim(2) dims[1 1 0 -1]
flexflow_python: /usr/FlexFlow/src/runtime/model.cc:891: Tensor FFModel::create_tensor(const int*, DataType, const Op*, bool) [with int NDIM = 2]: Assertion `false' failed.
Aborted (core dumped)

**Comment by liayan** [comment]
Could anyone give it a look? Thanks.

**Comment by eddy16112** [comment]
Are you using the latest master branch? I can not reproduce your error, here is my output
```
(flexflow) wwu@g0004:/scratch2/wwu/FlexFlow/python$ ./flexflow_python ../examples/python/keras/func_mnist_mlp_net2net.py -ll:py 1 -ll:gpu 1 -ll:fsize 4096 -ll:zsize 12192 -b 64
[0 - 7f553c063000]    0.278117 {3}{Mapper}: No strategy file provided. Use default data parallelism.
[0 - 7f553c063000]    0.278339 {3}{Mapper}: No strategy file provided. Use default data parallelism.
[0 - 7f553c063000]    0.278493 {3}{Mapper}: No strategy file provided. Use default data parallelism.
Using pybind11 flexflow bindings.
Using flexflow python
start top-level task
top-level task
Using flexflow backend.
Functional API, mnist mlp teach student
shape:  (60000, 784)
Python API batchSize(64) workersPerNodes(1) numNodes(1)
workSpaceSize (1024 MB)
ndim(2) dims[1 1 0 0]
Compiling layer Dense_100
Compiling layer Dense_101
Compiling layer Dense_102
Compiling layer Softmax_103
Index load entire dataset: ptr input_head_ 0x7f50a7f4b010, idx 0, input_ 0x7f50a7f4b010 139984391942160 47040000, input 0x7f50eb9eb860 139985527158880 47040000
seed = 1804289383 scale = 0.0680
seed = 846930886 scale = 0.0765
seed = 1681692777 scale = 0.1072
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Index load entire dataset: ptr input_head_ 0x7f50c48b69a0, idx 0, input_ 0x7f50c48b69a0 139984871582112 60000, input 0x7f50f6d5d060 139985715318880 60000
5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8 
Initializing layer Dense_100
init linear (input): in_dim(784) out_dim(512) batch_size(64)
Initializing layer Dense_101
init linear (input): in_dim(512) out_dim(512) batch_size(64)
Initializing layer Dense_102
init linear (input): in_dim(512) out_dim(10) batch_size(64)
Initializing layer Softmax_103
[Metrics] accuracy: 6.250000% (4 / 64) sparse_categorical_crossentropy: 2.286453
[Metrics] accuracy: 7.812500% (10 / 128) sparse_categorical_crossentropy: 2.283988
...
```
Looks like you are missing three outputs
```
Using pybind11 flexflow bindings.
Using flexflow python
start top-level task
```

**Comment by liayan** [comment]
Thanks for the reply. I am using ubuntu focal as host and bionic docker to run above error. I changed my enviroment to ubuntu bionic now, everything goes fine again. Seems there are some library conflicts with different distros.
