### ISSUE TITLE
Building failed when compiling /home/FlexFlow/python/bindings.cc

### ISSUE THREAD

**Issue by user11209** [flexflow/FlexFlow#287]
The `make` instruction failed on its last steps : (
```  
[root@bd2043998348 build]# make
......
[ 99%] Building CXX object python/CMakeFiles/flexflow_pybind11_internal.dir/bindings.cc.o
/home/FlexFlow/python/bindings.cc: In function ‘pybind11::array {anonymous}::get_array(Tensor&, FFConfig&)’:
/home/FlexFlow/python/bindings.cc:85:13: error: no matching function for call to ‘pybind11::array::array(pybind11::dtype, <brace-enclosed initializer list>, <brace-enclosed initializer list>, float*, NULL)’
         NULL);
......
make[2]: *** [python/CMakeFiles/flexflow_pybind11_internal.dir/build.make:76: python/CMakeFiles/flexflow_pybind11_internal.dir/bindings.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:365: python/CMakeFiles/flexflow_pybind11_internal.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```  
The left out part of the output info is about building the previous 98% of the process and possible candidates of the called function. I will paste the entire output if needed.  
I believe the following candidate is the most likely one, but am not sure.  
```
/home/FlexFlow/deps/pybind11/include/pybind11/numpy.h:696:5: note: candidate: ‘pybind11::array::array(const pybind11::dtype&, pybind11::array::ShapeContainer, pybind11::array::StridesContainer, const void*, pybind11::handle)’
     array(const pybind11::dtype &dt,
     ^~~~~
/home/FlexFlow/deps/pybind11/include/pybind11/numpy.h:696:5: note:   no known conversion for argument 5 from ‘long int’ to ‘pybind11::handle’
```  
Got this result on centos7 docker, with compiler gcc & gcc-c++ .

**Comment by user11209** [comment]
Could anyone please have a look at this? The Dockerfile provided doesn't work at all either.

**Comment by eddy16112** [comment]
Looks like it is the pybind11 issue, can you install the pybind11 using `pip install pybind11`?

**Comment by user11209** [comment]
I tried it in another docker built from `nvidia/cuda:11.1-devel-ubuntu18.04`, it said ```Requirement already satisfied: pybind11 in /opt/conda/lib/python3.9/site-packages (2.10.0)```, and then still reported the same error.

**Comment by user11209** [comment]
I will give further attempt when I get access to the previous centos7 docker.

**Comment by user11209** [comment]
The building process succeeded by deleting the `NULL` parameter from line `85` and line `92` in `python/binding.cc`. It seems pybind11 will complement the fifth argument with default value `handle()` and use the function `pybind11::array::array(const pybind11::dtype&, pybind11::array::ShapeContainer, pybind11::array::StridesContainer, const void*, pybind11::handle)` mentioned before. Does it cause serious problem?

**Comment by eddy16112** [comment]
Are you able to share a docker image that I can give a try? We do use a old version of pybind11, but I just found out that the fifth argument is also `handle()` even in the old pybind11, so I am not sure why we never had any complain from the compiler before. Anyway, it should be find if you delete the `NULL`.

**Comment by user11209** [comment]
Sure, try `docker pull user11209/flexflow-image:v1`. Please inform me if there's anything wrong with my configuration,thx.
