### ISSUE TITLE
Deadcode Elimination

### ISSUE THREAD

**Issue by jiazhihao** [flexflow/FlexFlow#306]
Hi issue tracks the progress of eliminating `#ifdef DEADCODE` ... `#endif` marcos in the codebase.

**Comment by lockshaw** [comment]
@virena You mind taking care of this? Should be pretty simple, just go through the code and remove any `DEADCODE` `ifdefs`. If any look important (i.e., things we should not be deleting for some reason) we can discuss them here. 

No particular rush on this issue, just when you get time :slightly_smiling_face:

**Comment by lockshaw** [comment]
Also see https://github.com/flexflow/FlexFlow/blob/34a21dd7a3cf30100a9c4cb87318633495c001f9/python/flexflow_dataloader.cc#L782

**Comment by eddy16112** [comment]
We have many data loader classes that are not used anymore, please see here
https://github.com/flexflow/FlexFlow/blob/master/python/flexflow_dataloader.cu#L128
On Python side, the following code can be removed
https://github.com/flexflow/FlexFlow/blob/master/python/flexflow/core/flexflow_cffi.py#L2195-L2240
