### ISSUE TITLE
  Please！Which files or functions are added in TASO to allow Unity to account for parallelization？

### ISSUE THREAD

**Issue by sunnie-star** [flexflow/FlexFlow#314]
In the paper "Unity: Accelerating DNN Training...", there's one sentence " To allow Unity to account for parallelization, we extend the fingerprint function in TASO  to include the parallelism degree of each tensor dimension."  

In which files is the specific implementation method? If you could point out the specific function, that's really very grateful.

**Comment by lockshaw** [comment]
Moving discussion to #351.
