### ISSUE TITLE
Fix parallel operators measure_operator_cost function

### ISSUE THREAD

**Issue by eric-zheng** [flexflow/FlexFlow#315]
The `sync_time`, `inputs_memory`, `outputs_memory`, and `weights_memory` should be set as 0 in the `measure_operator_cost` function of parallel operators.

The affected parallel ops include (may be an incomplete list):
- combine
- fused_parallel_op
- partition
- reduction
- replicate

To test the result, please run the mlp model multiple times with multiple GPUs and check the final cost number near the end of the log. It should be a reasonable positive number, instead of a negative or very large positive number.

Thanks

**Comment by lockshaw** [comment]
Requires #339 to be fixed
