### ISSUE TITLE
SEARCH.md is missing in README.md

### ISSUE THREAD

**Issue by Jack47** [flexflow/FlexFlow#318]
Autotuning's link is missing in [README.md pytorch support section](https://github.com/flexflow/FlexFlow/blob/d670657254059b3427a9705b8880fbb8a4ef1a5a/README.md#pytorch-support)

**Comment by lockshaw** [comment]
@virena Up to taking care of this? Happy to help if you have any questions :slightly_smiling_face:

**Comment by virena** [comment]
This is now resolved in [master](https://github.com/flexflow/FlexFlow/blob/master/README.md). Both autotuning links take the reader to the Unity paper.
