### ISSUE TITLE
Merge improved memory usage calculation back into master

### ISSUE THREAD

**Issue by eric-zheng** [flexflow/FlexFlow#329]
This issue to track the work to support memory cost calculation considering MachineView, devices, optimizations, etc.

**Comment by lockshaw** [comment]
@eric-zheng Let's use this for tracking the merge back into master of the improved memory calculation on the memory branch

**Comment by eric-zheng** [comment]
A draft to merge memory back to master (after merging master to the memory branch): https://github.com/flexflow/FlexFlow/pull/378
