### ISSUE TITLE
Multihead attention illegal memory access

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#334]
```
cd [your directory]/FlexFlow/build/examples/cpp/Transformer
CUDA_VISIBLE_DEVICES=1 ./transformer -ll:gpu 1 -ll:fsize 6000 -ll:zsize 8000 -b 1
```
Sometimes results in 
```
CU: cuEventSynchronize(e) = 700 (CUDA_ERROR_ILLEGAL_ADDRESS): an illegal memory access was encountered
```

Reported by Byungsoo:
> I found out that it happens when simulator measure cost of MultiHeadAttention. Still it’s not like it happens every time. It happens randomly (e.g., sometimes on the first MultiHeadAttention, the other times on the third MultiHeadAttention).
> Self-answer: it seems like the error goes away if I reduce the size of network. I guess it happens when it goes beyond memory allocated. (edited)

**Comment by lockshaw** [comment]
Potentially related report by Wonchan:
FF apparently segfualts on 
```
./transformer -ll:gpu 1 -ll:fsize 14000 -ll:zsize 14000
```

**Comment by DanGuge** [comment]
hello guys, I have the same problems, have you solved it now?When I run https://github.com/flexflow/FlexFlow/blob/osdi2022ae/scripts/osdi22ae/bert.sh

**Comment by DanGuge** [comment]
Hi guys, I have the same problem, have you fixed it now?
I have tested the scripts here https://github.com/flexflow/FlexFlow/tree/osdi2022ae/scripts/osdi22ae, and passed all scripts except bert.sh, and the "illagel memory access" problem happens every time.
* When running BERT with a parallelization strategy discovered by Unity, I met 'illegal memory access'
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/77946882/201331456-9a496547-40e1-472c-be20-54afdef0d441.png">
* When running BERT with data parallelism, flexflow successfully discovered the strategy but failed when initializing the operator.
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/77946882/201332150-883fb644-2357-4bb1-b8b7-474840a4412d.png">

* I built the flexflow on commit https://github.com/flexflow/FlexFlow/commit/1207e2f6

**Comment by lockshaw** [comment]
@jiazhihao What's the status on this?

**Comment by lockshaw** [comment]
Closing, as according to @jiazhihao:

> I think this issue should have been resolved

If anyone still runs into this error, feel free to reopen or comment on this issue.
