### ISSUE TITLE
[MT5] - Occasional `Realm` assertion error

### ISSUE THREAD

**Issue by gabrieleoliaro** [flexflow/FlexFlow#340]
When running the MT5 model with the following command: `flexflow_python examples/python/pytorch/mt5/mt5_ff.py -ll:py 1 -ll:gpu 1 -ll:fsize 14000 -ll:zsize 4096 --simulator-workspace-size 7057475584` I sometimes get the `Realm` assertion error below:

```bash
flexflow_python: /usr/FlexFlow/deps/legion/runtime/realm/mutex.cc:320: uint32_t Realm::Doorbell::wait_slow(): Assertion `errno == EAGAIN' failed.
Aborted (core dumped)
```

Full output:
<details>
<summary>Toggle here </summary>
<br>

root@050487f4cf2e:/usr/FlexFlow# flexflow_python examples/python/pytorch/mt5/mt5_ff.py -ll:py 1 -ll:gpu 1 -ll:fsize 14000 -ll:zsize 4096 --simulator-workspace-size 7057475584
[0 - 7fc0212fd700]    0.383959 {3}{Mapper}: Enabled Control Replication Optimizations.
[0 - 7fc0212fd700]    0.384057 {3}{Mapper}: Enabled Control Replication Optimizations.
[0 - 7fc0212fd700]    0.384090 {3}{Mapper}: Enabled Control Replication Optimizations.
Using cffi flexflow bindings.
Using flexflow python
start top-level task
top-level task
workSpaceSize (1024 MB)
Downloading: 100%|████████████████████████████████████████████████████████████████| 553/553 [00:00<00:00, 414kB/s]
Downloading:  50%|██████████████████████████████▏                             | 577M/1.12G [00:10<00:10, 54.9MB/s]flexflow_python: /usr/FlexFlow/deps/legion/runtime/realm/mutex.cc:320: uint32_t Realm::Doorbell::wait_slow(): Assertion `errno == EAGAIN' failed.
Aborted (core dumped)

</details>

**Comment by lockshaw** [comment]
@jiazhihao Any thoughts on this?

**Comment by lockshaw** [comment]
@tnoyola

**Comment by lockshaw** [comment]
@jiazhihao Should this still be open? What's the status of this?

**Comment by lockshaw** [comment]
According to @jiazhihao,

> This is a Realm issue (not a FlexFlow one). I don’t think we have seen this recently (the Legion team might have fixed the issue already)

If anyone else runs into this issue and is able to replicate it, feel free to reopen this issue.
