### ISSUE TITLE
Support gather operation

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#343]
A new op should be created to support https://pytorch.org/docs/stable/generated/torch.gather.html.

**Comment by lockshaw** [comment]
@jiazhihao temporarily assigning to you, but feel free to re-assign it if you delegate it to a student :slightly_smiling_face:

**Comment by lockshaw** [comment]
@soumyac1999

**Comment by soumyac1999** [comment]
Not blocking at the moment since I am currently working on the baseline. However, will need `gather` for the GNN model.

**Comment by lockshaw** [comment]
>  It seems that PyTorch and TF offer different semantics for gather . Our principle is to align FF with PyTorch. Do you think the PyTorch’s gather (https://pytorch.org/docs/stable/generated/torch.gather.html) will work? -Zhihao

@soumyac1999 Thoughts?

**Comment by lockshaw** [comment]
@soumyac1999 Did you ever figure out the answer to this?

**Comment by soumyac1999** [comment]
PyTorch's gather should work with some manipulation of the indexing.
