### ISSUE TITLE
Add 3-dimensional tensor support

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#348]
Currently some parts of FlexFlow don't support 3-dimensional tensors. For example: 

- https://github.com/flexflow/FlexFlow/blob/master/python/flexflow/keras/models/tensor.py#L100
- https://github.com/flexflow/FlexFlow/blob/master/src/ops/flat.cc#L23

These should be fixed. Depending on how many components need to be fixed this may be split into multiple issues.

**Comment by soumyac1999** [comment]
Turns out we do support 3d tensors at places. It was a Keras/Python check which needed to be removed (done in #603).
