### ISSUE TITLE
How to train a model with multiple nodes in a cluster?

### ISSUE THREAD

**Issue by gudiandian** [flexflow/FlexFlow#35]
Hi. I wish to use FlexFlow to train a model with multiple nodes in a cluster. 

According to [your paper](https://cs.stanford.edu/~zhihao/papers/sysml19a.pdf), FlexFlow should support training with more than one node and each node has multiple GPUs in clusters. However, there is no documentation mentioning how to run FlexFlow training on multiple nodes. 

Should there be more than one training process in this case? Or does FlexFlow only support training with multiple GPUs on one node currently? Thanks!

**Comment by JiatianWu** [comment]
same here

**Comment by jiazhihao** [comment]
@MonicaGu @JiatianWu Thanks a lot for your interests in FlexFlow. FlexFlow supports distributed training across multiple nodes as described in the paper. FlexFlow uses GASNet for communications and data transfers across nodes. See [instructions](http://legion.stanford.edu/gasnet) to install GASNet. After successfully installing GASNet, you will need to rebuild FlexFlow by setting `USE_GASNET` to 1 (see https://github.com/flexflow/FlexFlow/blob/master/examples/AlexNet/Makefile#L35). 

[This is an example script](https://github.com/flexflow/FlexFlow/blob/master/examples/DLRM/run_summit.sh) for launching distributed runs after you have rebuilt FlexFlow w/ GASNet enabled.

**Comment by roman955b** [comment]
Should GASNet be installed on each of the nodes in the cluster or is it enough that each of the docker's running FF also has GASNet installed within them?
Can I use FF with GASNet on AWS (not bare metal services)?

**Comment by eddy16112** [comment]
> Should GASNet be installed on each of the nodes in the cluster or is it enough that each of the docker's running FF also has GASNet installed within them?
> Can I use FF with GASNet on AWS (not bare metal services)?

You will need to install the GASNet anywhere you want to run the FlexFlow. You can use FF with GASNet on AWS, but make sure you select the high performance conduit for GASNet if you want to measure the performance.

**Comment by roman955b** [comment]
So I understand that it is not enough to have GASNet installed on the dockers that I run on my cluster, but I must ask the IT-admin to also install GASNet on the actual nodes of the cluster. Is this correct? (if yes, I think we can close this git issue).
Thanks
