### ISSUE TITLE
`Realm::Cuda::GPUStream::reap_events(Realm::TimeLimit)` assertion error 

### ISSUE THREAD

**Issue by gabrieleoliaro** [flexflow/FlexFlow#369]
When I run the `examples/python/onnx/cifar10_cnn.py` example as part of the `test.sh` script, I get the error below:

```bash
[0 - 7f5513c84700]   13.531413 {6}{gpu}: CUDA error reported on GPU 0: device-side assert triggered (CUDA_ERROR_ASSERT)
flexflow_python: /usr/FlexFlow/deps/legion/runtime/realm/cuda/cuda_module.cc:329: bool Realm::Cuda::GPUStream::reap_events(Realm::TimeLimit): Assertion `0' failed.
./test.sh: line 35: 185378 Aborted                 (core dumped) ./flexflow_python $FF_HOME/examples/python/onnx/cifar10_cnn.py -ll:py 1 -ll:gpu $GPUS -ll:fsize $LEGION_FSIZE_SMALL -ll:zsize $LEGION_ZSIZE --epochs 40 --test_type 1
```

**Comment by jiazhihao** [comment]
@gabrieleoliaro How many GPUs did you use for this run? Would be great if you can rerun the scratch with `--only-data-parallel` and see if you still observe the same issue.

**Comment by lockshaw** [comment]
@jiazhihao @gabrieleoliaro What's the status of this?

**Comment by eddy16112** [comment]
I guess this is because we use the control replication branch, not the flexflow branch? The flexflow banch only has one cuda stream.

**Comment by lockshaw** [comment]
@eddy16112 So does that mean this is fixed? I don't fully understand what you were trying to say--isn't the flexflow branch based on control replication?

**Comment by eddy16112** [comment]
There was a problem when we use multiple cuda streams to launch flexflow cuda kernels, so in the flexflow branch, we limit the number of streams to 1.

**Comment by lockshaw** [comment]
@eddy16112 Okay, I'll mark this as fixed then.

**Comment by Resurgence27** [comment]
> There was a problem when we use multiple cuda streams to launch flexflow cuda kernels, so in the flexflow branch, we limit the number of streams to 1.

@eddy16112， so could you give the resolution on how to solve this for multiple cuda streams?
