### ISSUE TITLE
Support generic data types in OpMeta

### ISSUE THREAD

**Issue by jiazhihao** [flexflow/FlexFlow#380]
FlexFlow currently assumes that the input/output tensors of some operators are 32-bit floating points. This issues tracks the progress of supporting general data types for FlexFlow's operators. The list of todos:

- [ ] Add input/output/weight data type as properties in `OpMeta`. This allows forward/backward tasks to know the data types of the input/weight/output tensors
- [ ] Use GenericTensorAccessor in forward/backward tasks

**Comment by lockshaw** [comment]
@jiazhihao The instructions above are out of date, especially after #622. Can you convert this into a list of which operators to which we still want to add multi-precision support?

**Comment by lockshaw** [comment]
Actually, let's move the list over to #408
