### ISSUE TITLE
Import pytorch models without requiring use of the native python interpreter

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#382]
As mentioned in the FF C++/Python bindings meeting, currently we can't import pytorch in `flexflow_python`, so a separate step must be performed to first export the torch fx representation to a file before the model can be trained. This issue looks into developing possible workarounds for this, either on the FF side or the Legion side. 

@eddy16112

**Comment by lockshaw** [comment]
@eddy16112 @gabrieleoliaro Status of this?

**Comment by eddy16112** [comment]
After we disable the cuda hijack (currently blocked by https://gitlab.com/StanfordLegion/legion/-/merge_requests/788), we should be able to import PyTorch directly.

**Comment by lockshaw** [comment]
> After we disable the cuda hijack (currently blocked by https://gitlab.com/StanfordLegion/legion/-/merge_requests/788), we should be able to import PyTorch directly.

Great, added the cuda hijack branch to this issue so when it's merged this issue should autoclose.
