### ISSUE TITLE
Supporting both cffi and pybind

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#383]
Currently there are two separate backends for the FF python bindings, one using `cffi` and one using `pybind`. The goal of this issue is to discuss whether or not we want to remove one of these backends to reduce unnecesary code to maintain. 

@eddy16112 @jiazhihao

**Comment by jiazhihao** [comment]
I think we should focus on enhancing the support for one python binding, instead of dividing the effort equally into the two. My impression is that the current pybind support is not up-to-date, and in Unity we have been using the cffi approach.

**Comment by lockshaw** [comment]
@eddy16112 @williamberman @gabrieleoliaro Any thoughts on this? I mainly want to make sure there arent any super-compelling reasons to use pybind before we remove it

**Comment by williamberman** [comment]
no strong opinions as not terribly familiar with tradeoffs in this case

**Comment by lockshaw** [comment]
Decision made: only supporting cffi

**Comment by lockshaw** [comment]
@eddy16112 @gabrieleoliaro Do we have an issue created for removing the pybind support? If not can one of you create it? I'm closing this issue for now as the decision has been made.
