### ISSUE TITLE
master分支编译出错

### ISSUE THREAD

**Issue by liqing9399** [flexflow/FlexFlow#401]
master分支编译出错。错误如下：

git submodule update 报错：
tao.li@BJSW-S03:~/workspace/FlexFlow/build$ git submodule update
fatal: remote error: upload-pack: not our ref 48da4329083209f7f7e0ba1dbcb0a9b633e823fb
Fetched in submodule path '../deps/legion', but it did not contain 48da4329083209f7f7e0ba1dbcb0a9b633e823fb. Direct fetching of that commit failed.

使用master 分支 legion编译时，同样编译出错：
In file included from /home/tao.li/workspace/FlexFlow/deps/legion/runtime/legion/legion_types.h:39:0,
                 from /home/tao.li/workspace/FlexFlow/deps/legion/runtime/legion.h:56,
                 from /home/tao.li/workspace/FlexFlow/include/flexflow/accessor.h:4,
                 from /home/tao.li/workspace/FlexFlow/include/flexflow/model.h:17,
                 from /home/tao.li/workspace/FlexFlow/src/runtime/model.cc:16:
/home/tao.li/workspace/FlexFlow/deps/legion/runtime/legion/legion.inl: In instantiation of ‘static void Legion::LegionTaskWrapper::legion_task_wrapper(const void*, size_t, const void*, size_t, Legion::Processor) [with T = FlexFlow::PCG::GraphOptimalViewSerialized; T (* TASK_PTR)(const Legion::Task*, const std::vector<Legion::PhysicalRegion>&, Legion::Context, Legion::Runtime*) = FlexFlow::PCG::Graph::graph_optimize_task; size_t = long unsigned int; Legion::Processor = Realm::Processor]’:
/home/tao.li/workspace/FlexFlow/deps/legion/runtime/legion/legion.inl:21770:22:   required from ‘static Legion::VariantID Legion::Runtime::preregister_task_variant(const Legion::TaskVariantRegistrar&, const char*, Legion::VariantID) [with T = FlexFlow::PCG::GraphOptimalViewSerialized; T (* TASK_PTR)(const Legion::Task*, const std::vector<Legion::PhysicalRegion>&, Legion::Context, Legion::Runtime*) = FlexFlow::PCG::Graph::graph_optimize_task; Legion::VariantID = unsigned int]’
/home/tao.li/workspace/FlexFlow/src/runtime/model.cc:4403:41:   required from here
/home/tao.li/workspace/FlexFlow/deps/legion/runtime/legion/legion_template_help.h:28:3: error: static assertion failed: Task return values must be less than or equal to LEGION_MAX_RETURN_SIZE bytes
   static_assert(condition, message)
   ^
/home/tao.li/workspace/FlexFlow/deps/legion/runtime/legion/legion.inl:21585:7: note: in expansion of macro ‘LEGION_STATIC_ASSERT’
       LEGION_STATIC_ASSERT(sizeof(T) <= LEGION_MAX_RETURN_SIZE,
       ^~~~~~~~~~~~~~~~~~~~
CMakeFiles/flexflow.dir/build.make:971: recipe for target 'CMakeFiles/flexflow.dir/src/runtime/model.cc.o' failed
make[2]: *** [CMakeFiles/flexflow.dir/src/runtime/model.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:365: recipe for target 'CMakeFiles/flexflow.dir/all' failed
make[1]: *** [CMakeFiles/flexflow.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lockshaw** [comment]
Looks like something is wrong with your git submodule of legion? I can't replicate the issue locally, that commit appears to exist in the Legion remote at https://gitlab.com/StanfordLegion/legion.git. Is it possible that there is some network configuration that's not letting you access gitlab?

**Comment by liqing9399** [comment]
The problem may be that the repositories don't match. I'm using https://github.com/StanfordLegion/legion。Could it be that gitlab and github are not the same

**Comment by eddy16112** [comment]
You should use this branch https://gitlab.com/StanfordLegion/legion/-/commits/flexflow

**Comment by liqing9399** [comment]
I finished compiling using the master branch of legion. Do I need to change to the flexflex branch?

**Comment by eddy16112** [comment]
If you need to run with multiple nodes, then yes, otherwise, master branch should be fine.

**Comment by liqing9399** [comment]
> If you need to run with multiple nodes, then yes, otherwise, master branch should be fine.

ok，thanks
