### ISSUE TITLE
`set_tensor` on a newly created tensor

### ISSUE THREAD

**Issue by soumyac1999** [flexflow/FlexFlow#414]
Calling `set_tensor` on a tensor created using `create_tensor` fails.

**Code to Reproduce** (similar to https://github.com/flexflow/FlexFlow/blob/master/examples/python/native/bert_proxy_native.py#L91):
```python
import flexflow.core as ff
import numpy as np

def top_level_task():
    ffconfig = ff.FFConfig()
    ffmodel = ff.FFModel(ffconfig)

    dims_input = [ffconfig.batch_size, 10]    
    input_tensor = ffmodel.create_tensor(dims_input, DataType.DT_FLOAT)
    np_input_tensor = np.zeros(dims_input, dtype=np.float32)
    input_tensor.set_tensor(ffmodel, np_input_tensor)

if __name__ == "__main__":
  top_level_task()
```
**Command**: `flexflow_python set_tensor.py -ll:py 1 -ll:gpu 1 -ll:fsize 8192 -ll:zsize 12192`

**Error**:
```
flexflow_python: /home/soumya/flexflow/src/runtime/model.cc:1656: bool FlexFlow::FFModel::get_parallel_tensor_from_tensor(FlexFlow::Tensor, FlexFlow::ParallelTensorBase*&) const: Assertion `false' failed.
```
https://github.com/flexflow/FlexFlow/blob/3652efb8916ccc8605402a8c38c4c513220fe903/src/runtime/model.cc#L1656

**Question**: Is this the correct way to use `set_tensor`? Do I need to pass some additional flags to get this to work (the BERT example had a bunch of other flags)?

**Comment by lockshaw** [comment]
@jiazhihao Forwarding to you as it appears runtime-related

Maybe related to #344 ?

**Comment by lockshaw** [comment]
@soumyac1999 What's the priority of this--blocking or more of a nice-to-have?

**Comment by soumyac1999** [comment]
This is not blocking at the moment. (Will be adding priority in future issues)

**Comment by lockshaw** [comment]
This is the same issue as #344, so I'll close this one and we can move discussion and prioritization over to there.
