### ISSUE TITLE
Add tests for changes in #415

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#418]
Not urgent, but we should start to figure out how to add tests for the python frontend. I know there's currently the pytorch alignment tests, but I'm not sure about its current status or if it would have caught the bug in #282 (@jiazhihao any thoughts?).

**Comment by jiazhihao** [comment]
We currently use [this script](https://github.com/flexflow/FlexFlow/blob/master/tests/multi_gpu_tests.sh) for testing the Python frontend, which only examines the basic functionality of the frontend. We will need to find a way to design more systematic python testing. Any suggestions from the community would be welcomed.

**Comment by lockshaw** [comment]
@williamberman @gabrieleoliaro Thoughts on this issue? I'd like to start moving toward having more thorough (or any :slightly_smiling_face:) tests, but I think we need to figure out what form they're going to take. 

This should probably also take into account the pytorch-alignment discussions in #353 and #362

**Comment by williamberman** [comment]
I'm focussed more on getting up to speed on operator substitution generation at the moment

**Comment by lockshaw** [comment]
We'll keep this issue around to focus on tests for #415, but move the broader discussion over to #431

**Comment by lockshaw** [comment]
Closed in favor of #769.
