### ISSUE TITLE
Add sin and cos operators

### ISSUE THREAD

**Issue by soumyac1999** [flexflow/FlexFlow#462]
#365

**Comment by lockshaw** [comment]
@soumyac1999 This issue should be pretty straightforward, do you want to try implementing it yourself to get some experience? `sin` and `cos` can be added to `ElementUnary` (take a look at https://github.com/flexflow/FlexFlow/blob/master/src/ops/element_unary.cu#L55-L99 and https://github.com/flexflow/FlexFlow/blob/master/src/ops/element_unary.cu#L159-L216). You'll also need to append a new `OperatorType` in https://github.com/flexflow/FlexFlow/blob/master/include/flexflow/ffconst.h#L61-L152, and then just update pretty much any place that references `OP_RELU` to also include `OP_SIN` and `OP_COS` (for example, https://github.com/flexflow/FlexFlow/blob/master/src/runtime/operator_params.cc#L52). Does that seem doable? Happy to answer any questions if you have any, but this seems like a good opportunity to start getting more familiarity with the C++ layer.

**Comment by lockshaw** [comment]
Also @soumyac1999 can you assign a priority?
