### ISSUE TITLE
cant make python api

### ISSUE THREAD

**Issue by bhetherman** [flexflow/FlexFlow#49]
Following the directions on the installation page results in the following error:

Makefile:76: cannot find libpython3.6*.so - falling back to using LD_LIBRARY_PATH
/home/acc/FlexFlow/legion/runtime//runtime.mk:345: cannot find libpython3.6*.so - falling back to using LD_LIBRARY_PATH
/home/acc/FlexFlow/protobuf/bin/protoc --proto_path=/home/acc/FlexFlow/src/runtime strategy.proto --cpp_out=.
make: /home/acc/FlexFlow/protobuf/bin/protoc: Command not found
Makefile:148: recipe for target 'strategy.pb.cc' failed
make: *** [strategy.pb.cc] Error 127

Any thoughts?

ps libpython3.6-stdlib is installed in the normal location so idk why it cant find it.

**Comment by eddy16112** [comment]
I guess you may need libpython-dev, but 
First, check if you have libpython3.6.so in the folders of your LD_LIBRARY_PATH 
Second, you can also try to export the following variables
export PYTHON_EXE=python3.6
export PYTHON_LIB=/usr/lib64/libpython3.6m.so.1.0 // change it to the path of your libpython 
export PYTHON_VERSION_MAJOR=3

**Comment by bhetherman** [comment]
libpython3.6.so was not in LD_LIBRARY_PATH so I added it. That lead to a whole bunch of c++ compile errors:

`make
/usr/bin/python /opt/FlexFlow/legion/runtime/../tools/generate_defines.py  -DLEGION_USE_CUDA -DLEGION_GPU_REDUCTIONS -DLEGION_USE_ZLIB -DLEGION_MAX_DIM=4               -c -i /opt/FlexFlow/legion/runtime/../cmake/legion_defines.h.in -o /home/acc/FlexFlow/python/legion_defines.h
/usr/bin/python /opt/FlexFlow/legion/runtime/../tools/generate_defines.py  -DREALM_USE_LIBDL -DREALM_PYTHON_LIB="\"/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1\"" -DREALM_PYTHON_VERSION_MAJOR=3 -DREALM_USE_PYTHON -DREALM_USE_CUDA -DREALM_USE_CUDART_HIJACK -DREALM_MAX_DIM=4               -DCOMPILE_TIME_MIN_LEVEL=LEVEL_DEBUG   -c -i /opt/FlexFlow/legion/runtime/../cmake/realm_defines.h.in -o /home/acc/FlexFlow/python/realm_defines.h
g++ -o main.cc.o -c main.cc -DBINDINGS_AUGMENT_PYTHONPATH -DFF_USE_PYTHON -std=c++11 -DLEGION_REDOP_COMPLEX   -march=native -DUSE_CUDA -O2 -fno-strict-aliasing  -Wall -Wno-strict-overflow -I/opt/FlexFlow/include -I/opt/FlexFlow/protobuf/src -I/include -I/include -I/home/acc/FlexFlow/python -I/opt/FlexFlow/legion/runtime -I/opt/FlexFlow/legion/runtime/mappers -I/usr/local/cuda/include -I/opt/FlexFlow/legion/runtime/realm/transfer 
g++ -o flexflow_c.cc.o -c flexflow_c.cc -DBINDINGS_AUGMENT_PYTHONPATH -DFF_USE_PYTHON -std=c++11 -DLEGION_REDOP_COMPLEX   -march=native -DUSE_CUDA -O2 -fno-strict-aliasing  -Wall -Wno-strict-overflow -I/opt/FlexFlow/include -I/opt/FlexFlow/protobuf/src -I/include -I/include -I/home/acc/FlexFlow/python -I/opt/FlexFlow/legion/runtime -I/opt/FlexFlow/legion/runtime/mappers -I/usr/local/cuda/include -I/opt/FlexFlow/legion/runtime/realm/transfer 
flexflow_c.cc: In function 'void flexflow_model_compute_metrics(flexflow_model_t)':
flexflow_c.cc:212:11: error: 'class FFModel' has no member named 'compute_metrics'; did you mean 'reset_metrics'?
   handle->compute_metrics();
           ^~~~~~~~~~~~~~~
           reset_metrics
flexflow_c.cc: In function 'flexflow_tensor_t flexflow_model_add_conv2d(flexflow_model_t, flexflow_tensor_t, int, int, int, int, int, int, int, ActiMode, bool, flexflow_op_t, flexflow_initializer_t, flexflow_initializer_t)':
flexflow_c.cc:348:181: error: no matching function for call to 'FFModel::conv2d(const Tensor&, int&, int&, int&, int&, int&, int&, int&, ActiMode&, bool&, Op*&, Initializer*&, Initializer*&)'
 t, out_channels, kernel_h, kernel_w, stride_h, stride_w, padding_h, padding_w, activation, use_bias, shared_op, kernel_initializer, bias_initializer);
                                                                                                                                                     ^
In file included from flexflow_dataloader.h:19:0,
                 from flexflow_c.cc:16:
/opt/FlexFlow/include/model.h:264:10: note: candidate: Tensor FFModel::conv2d(const Tensor&, int, int, int, int, int, int, int, ActiMode, bool, Initializer*, Initializer*)
   Tensor conv2d(const Tensor& input,
          ^~~~~~
/opt/FlexFlow/include/model.h:264:10: note:   candidate expects 12 arguments, 13 provided
/opt/FlexFlow/include/model.h:329:11: note: candidate: Conv2D* FFModel::conv2d(int, int, int, int, int, int, int, int, ActiMode, bool, Initializer*, Initializer*)
   Conv2D* conv2d(int inChannels,
           ^~~~~~
/opt/FlexFlow/include/model.h:329:11: note:   candidate expects 12 arguments, 13 provided
flexflow_c.cc: In function 'flexflow_tensor_t flexflow_model_add_embedding(flexflow_model_t, flexflow_tensor_t, int, int, AggrMode, flexflow_op_t, flexflow_initializer_t)':
flexflow_c.cc:390:96: error: no matching function for call to 'FFModel::embedding(const Tensor&, int&, int&, AggrMode&, Op*&, Initializer*&)'
   *tensor = handle->embedding(*input, num_entires, out_dim, aggr, shared_op, kernel_initializer);
                                                                                                ^
In file included from flexflow_dataloader.h:19:0,
                 from flexflow_c.cc:16:
/opt/FlexFlow/include/model.h:278:10: note: candidate: Tensor FFModel::embedding(const Tensor&, int, int, AggrMode, Initializer*)
   Tensor embedding(const Tensor& input,
          ^~~~~~~~~
/opt/FlexFlow/include/model.h:278:10: note:   candidate expects 5 arguments, 6 provided
/opt/FlexFlow/include/model.h:338:14: note: candidate: Embedding* FFModel::embedding(int, int, AggrMode, Initializer*)
   Embedding* embedding(int num_entires, int outDim,
              ^~~~~~~~~
/opt/FlexFlow/include/model.h:338:14: note:   candidate expects 4 arguments, 6 provided
flexflow_c.cc: In function 'flexflow_tensor_t flexflow_model_add_batch_matmul(flexflow_model_t, flexflow_tensor_t, flexflow_tensor_t)':
flexflow_c.cc:453:21: error: 'class FFModel' has no member named 'batch_matmul'; did you mean 'batch_norm'?
   *tensor = handle->batch_matmul(*a, *b);
                     ^~~~~~~~~~~~
                     batch_norm
flexflow_c.cc: In function 'flexflow_tensor_t flexflow_model_add_dense(flexflow_model_t, flexflow_tensor_t, int, ActiMode, bool, flexflow_op_t, flexflow_initializer_t, flexflow_initializer_t)':
flexflow_c.cc:475:113: error: no matching function for call to 'FFModel::dense(const Tensor&, int&, ActiMode&, bool&, Op*&, Initializer*&, Initializer*&)'
   *tensor = handle->dense(*input, out_dim, activation, use_bias, shared_op, kernel_initializer, bias_initializer);
                                                                                                                 ^
In file included from flexflow_dataloader.h:19:0,
                 from flexflow_c.cc:16:
/opt/FlexFlow/include/model.h:293:10: note: candidate: Tensor FFModel::dense(const Tensor&, int, ActiMode, bool, Initializer*, Initializer*)
   Tensor dense(const Tensor& input,
          ^~~~~
/opt/FlexFlow/include/model.h:293:10: note:   candidate expects 6 arguments, 7 provided
/opt/FlexFlow/include/model.h:346:11: note: candidate: Linear* FFModel::dense(int, int, ActiMode, bool, Initializer*, Initializer*)
   Linear* dense(int inDim, int outDim,
           ^~~~~
/opt/FlexFlow/include/model.h:346:11: note:   candidate expects 6 arguments, 7 provided
flexflow_c.cc: In function 'void flexflow_model_add_split(flexflow_model_t, flexflow_tensor_t, int, flexflow_tensor_t*, int*, int)':
flexflow_c.cc:541:11: error: 'class FFModel' has no member named 'split'
   handle->split(*input, outputs, split_vec, axis);
           ^~~~~
flexflow_c.cc: In function 'flexflow_tensor_t flexflow_model_add_transpose(flexflow_model_t, flexflow_tensor_t, int, int*)':
flexflow_c.cc:598:21: error: 'class FFModel' has no member named 'transpose'
   *tensor = handle->transpose(*input, perm_vec);
                     ^~~~~~~~~
flexflow_c.cc: In function 'flexflow_tensor_t flexflow_model_add_reverse(flexflow_model_t, flexflow_tensor_t, int)':
flexflow_c.cc:612:21: error: 'class FFModel' has no member named 'reverse'
   *tensor = handle->reverse(*input, axis);
                     ^~~~~~~
flexflow_c.cc: In function 'void flexflow_sgd_optimizer_destroy(flexflow_sgd_optimizer_t)':
flexflow_c.cc:959:10: warning: deleting object of polymorphic class type 'SGDOptimizer' which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
   delete handle;
          ^~~~~~
flexflow_c.cc: In function 'void flexflow_adam_optimizer_destroy(flexflow_adam_optimizer_t)':
flexflow_c.cc:996:10: warning: deleting object of polymorphic class type 'AdamOptimizer' which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
   delete handle;
          ^~~~~~
/opt/FlexFlow/legion/runtime/runtime.mk:1039: recipe for target 'flexflow_c.cc.o' failed
make: *** [flexflow_c.cc.o] Error 1`

**Comment by eddy16112** [comment]
Looks like you can using two different versions of FlexFlow
I/opt/FlexFlow/include -I/opt/FlexFlow/protobuf/src -I/include -I/include -I/home/acc/FlexFlow/python

**Comment by bhetherman** [comment]
thanks for finding that. fixed that and fixed another protobuf issue and it built
