### ISSUE TITLE
Exceeding the FF buffer size when running mt5_ff.py with BERT

### ISSUE THREAD

**Issue by tnoyola** [flexflow/FlexFlow#490]
The following error is occurring when I run `mt5_ff.py` with BERT instead of MT5.
![1](https://user-images.githubusercontent.com/58843962/203187294-0682906c-eeea-44fb-b722-d75ff8d59a59.png)

**Comment by lockshaw** [comment]
Potentially linked to #417?

**Comment by lockshaw** [comment]
Tentatively assigning to @jiazhihao as he likely has more experience with this code. @jiazhihao feel free to correct me if this is wrong or transfer to someone else :slightly_smiling_face:

**Comment by tnoyola** [comment]
Resolved this issue by enlarging the buffer size [here](https://github.com/flexflow/FlexFlow/blob/master/include/flexflow/graph.h#L88) (multiplied LEGION_MAX_RETURN_SIZE by 4)
