### ISSUE TITLE
CUDNN failure: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by Tron-x** [flexflow/FlexFlow#51]
hi , when i run the dlrm case, after complie, i execute "./dlrm -ll:gpu 2 -ll:cpu 4 -ll:fsize 10000 -ll:zsize 9000 -ll:util 2 --arch-sparse-feature-size 64 --arch-embedding-size 1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --arch-mlp-bot 64-512-512-64 --arch-mlp-top 576-1024-1024-1024-1 --epochs 20 --batch-size 64 -dm:memoize --strategy ../../../src/runtime/dlrm_strategy_gpu_2_node_1.pb"

i got the CUDNN failure: CUDNN_STATUS_NOT_INITIALIZED erro
![image](https://user-images.githubusercontent.com/7659413/95723167-6b0cba00-0ca7-11eb-999b-b3fec3c1f679.png)

I don't know where the problem is. It seems to be a memory problem

device info:  two 2080ti with 11G  gpu memory

**Comment by jiazhihao** [comment]
A common cause of this failure is out-of-memory when initializing the cuDNN runtime. Can you change the `-ll:fsize 10000` to `-ll:fsize 9000` and give it another try. Currently, the cudnn work space (1GB by default) is not managed by FlexFlow. When FlexFlow allocated 10GB of device memory, it seems the cuDNN runtime cannot successfully allocate the remaining 1GB.

**Comment by Tron-x** [comment]
Thank you, but then I ran into another problem. I'm not familiar with this code, so I still don't know how to solve it.
![image](https://user-images.githubusercontent.com/7659413/95815097-926a9200-0d4e-11eb-90f9-67fdb1113c28.png)

In addition, when I was learning code, I did not understand from the code level when the simulator and MCMC sampling were used, such as under the runtime folder simulator.cc  It seems to be using simulation, but it seems that there is no simulator used in other places. In general, can you tell us from the code level simply how to find the optimal parallel strategy when training a network? thanks~
