### ISSUE TITLE
Run  dlrm case erro

### ISSUE THREAD

**Issue by Tron-x** [flexflow/FlexFlow#52]
when i run the dlrm case, i encounter another problem. I'm not familiar with this code now, so I still don't know how to solve it.
![image](https://user-images.githubusercontent.com/7659413/96413149-cc8bd600-121d-11eb-81fc-8a2c81d65a16.png)
In addition, when I was learning code, I did not understand from the code level when the simulator and MCMC sampling were used, such as under the runtime folder simulator.cc It seems to be using simulation. In general, can you tell us from the code level simply how to find the optimal parallel strategy when training a network? thanks~

**Comment by jiazhihao** [comment]
Can you show us the command line you used to launch DLRM? It seems like you forgot the set GPU flags (e.g., `-ll:gpu`, `-ll:zsize`). This might be a useful blog post that describes how to use the optimizer: https://flexflow.ai/search/

**Comment by Tron-x** [comment]
command line is:
./dlrm -ll:gpu 2 -ll:cpu 4 -ll:fsize 8000 -ll:zsize 20000 -ll:util 2 --arch-sparse-feature-size 64 --arch-embedding-size 1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --arch-mlp-bot 64-512-512-64 --arch-mlp-top 576-1024-1024-1024-1 --epochs 20 --batch-size 128 -dm:memoize --strategy ../../../src/runtime/dlrm_strategy_gpu_2_node_1.pb
