### ISSUE TITLE
Cant add batch_norm to cpp ResNet model

### ISSUE THREAD

**Issue by bhetherman** [flexflow/FlexFlow#53]
When I add a batch_norm layer to the ResNet model (see code below) I get a runtime error. There are no errors during compilation, just when I try to run but I'm not sure how to fix it based on the error message.

Starting at line 92 in function top_level_task of resnet.cc: 

`  // Add layers`
`  Tensor t = input;`
`  t = ff.conv2d(input, 64, 7, 7, 2, 2, 3, 3);`
`  t = ff.batch_norm(t, false); //I added this line which should be batch_norm and no relu?`
`  t = ff.pool2d(t, 3, 3, 2, 2, 1, 1);`

This results in the following output/error:

root@46083842-0c93-44ec-9c8b-fd074d7b4ee2-77f877845f-g2r6d:/home/acc/FlexFlow# ./examples/cpp/ResNet/resnet -ll:gpu 2 --epochs 1 -ll:fsize 24000 -ll:zsize 8000 --search-budget 2000
[0 - 7fbaf9502fc0]    4.586106 {3}{Mapper}: No strategy file provided. Use default data parallelism.
[0 - 7fbaf9502fc0]    4.586708 {3}{ResNet}: batchSize(64) workersPerNodes(2) numNodes(1)
workSpaceSize (1024 MB)
workSpaceSize (1024 MB)
resnet: /home/acc/FlexFlow/legion/runtime/realm/dynamic_templates.inl:199: static void Realm::DynamicTemplates::IntList<MIN, MAX>::DemuxHelper<TARGET, MAX>::demux(int, T1, T2) [with T1 = unsigned int; T2 = int*; TARGET = Realm::DynamicTemplates::ListProduct2<Realm::DynamicTemplates::IntList<1, 4>, Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long int, Realm::DynamicTemplates::TypeListTerm> > > >::DemuxHelper1<Legion::Internal::NT_TemplateHelper::DimHelper>; int MIN = 1; int MAX = 4]: Assertion `index == MAX' failed.
Aborted (core dumped)

It runs through the MCMC strategy search without the batch_norm layer.

Thanks for the help.

**Comment by jiazhihao** [comment]
Hi @bhetherman, the issue should have been fixed by commit 31fd3d3bf6.

**Comment by bhetherman** [comment]
Thanks @jiazhihao that fixed the issue
