### ISSUE TITLE
Potential Features

### ISSUE THREAD

**Issue by jiazhihao** [flexflow/FlexFlow#54]
Here is a list of feature requests discussed during the FlexFlow office hour on Oct 22.

- [ ] Include additional information in strategy configurations, such as the DNN model architecture and machine topology information.
- [ ] Enable a way to simulate hardware that are not accessible
- [ ] Enhance GPU-DRAM or GPU Direct support
- [ ] Plan to support multi-stream optimizations

**Comment by sgh7398** [comment]
Has there been any progress on these features? I am very interested about the second item "Enable a way to simulate hardware that are not accessible". Has this new feature been added to FlexFlow? If not, Could you please give a high level idea on how it can be done?
