### ISSUE TITLE
Running on multiple nodes using GASNet UDP conduit

### ISSUE THREAD

**Issue by ainarain-pl** [flexflow/FlexFlow#58]
Hi,

So I have two connected nodes, both of which have Flexflow and GASNet installed. I setup GASNet and AlexNet on both nodes the following way.

GASNet:

1. Navigate to the directory where gasnet is installed.
2. Run `./configure --enable-segment-fast --disable-pshm --with-max-segsize=16GB --disable-seq --disable-parsync --enable-udp --enable-mpi-compat --disable-mpi --disable-aligned-segments --disable-ibv`
3. Run `CXXFLAGS=-fPIC make -e CONDUIT=udp`
4. Run `make install`

AlexNet:

`USE_GASNET=1 LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial <path_to_FlexFlow>/ffcompile.sh <path_to_FlexFlow>/examples/cpp/AlexNet`

UDP conduit:

1. Setup a passwordless ssh connection between the two nodes using ssh-copy-id.
2. Suppose we want to run FlexFlow on remote node **a** from local node **b**.
3. Set the following environment variables:
        GASNET_SPAWNFN='S'
        SSH_CMD='ssh'
        SSH_SERVERS='username@<node_a_ip_address>'
        In my case, I had to set SSH_OPTIONS='-p 2222' since we are port forwarding a 
        container's ssh port.

To run AlexNet: 

`<path_to_executable>/alexnet 1 <FlexFlow_command_line_arguments>`.

The parameters 1 indicates we are running on one remote node.  

When I try this, I get the following error:

```
*** GASNET WARNING: int AMUDP_SPMDStartup_AMUDP_NDEBUG(int*, char***, int, int, amudp_spawnfn_t, uint64_t*, amudp_eb**, amudp_ep**) returning an error code: AM_ERR_RESOURCE (Problem with requested resource)
  from function AMUDP_SPMDStartup
  at ./amudp_spmd.cpp:971
  reason: worker failed DNSLookup on master host name

GASNet initialization encountered an error: "worker AMUDP_SPMDStartup() failed"
  in gasnetc_init at /usr/local/gasnet/udp-conduit/gasnet_core.c:242
*** WARNING (4e25f04e502e:10879): GASNet gasnetc_init returning an error code: GASNET_ERR_RESOURCE (Problem with requested resource)
  at /usr/local/gasnet/udp-conduit/gasnet_core.c:326
*** WARNING (4e25f04e502e:10879): GASNet gex_Client_Init_GASNET_202031PARnopshmFASTnodebugnotracenostatsnodebugmallocnosrclines returning an error code: GASNET_ERR_RESOURCE (Problem with requested resource)
  at /usr/local/gasnet/udp-conduit/gasnet_core.c:504
GASNET: gasnet_init(argc, const_cast<char ***>(argv)) = 3 (GASNET_ERR_RESOURCE, Problem with requested resource)
Terminated

```

Thanks.

**Comment by fdouglis** [comment]
This sounds more like a GASNet bug (or issue) and perhaps orthogonal to FlexFlow.  But  I suggest you post a link to this in the Legion slack if you haven't already, and maybe those on Legion who have worked closely with GASNet will have suggestions.

**Comment by eddy16112** [comment]
Have you tried the MPI conduit? If the MPI conduit works, then I guess the bug might be related to the UDP conduit itself or the configuration of GASNet.
