### ISSUE TITLE
Make number of replicas a `ParallelTensorShape` field, instead of adding a `ParallelDim` to tensors

### ISSUE THREAD

**Issue by goliaro** [flexflow/FlexFlow#585]
Currently, to keep track of the number of replicas that are created for each tensor, we add a `ParallelDim` to each `ParallelTensor`, making it harder for us to implement the operators' kernels correctly. Instead, we'd ideally make the number of replicas a member of the `ParallelTensorShape` struct.

**Comment by lockshaw** [comment]
Replaced by #1276
