### ISSUE TITLE
Incomplete sentence in README

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#634]
> Please subscribe to the FlexFlow users mailing list for

@jiazhihao or @gabrieleoliaro: Any idea what this sentence was supposed to say? Is the mailing list still monitored?

**Comment by lockshaw** [comment]
Linking in #110

**Comment by jiazhihao** [comment]
Good catch. I don't think we are actively monitoring that mailing list. We should use github for tracking all issues.
