### ISSUE TITLE
How do I use mcmc_optimize?

### ISSUE THREAD

**Issue by abhivijay96** [flexflow/FlexFlow#648]
Hello,

Can you please point me to an example using mcmc_optimize function in the model.cc file? I tried browsing the repository, seems like the function is not called from any of the files.

**Comment by lockshaw** [comment]
`mcmc_optimize` is no longer used as of [Unity](https://www.usenix.org/conference/osdi22/presentation/unger). If you'd like to use `mcmc_optimize`, you can use the last pre-unity release (https://github.com/flexflow/FlexFlow/releases/tag/r22.07) or use the new search methods (which are currently in flux implementation-wise but should stabilize within a couple weeks).

**Comment by abhivijay96** [comment]
Thanks a lot! This is very helpful
