### ISSUE TITLE
Runtime Hangs when Running ResNet at larger batch sizes

### ISSUE THREAD

**Issue by bhetherman** [flexflow/FlexFlow#67]
When running the resnet model with a batch size of 128. The runtime hangs when it gets to the training loop. It seems to have something to do with legion because if I remove 'runtime->begin_trace(ctx, 111/*trace_id*/);' and 'runtime->end_trace(ctx, 111/*trace_id*/);' and launch the file with the '-lg:inorder' it will get through the runtime ok. But I imagine there is a performance hit from using '-lg:inorder'.

I also tried with the debug flag enabled but it still just hangs and no error is printed. And i tried using legion spy, the last thing in the  log was '[0 - 7f4214849fc0]   19.405782 {3}{legion_spy}: Future Creation 4893 0 4 0 0 0 0'

Not sure whats going on but there seems almost like its not behaving in a milti-thread/process safe manner. Otherwise why would forcing In-Order Execution make a difference?

Any help or suggestions would be appreciated. Thanks!

**Comment by jiazhihao** [comment]
@bhetherman I was able to reproduce the issue on my end. The issue is related to how FlexFlow/Legion switches GPU threads. Can you add `-ll:streams 1` to your command line and see if this can fix the issue?
