### ISSUE TITLE
Assertion failed when running Alexnet example

### ISSUE THREAD

**Issue by ylxdzsw** [flexflow/FlexFlow#7]
Hi, I tried to run the AlexNet example but failed with an assertion error with no meaningful error messages. I tried all three released versions (I can't get master compiled) and they all reports the same error.

```
$ ./alexnet -b 4 -ll:gpu 2 --ll:fsize 16130 -ll:zsize 5000

--------  Start FlexFlow Runtime  --------
batchSize(4) inputHeight(224) inputWdith(224)
workersPerNode(2) loadersPerNode(4)
datasetPath(synthetic data)
strategy(Default Data Parallelism)
Create Alexnet:
    Create conv layer: output(n=4 c=64 h=55 w=55)
    Create pool2d layer: output(n=4 c=64 h=27 w=27)
    Create conv layer: output(n=4 c=192 h=27 w=27)
    Create pool2d layer: output(n=4 c=192 h=13 w=13)
    Create conv layer: output(n=4 c=384 h=13 w=13)
    Create conv layer: output(n=4 c=256 h=13 w=13)
    Create conv layer: output(n=4 c=256 h=13 w=13)
    Create pool2d layer: output(n=4 c=256 h=6 w=6)
    Create flat layer: input(N=4 C=256 H=6 W=6) -> output(N=4 C=9216)
    Create linear layer: output(n=4 c=4096))
    Create linear layer: output(n=4 c=4096))
    Create linear layer: output(n=4 c=1000))
alexnet: linear.cu:519: static void Linear::backward_task(const Legion::Task*, const std::vector<Legion::PhysicalRegion>&, Legion::Context, Legion::Runtime*): Assertion `acc_kernel_grad.accessor.is_dense_arbitrary(rect_kernel_grad)' failed.
Aborted (core dumped)
```

Ubuntu 16.04 + CUDA 10.1 + CuDNN 7 with 2 Tesla V100. Legion is compiled following the guide with default options except for `USE_CUDA=1`.

**Comment by ylxdzsw** [comment]
Hi, I simply deleted all the `assert`s and now it _seems_ that it runs well. Not sure what's the subsequence.

**Comment by glauer53** [comment]
I'm running the simulator in the script directory.
When I change the example from nmt to alexnet, I get an assert complaining that c.nDims==1 failed.
(I get similar assert failures for resnet, densenet, inceptionnet, etc.)

Here's a typical backtrace from gdb, followed by a print(c) of the object failing the assert.

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fffd843e801 in __GI_abort () at abort.c:79
#2  0x00007fffd842e39a in __assert_fail_base (fmt=0x7fffd85b57d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5555555f0e27 "c.nDims == 1", 
    file=file@entry=0x5555555f0d60 "simulator.cc", line=line@entry=284, 
    function=function@entry=0x5555555f1960 <Pool2D::compute(OpConfig)::__PRETTY_FUNCTION__> "virtual float Pool2D::compute(OpConfig)") at assert.c:92
#3  0x00007fffd842e412 in __GI___assert_fail (assertion=0x5555555f0e27 "c.nDims == 1", file=0x5555555f0d60 "simulator.cc", line=284, 
    function=0x5555555f1960 <Pool2D::compute(OpConfig)::__PRETTY_FUNCTION__> "virtual float Pool2D::compute(OpConfig)") at assert.c:101
#4  0x0000555555578e19 in Pool2D::compute (this=0x55558342bb80, c=...) at simulator.cc:284
#5  0x000055555557aaa9 in simulate_time (global=std::map with 12 elements = {...}, print=true) at simulator.cc:924
#6  0x0000555555583394 in main () at simulator.cc:1440

print(c)
$2 = {nDims = 2, nParts = 8, dim = {8, 1, 0, 0}, map = {0, 1, 2, 3, 4, 5, 6, 7, 1434542400, 21845, -7504, 32767, 1431878940, 21845, 1432047008, 21845, 1434542400, 21845, -7472, 32767, 
    1431868600, 21845, 1432044480, 21845, 1434542400, 21845, -7440, 32767, -662772184, 32767, 1431891256, 21845, -666626935, 32767, -7408, 32767, 2, 0, -7376, 32767, 1434520352, 
    21845, 1, 0, 1431844710, 21845, 1434520352, 21845, 65535, 1, 1431992803, 21845, 1431844732, 21845, 19, 0, 1432291997, 21845, -136423008, 32767, 0, 0, 1432291920, 21845}}

I reran after setting a breakpoint at simulator.cc:284 and see that (earlier in the execution) the object (c) is the same except for nDims...

print(c)
$1 = {nDims = 1, nParts = 8, dim = {8, 1, 0, 0}, map = {0, 1, 2, 3, 4, 5, 6, 7, 1434542400, 21845, -7504, 32767, 1431878940, 21845, 1432047008, 21845, 1434542400, 21845, -7472, 32767, 
    1431868600, 21845, 1432044480, 21845, 1434542400, 21845, -7440, 32767, -662772184, 32767, 1431891256, 21845, -666626935, 32767, -7408, 32767, 2, 0, -7376, 32767, 1434520352, 
    21845, 1, 0, 1431844710, 21845, 1434520352, 21845, 65535, 1, 1431992803, 21845, 1431844732, 21845, 19, 0, 1432291997, 21845, -136423008, 32767, 0, 0, 1432291920, 21845}}

Thoughts?
Thanks,
Greg

**Comment by Orion-wyc** [comment]
I encountered the same problem. Assertion appeared while testing AlexNet.

Details:
```shell
alexnet: model.cu:50: static FFHandler UtilityTasks::init_cuda_task(const Legion::Task*, const std::vector<Legion::PhysicalRegion>&, Legion::Context, Legion::HighLevelRuntime*): Assertion `memFB.size() == 1' failed.
Aborted (core dumped)
```
