### ISSUE TITLE
Getting errors when building FlexFlow

### ISSUE THREAD

**Issue by aoranwu** [flexflow/FlexFlow#70]
Hi,

I try to build FlexFlow runtime following the instructions. When running "./ffcompile.sh examples/cpp/InceptionV3", there are some errors occurring:

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1761): error: identifier "__builtin_ia32_sqrtsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1770): error: identifier "__builtin_ia32_sqrtss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2728): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2737): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11265): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11274): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1163): error: identifier "__builtin_ia32_reducesd" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1171): error: identifier "__builtin_ia32_reducess" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1179): error: identifier "__builtin_ia32_rangesd128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1189): error: identifier "__builtin_ia32_rangess128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1198): error: identifier "__builtin_ia32_rangesd128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1207): error: identifier "__builtin_ia32_rangess128_round" is undefined

12 errors detected in the compilation of "/tmp/tmpxft_00013d3f_00000000-18_simulator.compute_75.cpp1.ii".
/home/wisr/aoranwu/FlexFlow/legion/runtime/runtime.mk:1103: recipe for target '/home/wisr/aoranwu/FlexFlow/src/runtime/simulator.cu.o' failed
make: *** [/home/wisr/aoranwu/FlexFlow/src/runtime/simulator.cu.o] Error 1
make: *** Waiting for unfinished jobs....

Is there any way to solve that? Thanks!

**Comment by aoranwu** [comment]
The command causing this error is 
```bash
/usr/local/cuda/bin/nvcc -o /home/wisr/aoranwu/FlexFlow/src/runtime/simulator.cu.o -c /home/wisr/aoranwu/FlexFlow/src/runtime/simulator.cu -DMAX_TENSOR_DIM=4                 -std=c++11  -O2   -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_53,code=sm_53 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_62,code=sm_62 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_72,code=sm_72 -gencode arch=compute_75,code=sm_75 -Xcudafe --diag_suppress=boolean_controlling_expr_is_constant -I/home/wisr/aoranwu/FlexFlow/include/ -I/include -I/home/wisr/aoranwu/FlexFlow/protobuf/src -I/home/wisr/aoranwu/FlexFlow/examples/cpp/InceptionV3 -I/home/wisr/aoranwu/FlexFlow/legion/runtime -I/home/wisr/aoranwu/FlexFlow/legion/runtime/mappers -I/usr/local/cuda/include -I/home/wisr/aoranwu/FlexFlow/legion/runtime/realm/transfer
```
So that error happens when trying to use nvcc to compile simulator.cu

Any help would be appreciated. Thanks!

**Comment by Terex12** [comment]
I encountered a similar error when I used g++/gcc7. I think you can use a different version of g++/gcc. When I switched to g++/gcc6, the error disappeared.
