### ISSUE TITLE
Question on add_operator_cost in graph_cost

### ISSUE THREAD

**Issue by lei-houjyu** [flexflow/FlexFlow#718]
Hi,

When reading the source code, I noticed that no matter if the current graph is cached or not in `SearchHelper::graph_cost`, the compute time of the sink node will be added to the cost (if `include_sink_compute_time` is set to true, which seems the default value). I was expecting the compute time is only added to the cost in a cache miss, otherwise the compute time would be counted for multiple times (if the same graph is queried again), right? Did I miss anything? Any explanation would be highly appreciated!

**Comment by lockshaw** [comment]
I believe the cost is not added twice because the cost that is cached is always without the sink time included (https://github.com/flexflow/FlexFlow/blob/ef3b76e2acfe19e3e6340cbcd56fb86bd93f5b69/src/runtime/graph.cc#L1655).
