### ISSUE TITLE
FlexFlow Performance of Alexnet drastically drops in Multi-GPU

### ISSUE THREAD

**Issue by ghostplant** [flexflow/FlexFlow#73]
Environment CUDA V100-PCIE:

FlexFlow-AlexNet (1GPU):
-  data-parallel: 1172.39 samples/s
-  optimized:     2005.06 samples/s

FlexFlow-AlexNet (2GPU):
-  data-parallel:  840.98 samples/s
-  optimized:     2000.77 samples/s

FlexFlow-AlexNet (4GPU):
-  data-parallel:  331.25 samples/s
-  optimized:     1444.97 samples/s

Tensorflow-AlexNet (1GPU):
-  data-parallel:  3079.8 samples/s

Tensorflow-AlexNet (2GPU):
-  data-parallel:  3414.8 samples/s

Tensorflow-AlexNet (4GPU):
-  data-parallel:  3210.6 samples/s

How to fix it?

**Comment by jiazhihao** [comment]
@ghostplant It seems you have been using the sysml19 branch. It is outdated. Can you retry the master branch and see if you still observe the same performance issue? This is a tutorial for auto-tuning strategies: https://flexflow.ai/search/

**Comment by ghostplant** [comment]
Thanks, but I think the number on P100 is OK, so it shouldn't be the environmental problem.
Do you have the optimal result of AlexNet number for V100 officially that is reproducible on master branch?

In the current master branch, I didn't find the identical script to reproduce the mlsys19.

**Comment by jiazhihao** [comment]
I have tested the AlexNet implementation in the master branch (https://github.com/flexflow/FlexFlow/tree/master/examples/cpp/AlexNet) on V100 GPUs. The throughput numbers (with a per-GPU batch-size of 256 and the optimized strategies).

- 1GPU: 3999.13 samples/second
- 2GPUs: 7964.90 samples/second
- 4GPUs: 15085.76 samples/second

**Comment by ghostplant** [comment]
@jiazhihao The performance is great. Can you explain how to build that cpp folder? I have tried many different ways but all failed with errors. Like:
1) I build the docker image `ff:v1`, then `./ffcompile.sh examples/cpp/AlexNet` tells me it only allows directory that contains `Proto Buffer`.
2) I goto directory `examples/cpp/AlexNet`, whatever `cmake .` and `make` will fail for `No rule to make target` or `Unknown CMake command "cuda_add_executable"`

**Comment by jiazhihao** [comment]
@ghostplant Both Makefile and CMake should work. You can find more detailed instructions [here](https://github.com/flexflow/FlexFlow/blob/master/INSTALL.md).

For 1, can you copy paste the exact error message? Also, can you check that you have `strategy.pb.h` and `strategy.pb.cc` in `src/runtime`. It seems like something went wrong when you generated protocol buffer files.

For 2, can you confirm that you have correctly set the CUDA paths required here: https://github.com/flexflow/FlexFlow/blob/master/INSTALL.md#build-flexflow-runtime-with-python-interface-c-interface-is-also-enabled.

**Comment by roman955b** [comment]
@jiazhihao I cannot reproduce the results that you report above:
```
1GPU: 3999.13 samples/second
2GPUs: 7964.90 samples/second
4GPUs: 15085.76 samples/second
```

Can you please share the `config/config.linux` that you used to create the build project (especially how is FF_USE_GASNET, FF_GASNET_CONDUIT and FF_USE_NCCL set)?

Also what is the exact command line  flags that you use to evaluate the strategy (especially:  -ll:py, -ll:util, -ll:bgwork, --batch-size)?

**Comment by roman955b** [comment]
@ghostplant Were you able to reproduce the AlexNet  results  of FlexFlow?
```
1GPU: 3999.13 samples/second
2GPUs: 7964.90 samples/second
4GPUs: 15085.76 samples/second
```

**Comment by ghostplant** [comment]
Can reproduce this number on P100 only.

**Comment by roman955b** [comment]
@eddy16112 @ferdiko  What are the full instructions to reproduce the results for AlexNet? Do you recognize the limitations reported on above?
