### ISSUE TITLE
Something wrong with the SSM between commit b8e558 and f0604b30

### ISSUE THREAD

**Issue by jiazhihao** [flexflow/FlexFlow#735]
Using the most up-to-date inference branch and LLAMA-190M as the LLM, both spec_infer and incr_decoding generates 
```
Give three tips for staying healthy.?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?" world?" world?"?"?" world?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?"?" world?" world?"!"!"!"!"!"!" world?"
```
for the test prompt. 

When we roll back to commit b8e558 and using LLAMA-190M as the LLM, both spec_infer and incremental decoding produces 
```
Give three tips for staying healthy.

The term "flip" is used in the United States to refer to a healthy lifestyle.

The term "flip" is used in the United Kingdom to refer to a healthy lifestyle.

The term "flip" is used in the United States to refer to a healthy lifestyle.

The term "flip" is used in the United States to refer to a healthy lifestyle.

The term "flip" is used in the United States to refer to a healthy l
```
which seems a lot more reasonable.

**Comment by jiazhihao** [comment]
I haven't conducted a binary search to figure out which commit caused the issue.

**Comment by gabrieleoliaro** [comment]
@jiazhihao Are you using the tokenizer from our S3 bucket: https://specinfer.s3.us-east-2.amazonaws.com/tokenizer/tokenizer.model ? I get similar issues when using the tokenizer from Huggingface

**Comment by jiazhihao** [comment]
I used the tokenizer from https://catalyst-llama.s3.us-east-2.amazonaws.com/tokenizer.model. If I change to the new tokenizer, the output token is always larger than 32000. I believe the LLAMA model was trained using the first 32K tokens, which makes outputting tokens whose ids are larger than 32K suspicious.

**Comment by gabrieleoliaro** [comment]
ok, I see! and are these issues only there for the SSM, or is the LLM also showing some weird behavior?

**Comment by jiazhihao** [comment]
It's only for the LLAMA-190M model. This is the command line I used 
```
./inference/spec_infer/spec_infer -ll:gpu 4 -ll:fsize 14000 -ll:zsize 30000 -llm-model llama -llm-weight ../inference/weights/llama_190M_weights/ -llm-config ../inference/models/configs/llama_190M.json -ssm-model llama -ssm-weight ../inference/weights/llama_190M_weights/ -ssm-config ../inference/models/configs/llama_190M.json -tokenizer ../inference/tokenizer/tokenizer.model -prompt ../inference/prompt/test.json
```

**Comment by jiazhihao** [comment]
I think this is also probably why you saw that SpecInfer is slower than IncDecoding --- as the SSM does not generate reasonable tokens.

**Comment by gabrieleoliaro** [comment]
Yeah, that is likely the issue

**Comment by xinhaoc** [comment]
What is the command line you are using to reproduce this bug,, I got correct results on the inference branch.

**Comment by Z-Y00** [comment]
Hi, 
I'm just wondering if the SSM data will be updated.
Also, if you will upload collectively boost-tuned SSMs, so far it seems there is only one.

**Comment by jiazhihao** [comment]
@Z-Y00 #734 will add support for multiple SSMs. We are working on uploading the boost-tuned SSMs.
