### ISSUE TITLE
FlexFlow mnist_mlp.py Test Failed 

### ISSUE THREAD

**Issue by DerrickYLJ** [flexflow/FlexFlow#753]
I followed instructions in the documentation to check if FlexFlow has been installed correctly and run the following command on Fleet Machine:
```
cd python
./flexflow_python examples/python/native/mnist_mlp.py -ll:py 1 -ll:gpu 1 -ll:fsize <size of gpu buffer> -ll:zsize <size of zero buffer>
```
In which I replace `<size of gpu buffer>` and `<size of zero buffer>` with 1.
However, the error message is:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
      Output information may be incomplete.
Linked to libnvidia-ml library at wrong path : /usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libnvidia-ml.so

[0 - 7fd76c266000]    0.144761 {6}{python}: libpython3.11.so: cannot open shared object file: No such file or directory
flexflow_python: /home/lijiey/FFW/FlexFlow/deps/legion/runtime/realm/python/python_module.cc:176: Realm::PythonInterpreter::PythonInterpreter(): Assertion `false' failed.
Aborted (core dumped)
```

Based on the error, it seems some files on my end are missing.

**Comment by eddy16112** [comment]
It is because libpython3.11.so is not under your LD_LIBRARY_PATH, if you are using conda, you probably need to export something like `export LD_LIBRARY_PATH=/path-to-anaconda3/envs/myenv/lib:$LD_LIBRARY_PATH`

**Comment by DerrickYLJ** [comment]
should I add `export LD_LIBRARY_PATH=/path-to-anaconda3/envs/myenv/lib:$LD_LIBRARY_PATH` to `~/.bashrc` as well?

**Comment by eddy16112** [comment]
depends on if you want to do the export every time or not.

**Comment by DerrickYLJ** [comment]
> should I add `export LD_LIBRARY_PATH=/path-to-anaconda3/envs/myenv/lib:$LD_LIBRARY_PATH` to `~/.bashrc` as well?

It still aborts after I have exported the line above to `~/.bashrc`

**Comment by eddy16112** [comment]
Could you please print your LD_LIBRARY_PATH and also paste the result of ldd flexflow_python

**Comment by DerrickYLJ** [comment]
I wonder how to print my LD_LIBRARY_PATH.

```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
export FF_HOME=/path/to/FlexFlow
export LD_LIBRARY_PATH=/path-to-anaconda3/envs/myenv/lib:$LD_LIBRARY_PATH
```

This is what it looks like in my bash file now.

**Comment by eddy16112** [comment]
Do echo $LD_LIBRARY__PATH

**Comment by DerrickYLJ** [comment]
(1) The path doesn't show up. 
<img width="234" alt="Screen Shot 2023-06-04 at 11 52 13 AM" src="https://github.com/flexflow/FlexFlow/assets/99985904/4ccaaf4a-bb19-4834-aa83-7ea7dca52262">

(2) What do you mean by "the result of ldd flexflow_python" and how to obtain it?

Thanks.

**Comment by eddy16112** [comment]
Then it means your LD_LIBRARY_PATH is not set correctly. It couldn't be empty.

**Comment by eddy16112** [comment]
As I said before https://github.com/flexflow/FlexFlow/issues/753#issuecomment-1575221839, please make sure to change `/path-to-anaconda3/envs/myenv/lib` to the lib directory of your conda env.

**Comment by DerrickYLJ** [comment]
```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
export FF_HOME=/path/to/FlexFlow
export LD_LIBRARY_PATH=/path-to-anaconda3/envs/myenv/lib:$LD_LIBRARY_PATH
```
Right now my `~/.bashrc` looks like the above, isn't this what you mean?
If not, do you mind explaining what I should do in more detail? 

Thanks

**Comment by eddy16112** [comment]
Looks correct, make sure your bashrc is actually executed, and then you should be able to see the correct LD_LIBRARY_PATH using echo $LD_LIBRARY_PATH

**Comment by DerrickYLJ** [comment]
Is there a way to check if  my `bashrc` is actually executed?

**Comment by eddy16112** [comment]
You can add a `echo "hello"` in bashrc to see if it prints. BTW, why do you have to add `export` into bashrc, you can explicitly run it in your terminal.
