### ISSUE TITLE
[SpecInfer] How to use Collective Boost-Tuning?

### ISSUE THREAD

**Issue by frankxyy** [flexflow/FlexFlow#760]
Hi, is there a doc and code about this?

**Comment by lockshaw** [comment]
@jiazhihao Do you know what this is referring to?

**Comment by JackFram** [comment]
We will release the Collective Boost-Tuning code once we clean up the code base. Basically, we fine-tuned 4 more SSMs (LLaMA-160m) besides the base version on OpenWebText datasets to align with the LLM.

**Comment by ehuaa** [comment]
> We will release the Collective Boost-Tuning code once we clean up the code base. Basically, we fine-tuned 4 more SSMs (LLaMA-160m) besides the base version on OpenWebText datasets to align with the LLM.

Hi Jack, is it ready for you to share your Collective Boost-Tuning code, i'm very looking forward to using this feature, thanks! @JackFram

**Comment by JackFram** [comment]
Hi, if you are looking for the original collective boost-tuned models they are [here](https://huggingface.co/JackFram). If you are looking for the source code to train them, as we are currently improving our algorithms, we will release the code once the implementation is finalized. Thanks for your interests!

**Comment by ehuaa** [comment]
> Hi, if you are looking for the original collective boost-tuned models they are [here](https://huggingface.co/JackFram). If you are looking for the source code to train them, as we are currently improving our algorithms, we will release the code once the implementation is finalized. Thanks for your interests!

Thanks for your reply, if i want to train my own boost-tuned models with my DIY LLM, can i just use the code to be released mentioned above and my own datasets to get these ssm models?

**Comment by JackFram** [comment]
Sure, once we have finalized our improvement, you can try using the code to tune the SSMs accordingly.

**Comment by ehuaa** [comment]
> Sure, once we have finalized our improvement, you can try using the code to tune the SSMs accordingly.

ok, thanks
