### ISSUE TITLE
A PR already exists for flexflow:inference.

### ISSUE THREAD

**Issue by DerrickYLJ** [flexflow/FlexFlow#775]
I am trying to create a PR for updating process of building and publish docker images in `inference` branch. However, I met this error saying `GraphQL error: A pull request already exists for flexflow:inference.`

I don't think this PR is already created but currently wonder how to resolve the issue.

Thanks!

![Screen Shot 2023-06-16 at 7 25 18 PM](https://github.com/flexflow/FlexFlow/assets/99985904/2de74afc-6ef9-4b15-9734-a1671445ed25)

**Comment by jiazhihao** [comment]
You tried to merge `inference` to `master`, which is exactly this PR's job (https://github.com/flexflow/FlexFlow/pull/475). You may want to merge your local branch to `inference`

**Comment by DerrickYLJ** [comment]
![Screen Shot 2023-06-16 at 8 14 23 PM](https://github.com/flexflow/FlexFlow/assets/99985904/b802ca44-6921-46b8-af64-f561e1ca0ec4)

Thanks for your reply!

I tried to merge local branch to `inference` but it says `failed to execute git`. I check `git status` it shows `Your branch is ahead of 'origin/inference' by 1 commit.` so I am not sure why this happens.

**Comment by jiazhihao** [comment]
The `merge changes from`'s remote repo should be your local FlexFlow repo instead of the public one.

**Comment by DerrickYLJ** [comment]
In `merge changes from` section, `remote` only has single option, and `branch` are all current available branches on github. Am I doing anything wrong here?

![Screen Shot 2023-06-16 at 8 38 01 PM](https://github.com/flexflow/FlexFlow/assets/99985904/f077e644-2511-4bbb-9a52-e7cb2d63d518)
![Screen Shot 2023-06-16 at 8 40 20 PM](https://github.com/flexflow/FlexFlow/assets/99985904/274c546b-98b6-40dd-91a9-b1cd93723803)

**Comment by gabrieleoliaro** [comment]
Which branch/fork did you make your changes on? Could you run, in the main FlexFlow folder, the following commands from terminal, and post the result here: `git status` and `git log`?
