### ISSUE TITLE
SpecInfer not available in docker image provided?

### ISSUE THREAD

**Issue by yuchen2580** [flexflow/FlexFlow#782]
Hi,
I tried to follow the readme and download the pre-build docker image for test,
but it seems there is no inference folder in the pre-build image, 
or am I looking at the wrong place?
Best.

**Comment by gabrieleoliaro** [comment]
Hi @yuchen2580 ! We will be publishing docker images for SpecInfer in the next few days; in the meantime, if you'd like to run SpecInfer within docker, you can do the following:

1. Clone the FlexFlow repo, and checkout the inference branch (`git checkout -b inference --recursive https://github.com/flexflow/FlexFlow.git`)
2. Open the main FlexFlow folder in the terminal
3. Build the docker machine for SpecInfer using `./docker/build.sh`
4. Run the machine with `./docker/run.sh`

Make sure that you have a NVIDIA gpu on the machine where you are trying SpecInfer. The script should then automatically build a Docker machine using the proper version of CUDA.

**Comment by gabrieleoliaro** [comment]
closing for now, feel free to open another issue if you encounter any problem!
