### ISSUE TITLE
Add cargo check in cmake

### ISSUE THREAD

**Issue by jiazhihao** [flexflow/FlexFlow#809]
Since building tokenizers-cpp requires cargo, we should add a cargo check in cmake. Otherwise, users will get a `No such file or directory` error, which is not very helpful.

**Comment by gabrieleoliaro** [comment]
@jiazhihao This should already be implemented in the `inference` branch (see [here](https://github.com/flexflow/FlexFlow/blob/inference/CMakeLists.txt#L485:L492)). Which branch did you encounter the error above in? Is the branch updated (did you rebase on / merge the `inference` branch recently)

**Comment by jiazhihao** [comment]
I used the inference branch and installed rust using `apt-get install`, which doesn't install cargo by default.

**Comment by jiazhihao** [comment]
I am not sure if this is a common error or just me.

**Comment by gabrieleoliaro** [comment]
I usually install Rust with: `curl https://sh.rustup.rs -sSf | sh -s -- -y`. Can you try to see if this works? After installing, you also need to follow the instructions on the screen to add Rust to the bash profile

**Comment by gabrieleoliaro** [comment]
I see! Maybe we should check for cargo and rust separately in the cmake, and print a separate error message if Rust is installed but cargo is not. Also, if Rust is not i stalled, maybe we should print, as part of the error message, the instructions to install it with cargo also included
