### ISSUE TITLE
How does Legion apply to FlexFLow?

### ISSUE THREAD

**Issue by AngryBear2** [flexflow/FlexFlow#811]
Hello, at the SysML conference in 2019, I noticed a question on the spot, you mentioned using Legion as a distributed runtime for FlexFlow, and I had some knowledge about Legion before. Could you provide more documentation or video tutorials on how Legion is used in FlexFlow, or what Legion is used for, and how it interfaces with FlexFlow?

**Comment by lockshaw** [comment]
Legion is used to coordinate distributed execution in FlexFlow: ordering of tasks, moving tensors between tasks, and partitioning computations. Currently there exist a number of calls to Legion's `TaskLauncher` and `IndexLauncher` (see https://github.com/flexflow/FlexFlow/blob/be34be6da03577fdbb33c5fff4614537ab628056/src/ops/element_binary.cc#L272-L279) for an example. In the future, #622 will be merged, which provides a more structured interface with Legion.

**Comment by AngryBear2** [comment]
Thank you very much for reading my question carefully and providing me with help. If I don't need the policy and hierarchical parallelism provided by FlexFLow, and just think about using Legion for DNN, do I just have to emulate FlexFlow/src/ops/* with FlexFlow/runtime/model.cc?
