### ISSUE TITLE
Preparing model weights for LLaMA-13B, LLaMA-33B, LLaMA-65B

### ISSUE THREAD

**Issue by jiazhihao** [flexflow/FlexFlow#823]
We currently support the LLaMA-7B model (https://github.com/flexflow/FlexFlow/tree/inference#llm-weights), it would be great to add preprocessed LLaMA-13B, 33B, and 65B weights to S3. We can only target half precision weights for these models.

@DerrickYLJ you can take a look at this script for processing weights: https://github.com/flexflow/FlexFlow/blob/inference/inference/utils/download_opt_weights.py and talk to @gabrieleoliaro for questions.

**Comment by DerrickYLJ** [comment]
I am reading through the https://github.com/flexflow/FlexFlow/blob/inference/inference/utils/download_opt_weights.py while I noticed that there is also a file that specifically deals with  https://github.com/flexflow/FlexFlow/blob/inference/inference/utils/download_llama_weights.py. Should I follow the code of the `download_opt_weights.py` or `download_llama_weights.py` while trying to process weights of LLaMA-13B, 33B, and 65B?

Thanks!
