### ISSUE TITLE
Legion Error:  error_code_68

### ISSUE THREAD

**Issue by aj-prime** [flexflow/FlexFlow#9]
I am trying to run alexnet example with sysml19_ae branch.

My run command is:
./alexnet -b 64 -ll:gpu 1 -ll:fsize 5000 -ll:zsize 5000 --strategy strategies/alexnet_data_parallel.strategy

The output is:
--------  Start FlexFlow Runtime  --------
batchSize(64) inputHeight(224) inputWdith(224)
workersPerNode(1) loadersPerNode(8)
datasetPath(synthetic data)
strategy(strategies/alexnet_data_parallel.strategy)
Default Data Parallelism
Create Alexnet:
    Create conv layer: output(n=64 c=64 h=55 w=55)
    Create pool2d layer: output(n=64 c=64 h=27 w=27)
    Create conv layer: output(n=64 c=192 h=27 w=27)
    Create pool2d layer: output(n=64 c=192 h=13 w=13)
    Create conv layer: output(n=64 c=384 h=13 w=13)
    Create conv layer: output(n=64 c=256 h=13 w=13)
    Create conv layer: output(n=64 c=256 h=13 w=13)
    Create pool2d layer: output(n=64 c=256 h=6 w=6)
    Create flat layer: input(N=64 C=256 H=6 W=6) -> output(N=64 C=9216)
    Create linear layer: output(n=64 c=4096))
    Create linear layer: output(n=64 c=4096))
    Create linear layer: output(n=64 c=1000))
[0 - 2ab352172700] {5}{runtime}: [error 68] LEGION ERROR: Region requirement 0 of operation linear_init_task (UID 110) in parent task top_level (UID 1) is using uninitialized data for field(s) 0 of logical region (82,1,41) with read-only privileges (from file legion/runtime/legion/legion_ops.cc:518)[error 68]
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_68

**Comment by moderato** [comment]
Same error here when running the DLRM example.

**Comment by Orion-wyc** [comment]
> Same error here when running the DLRM example. Anyone could help?

Can you run any other examples (Alexnet or Resnet) without  error?

**Comment by moderato** [comment]
Alexnet and InceptionV3 work well for me without specifying a dataset (I suppose it's using synthetic data). Very strangely, when I rebuild the DLRM example it now gives me this error...
```
[0 - 7f5b7c4c1700] {4}{gpu}: CUDART hijack code not active - device synchronizations required after every GPU task!
[0 - 7f5b7c502700] {3}{Mapper}: No strategy file provided. Use default data parallelism.
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
./run_criteo_kaggle.sh: line 8: 27283 Aborted                 (core dumped) ./dlrm -ll:gpu ${numgpu} -ll:cpu 1 -ll:fsize 12000 -ll:zsize 20000 --arch-sparse-feature-size 16 --arch-embedding-size 1396-550-1761917-507795-290-21-11948-608-3-58176-5237-1497287-3127-26-12153-1068715-10-4836-2085-4-1312273-17-15-110946-91-72655 --arch-mlp-bot 13-512-256-64-16 --arch-mlp-top 224-512-256-1 --epochs 100 --batch-size ${batchsize} --dataset ${dataset}
```

Any thoughts?

**Comment by Orion-wyc** [comment]
> Alexnet and InceptionV3 work well for me without specifying a dataset (I suppose it's using synthetic data). Very strangely, when I rebuild the DLRM example it now gives me this error...
> 
> ```
> [0 - 7f5b7c4c1700] {4}{gpu}: CUDART hijack code not active - device synchronizations required after every GPU task!
> [0 - 7f5b7c502700] {3}{Mapper}: No strategy file provided. Use default data parallelism.
> terminate called after throwing an instance of 'std::logic_error'
>   what():  basic_string::_M_construct null not valid
> ./run_criteo_kaggle.sh: line 8: 27283 Aborted                 (core dumped) ./dlrm -ll:gpu ${numgpu} -ll:cpu 1 -ll:fsize 12000 -ll:zsize 20000 --arch-sparse-feature-size 16 --arch-embedding-size 1396-550-1761917-507795-290-21-11948-608-3-58176-5237-1497287-3127-26-12153-1068715-10-4836-2085-4-1312273-17-15-110946-91-72655 --arch-mlp-bot 13-512-256-64-16 --arch-mlp-top 224-512-256-1 --epochs 100 --batch-size ${batchsize} --dataset ${dataset}
> ```
> 
> I also try the DLRM example on another of our server machines, and it throws the original error though.
> 
> Any thoughts

I haven’t tried DLRM so far. You are right. It works well without strategies and datasets. 
I want to know how to automatically generate a strategy for a DNN, as described in the paper.
Have you tried using strategies？
The simulator.cc provided in the scripts floder seems to output a series of candidate strategies, but how to deploy these strategies？
You can also refer to another issue
https://github.com/flexflow/FlexFlow/issues/14#issue-596610386

**Comment by jiazhihao** [comment]
@moderato The strategy files provided in the sysml19_ae branch is deprecated. This file (https://github.com/flexflow/FlexFlow/blob/master/src/runtime/dlrm_strategy.cc) demonstrates how to generate strategy files for DLRM. I am currently working on updating the FlexFlow generator to support the new strategy format.

**Comment by moderato** [comment]
@jiazhihao Sounds cool, thank you for the reply! Is the error we encountered here related to the mismatch you mentioned here? [https://github.com/flexflow/FlexFlow/issues/14](url)
