### ISSUE TITLE
Assertion failure in softmax's backward_kernel

### ISSUE THREAD

**Issue by suranap** [flexflow/FlexFlow#906]
Building a Debug release on Crusher (AMD), I get this error running mnist_mlp

```
Cuda failure: 1
/ccs/home/suranap/FRONTIER/projects/BertMLM_fixes/src/ops/kernels/softmax.cpp:125
Aborting...
flexflow_python: /ccs/home/suranap/FRONTIER/projects/BertMLM_fixes/src/ops/kernels/softmax.cpp:125: void FlexFlow::Kernels::Softmax::Internal::backward_kernel(float *, const float *, size_t, hipStream_t): Assertion `false' failed.
Aborted
```

I changed this [line](https://github.com/flexflow/FlexFlow/blob/d3ffa431ac21b187b91c219b70f8ab2b6a92f70b/src/ops/softmax.cc#L382) and it works now:
```
    backward = [=] {
```

Aren't these technically dangling references if you use `[&]` and your variables go out of scope? ChatGPT thinks so. 

Here's the command to run mnist:
```
./python/flexflow_python ./examples/python/native/mnist_mlp.py -ll:py 1 -ll:gpu 1 -ll:fsize 8000 -ll:zsize 4000
```

**Comment by lockshaw** [comment]
Yup, that's a bug. Do you have time to file a PR to master with a fix?
