### ISSUE TITLE
Missing Support For StarCoder Backbones

### ISSUE THREAD

**Issue by VenkatKS** [flexflow/FlexFlow#917]
Hi everyone! 

I was wondering if we could include support (including for batched inference and online inference) for starcoder backbones? 

I was hoping to use it as a backend for both starcoder7B and starcoder16B models, with a prioritization of the 7B model -- and having support for these backbones, including for batched inference and online inference, would be great! I've found that starcoder is strong for a variety of use cases, and leveraging this framework would be extremely helpful. 

Thank you so much!

**Comment by jiazhihao** [comment]
Hi @VenkatKS , we are currently working on adding support for StarCoder.
