### ISSUE TITLE
Implement command line parsing and help printing

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#942]
On master, all command line parsing is done in a giant switch case in `model.cc` (see [here](https://github.com/flexflow/FlexFlow/blob/master/src/runtime/model.cc#L3501-L3730)). However, doing it this way prevents us from adding automatic help text generation, etc. 

One way to fix this would be to use a third-party command line parsing library. However, all of the ones I (@lockshaw) have looked into do not allow arguments of the form Legion uses, e.g., 
```
$ ./my-executable -flag 5
```
as typically this would be interpreted as the same as passing
```
$ ./my-executable -f -l -a -g 5
```
Feel free to do some looking, and if you find one that I missed that would let us do that, feel free to let @lockshaw know. 

Assuming this is correct, we should write a small command-line parsing library in `utils` that supports this syntax, and move argument parsing over to it. In addition, argument parsing for `FlexFlow` happens in multiple layers, i.e.,
```
user executable ---> user program-specific flags (model size, etc.)
    |
    |
    |
    v
flexflow runtime --> ff flags (simulator size, profiling, etc.)
    |
    |
    |
    v
legion runtime ----> legion flags (-ll:gpu, -ll:cpu, -lg:prof, etc.) 
```
So likely argument parsing will need to be done in a series of passes and will not be able to rely on having the full definition in a single place.

**Comment by lambda7xx** [comment]
I use a third party that TVM community uses it.   https://github.com/p-ranav/argparse. I will set a PR.

**Comment by lambda7xx** [comment]
But the argument parsing still needs to add the definition. the argparse example is below.

```
#include <argparse/argparse.hpp>

int main(int argc, char *argv[]) {
  argparse::ArgumentParser program("main");
  //program.add_argument("thing").help("Thing to use.").metavar("THING");
  program.add_argument("--member").help("The alias for the member to pass to.").metavar("ALIAS");
  program.add_argument("--verbose").default_value(false).implicit_value(true);
  program.add_argument("--version-hello");//.default_value("version-3.14");
  program.add_argument("--batch-size").default_value(32).help("Batch size.");
  program.add_argument("--learning-rate").default_value(0.01).help("Learning rate.");
  program.add_argument("-ll:gpu").default_value((size_t)2).help("Number of GPUs to use.");
// program.add_description("Forward a thing to the next member.");
  //program.add_epilog("Possible things include betingalw, chiz, and res.");
  program.parse_args(argc, argv);
  std::cout<<program.get<std::string>("--version-hello")<<std::endl;
  std::cout<<program.get<int>("--batch-size")<<std::endl;
  std::cout<<program.get<double>("--learning-rate")<<std::endl;
    std::cout<<program.get<size_t>("-ll:gpu")<<std::endl;
  //std::cout << program << std::endl;
}

```

**Comment by lockshaw** [comment]
For the most part completed in #1490.
