### ISSUE TITLE
Read through FlexFlow python bindings on master (at a high level). Figure out where the corresponding code is in repo-refactor

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#953]
Note that not all code may have been ported over--in this case, this should also be identified.

`grep/ag/rg` will likely be your friend here

**Comment by lockshaw** [comment]
Write up a brief explanation of what you've identified below. This will be helpful for us in sketching out any changes we will need to make to the python structure, figuring out which code still needs to be brought over, which code needs to be updated to support new interfaces in `repo-refactor`, etc.

**Comment by junyizha** [comment]
Python binding on the master branch binds important FlexFlow C++ functions like beginning and finishing a flexflow task, initializing optimizers, FFmodel and tensor operations, to their corresponding Python equivalence using pybind11 library. Now in the repo-refactor branch, old Python bindings code is refactored mainly under python/flexflow_c.cc/.h. Specific implementations are under lib/ffi and lib/pcg. All bindings from the master branch have been ported over in the expanded-ffi branch under a rough skim.
