### ISSUE TITLE
Refactor the PCG and CG to be an `OutputLabelledOpenMultiDiGraph`

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#956]
Not 100% sure this is a good idea, so this issue also consists of looking into it and figuring out if it makes sense or not. 

The reason behind this is to eliminate `Input` nodes, which have somewhat strange behavior, and in theory if edges in the PCG represent tensors, then it should be able to model them just with input edges, and same with output tensors. However, I don't know how this would interface with SP decomposition, device placement (data ultimately does have to be loaded from somewhere, so maybe the `Input` node really just conceptually is modelling data loading?), etc.

**Comment by wmdi** [comment]
I don't think this would affect SP decomposition much, as it would be easy to generalize SP decomposition for open graphs. But for device placement, I think it would be better to keep `Input` nodes to model data loading for initial data. The concept of `Input` nodes would also be consistent with other frameworks and easier for users to build models. I would also like to know more about the strange behavior of having `Input` nodes and think more about this.
