### ISSUE TITLE
Problem running FFConfig after installing Python FlexFlow

### ISSUE THREAD

**Issue by Efrainq07** [flexflow/FlexFlow#98]
After installing Flexflow again and trying to test with the examples there was an error particularly when trying to call `FFConfig()`
![image](https://user-images.githubusercontent.com/33973526/108284751-6e2f1f80-714b-11eb-802f-7b5f4b941144.png)

There were no errors when building so the only problem appeared at the end when testing flexflow. Notice that the library can be imported with no problems, but the error happens anyway.
The steps I followed for the installation were these:
`export FF_HOME=$HOME/FlexFlow/`
`export CUDNN_HOME=$CUDNN_ROOT_DIR`
`export PROTOBUF_DIR=/public/apps/protobuf/v3.10.1/gcc.7.3.0/`
`export LG_RT_DIR=$HOME/FlexFlow/legion/runtime`
`export CUDA_ARCH="60,70"`
`export GPU_ARCH="60,70"`
`git clone --recursive git@github.com:flexflow/FlexFlow.git`
`cd FlexFlow/nccl`
`make -j src.build NVCC_GENCODE="-gencode=arch=compute_60,code=sm_60"`
`cd ../python`
`make -j`

**Comment by eddy16112** [comment]
This is not how flexflow python support works. Here is the instruction of how to build the flexflow python. 
https://github.com/flexflow/FlexFlow/blob/master/INSTALL.md#build-flexflow-runtime-with-python-interface-c-interface-is-also-enabled

This script shows how to run the flexflow python examples
https://github.com/flexflow/FlexFlow/blob/master/python/test.sh

**Comment by Efrainq07** [comment]
Sorry, forgot to mention when I set the environment variables. I edited the issue with that, I pretty much followed the steps on that link you mentioned. I had already done the installation the same way before and ran the examples.

**Comment by eddy16112** [comment]
You can not run your python program with the native python interpreter (python script.py), instead, you will need to use flexflow_python, just check this script https://github.com/flexflow/FlexFlow/blob/master/python/test.sh

**Comment by Efrainq07** [comment]
That was the solution thanks.
