### ISSUE TITLE
Add unit tests for labelled graphs in utils

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#986]

**Comment by lockshaw** [comment]
Once #940 is merged

**Comment by lockshaw** [comment]
@wmdi Is this issue entirely addressed by #1224 or is additional work needed after that is merged?

**Comment by lockshaw** [comment]
@Marsella8 this is a really old issue so feel free to say it's no longer makes sense as worded, but would you say that this is addressed in #1464 or is additional work needed for this?

**Comment by Marsella8** [comment]
Test coverage seems pretty good for graphs so far, I'll close this PR and we can increase coverage in the future if needed
